using System;

namespace PersonalTools.Enums
{
    /// <summary>
    /// TILE-Gx Relocation Types
    /// </summary>
    [Flags]
    public enum TILEGxRelocationType : uint
    {
        R_TILEGX_NONE = 0,                     /* No reloc */
        R_TILEGX_64 = 1,                       /* Direct 64 bit */
        R_TILEGX_32 = 2,                       /* Direct 32 bit */
        R_TILEGX_16 = 3,                       /* Direct 16 bit */
        R_TILEGX_8 = 4,                        /* Direct 8 bit */
        R_TILEGX_64_PCREL = 5,                 /* PC relative 64 bit */
        R_TILEGX_32_PCREL = 6,                 /* PC relative 32 bit */
        R_TILEGX_16_PCREL = 7,                 /* PC relative 16 bit */
        R_TILEGX_8_PCREL = 8,                  /* PC relative 8 bit */
        R_TILEGX_HW0 = 9,                      /* hword 0 16-bit */
        R_TILEGX_HW1 = 10,                     /* hword 1 16-bit */
        R_TILEGX_HW2 = 11,                     /* hword 2 16-bit */
        R_TILEGX_HW3 = 12,                     /* hword 3 16-bit */
        R_TILEGX_HW0_LAST = 13,                /* last hword 0 16-bit */
        R_TILEGX_HW1_LAST = 14,                /* last hword 1 16-bit */
        R_TILEGX_HW2_LAST = 15,                /* last hword 2 16-bit */
        R_TILEGX_COPY = 16,                    /* Copy relocation */
        R_TILEGX_GLOB_DAT = 17,                /* Create GOT entry */
        R_TILEGX_JMP_SLOT = 18,                /* Create PLT entry */
        R_TILEGX_RELATIVE = 19,                /* Adjust by program base */
        R_TILEGX_BROFF_X1 = 20,                /* X1 pipe branch offset */
        R_TILEGX_JUMPOFF_X1 = 21,              /* X1 pipe jump offset */
        R_TILEGX_JUMPOFF_X1_PLT = 22,          /* X1 pipe jump offset to PLT */
        R_TILEGX_IMM8_X0 = 23,                 /* X0 pipe 8-bit */
        R_TILEGX_IMM8_Y0 = 24,                 /* Y0 pipe 8-bit */
        R_TILEGX_IMM8_X1 = 25,                 /* X1 pipe 8-bit */
        R_TILEGX_IMM8_Y1 = 26,                 /* Y1 pipe 8-bit */
        R_TILEGX_DEST_IMM8_X1 = 27,            /* X1 pipe destination 8-bit */
        R_TILEGX_MT_IMM14_X1 = 28,             /* X1 pipe mtspr */
        R_TILEGX_MF_IMM14_X1 = 29,             /* X1 pipe mfspr */
        R_TILEGX_MMSTART_X0 = 30,              /* X0 pipe mm "start" */
        R_TILEGX_MMEND_X0 = 31,                /* X0 pipe mm "end" */
        R_TILEGX_SHAMT_X0 = 32,                /* X0 pipe shift amount */
        R_TILEGX_SHAMT_X1 = 33,                /* X1 pipe shift amount */
        R_TILEGX_SHAMT_Y0 = 34,                /* Y0 pipe shift amount */
        R_TILEGX_SHAMT_Y1 = 35,                /* Y1 pipe shift amount */
        R_TILEGX_IMM16_X0_HW0 = 36,            /* X0 pipe hword 0 */
        R_TILEGX_IMM16_X1_HW0 = 37,            /* X1 pipe hword 0 */
        R_TILEGX_IMM16_X0_HW1 = 38,            /* X0 pipe hword 1 */
        R_TILEGX_IMM16_X1_HW1 = 39,            /* X1 pipe hword 1 */
        R_TILEGX_IMM16_X0_HW2 = 40,            /* X0 pipe hword 2 */
        R_TILEGX_IMM16_X1_HW2 = 41,            /* X1 pipe hword 2 */
        R_TILEGX_IMM16_X0_HW3 = 42,            /* X0 pipe hword 3 */
        R_TILEGX_IMM16_X1_HW3 = 43,            /* X1 pipe hword 3 */
        R_TILEGX_IMM16_X0_HW0_LAST = 44,       /* X0 pipe last hword 0 */
        R_TILEGX_IMM16_X1_HW0_LAST = 45,       /* X1 pipe last hword 0 */
        R_TILEGX_IMM16_X0_HW1_LAST = 46,       /* X0 pipe last hword 1 */
        R_TILEGX_IMM16_X1_HW1_LAST = 47,       /* X1 pipe last hword 1 */
        R_TILEGX_IMM16_X0_HW2_LAST = 48,       /* X0 pipe last hword 2 */
        R_TILEGX_IMM16_X1_HW2_LAST = 49,       /* X1 pipe last hword 2 */
        R_TILEGX_IMM16_X0_HW0_PCREL = 50,      /* X0 pipe PC relative hword 0 */
        R_TILEGX_IMM16_X1_HW0_PCREL = 51,      /* X1 pipe PC relative hword 0 */
        R_TILEGX_IMM16_X0_HW1_PCREL = 52,      /* X0 pipe PC relative hword 1 */
        R_TILEGX_IMM16_X1_HW1_PCREL = 53,      /* X1 pipe PC relative hword 1 */
        R_TILEGX_IMM16_X0_HW2_PCREL = 54,      /* X0 pipe PC relative hword 2 */
        R_TILEGX_IMM16_X1_HW2_PCREL = 55,      /* X1 pipe PC relative hword 2 */
        R_TILEGX_IMM16_X0_HW3_PCREL = 56,      /* X0 pipe PC relative hword 3 */
        R_TILEGX_IMM16_X1_HW3_PCREL = 57,      /* X1 pipe PC relative hword 3 */
        R_TILEGX_IMM16_X0_HW0_LAST_PCREL = 58, /* X0 pipe PC-rel last hword 0 */
        R_TILEGX_IMM16_X1_HW0_LAST_PCREL = 59, /* X1 pipe PC-rel last hword 0 */
        R_TILEGX_IMM16_X0_HW1_LAST_PCREL = 60, /* X0 pipe PC-rel last hword 1 */
        R_TILEGX_IMM16_X1_HW1_LAST_PCREL = 61, /* X1 pipe PC-rel last hword 1 */
        R_TILEGX_IMM16_X0_HW2_LAST_PCREL = 62, /* X0 pipe PC-rel last hword 2 */
        R_TILEGX_IMM16_X1_HW2_LAST_PCREL = 63, /* X1 pipe PC-rel last hword 2 */
        R_TILEGX_IMM16_X0_HW0_GOT = 64,        /* X0 pipe hword 0 GOT offset */
        R_TILEGX_IMM16_X1_HW0_GOT = 65,        /* X1 pipe hword 0 GOT offset */
        R_TILEGX_IMM16_X0_HW0_PLT_PCREL = 66,  /* X0 pipe PC-rel PLT hword 0 */
        R_TILEGX_IMM16_X1_HW0_PLT_PCREL = 67,  /* X1 pipe PC-rel PLT hword 0 */
        R_TILEGX_IMM16_X0_HW1_PLT_PCREL = 68,  /* X0 pipe PC-rel PLT hword 1 */
        R_TILEGX_IMM16_X1_HW1_PLT_PCREL = 69,  /* X1 pipe PC-rel PLT hword 1 */
        R_TILEGX_IMM16_X0_HW2_PLT_PCREL = 70,  /* X0 pipe PC-rel PLT hword 2 */
        R_TILEGX_IMM16_X1_HW2_PLT_PCREL = 71,  /* X1 pipe PC-rel PLT hword 2 */
        R_TILEGX_IMM16_X0_HW0_LAST_GOT = 72,   /* X0 pipe last hword 0 GOT offset */
        R_TILEGX_IMM16_X1_HW0_LAST_GOT = 73,   /* X1 pipe last hword 0 GOT offset */
        R_TILEGX_IMM16_X0_HW1_LAST_GOT = 74,   /* X0 pipe last hword 1 GOT offset */
        R_TILEGX_IMM16_X1_HW1_LAST_GOT = 75,   /* X1 pipe last hword 1 GOT offset */
        R_TILEGX_IMM16_X0_HW3_PLT_PCREL = 76,  /* X0 pipe PC-rel PLT hword 3 */
        R_TILEGX_IMM16_X1_HW3_PLT_PCREL = 77,  /* X1 pipe PC-rel PLT hword 3 */
        R_TILEGX_IMM16_X0_HW0_TLS_GD = 78,     /* X0 pipe hword 0 TLS GD offset */
        R_TILEGX_IMM16_X1_HW0_TLS_GD = 79,     /* X1 pipe hword 0 TLS GD offset */
        R_TILEGX_IMM16_X0_HW0_TLS_LE = 80,     /* X0 pipe hword 0 TLS LE offset */
        R_TILEGX_IMM16_X1_HW0_TLS_LE = 81,     /* X1 pipe hword 0 TLS LE offset */
        R_TILEGX_IMM16_X0_HW0_LAST_TLS_LE = 82, /* X0 pipe last hword 0 LE off */
        R_TILEGX_IMM16_X1_HW0_LAST_TLS_LE = 83, /* X1 pipe last hword 0 LE off */
        R_TILEGX_IMM16_X0_HW1_LAST_TLS_LE = 84, /* X0 pipe last hword 1 LE off */
        R_TILEGX_IMM16_X1_HW1_LAST_TLS_LE = 85, /* X1 pipe last hword 1 LE off */
        R_TILEGX_IMM16_X0_HW0_LAST_TLS_GD = 86, /* X0 pipe last hword 0 GD off */
        R_TILEGX_IMM16_X1_HW0_LAST_TLS_GD = 87, /* X1 pipe last hword 0 GD off */
        R_TILEGX_IMM16_X0_HW1_LAST_TLS_GD = 88, /* X0 pipe last hword 1 GD off */
        R_TILEGX_IMM16_X1_HW1_LAST_TLS_GD = 89, /* X1 pipe last hword 1 GD off */
        R_TILEGX_IMM16_X0_HW0_TLS_IE = 92,     /* X0 pipe hword 0 TLS IE offset */
        R_TILEGX_IMM16_X1_HW0_TLS_IE = 93,     /* X1 pipe hword 0 TLS IE offset */
        R_TILEGX_IMM16_X0_HW0_LAST_PLT_PCREL = 94, /* X0 pipe PC-rel PLT last hword 0 */
        R_TILEGX_IMM16_X1_HW0_LAST_PLT_PCREL = 95, /* X1 pipe PC-rel PLT last hword 0 */
        R_TILEGX_IMM16_X0_HW1_LAST_PLT_PCREL = 96, /* X0 pipe PC-rel PLT last hword 1 */
        R_TILEGX_IMM16_X1_HW1_LAST_PLT_PCREL = 97, /* X1 pipe PC-rel PLT last hword 1 */
        R_TILEGX_IMM16_X0_HW2_LAST_PLT_PCREL = 98, /* X0 pipe PC-rel PLT last hword 2 */
        R_TILEGX_IMM16_X1_HW2_LAST_PLT_PCREL = 99, /* X1 pipe PC-rel PLT last hword 2 */
        R_TILEGX_IMM16_X0_HW0_LAST_TLS_IE = 100, /* X0 pipe last hword 0 IE off */
        R_TILEGX_IMM16_X1_HW0_LAST_TLS_IE = 101, /* X1 pipe last hword 0 IE off */
        R_TILEGX_IMM16_X0_HW1_LAST_TLS_IE = 102, /* X0 pipe last hword 1 IE off */
        R_TILEGX_IMM16_X1_HW1_LAST_TLS_IE = 103, /* X1 pipe last hword 1 IE off */
        R_TILEGX_TLS_DTPMOD64 = 106,           /* 64-bit ID of symbol's module */
        R_TILEGX_TLS_DTPOFF64 = 107,           /* 64-bit offset in TLS block */
        R_TILEGX_TLS_TPOFF64 = 108,            /* 64-bit offset in static TLS block */
        R_TILEGX_TLS_DTPMOD32 = 109,           /* 32-bit ID of symbol's module */
        R_TILEGX_TLS_DTPOFF32 = 110,           /* 32-bit offset in TLS block */
        R_TILEGX_TLS_TPOFF32 = 111,            /* 32-bit offset in static TLS block */
        R_TILEGX_TLS_GD_CALL = 112,            /* "jal" for TLS GD */
        R_TILEGX_IMM8_X0_TLS_GD_ADD = 113,     /* X0 pipe "addi" for TLS GD */
        R_TILEGX_IMM8_X1_TLS_GD_ADD = 114,     /* X1 pipe "addi" for TLS GD */
        R_TILEGX_IMM8_Y0_TLS_GD_ADD = 115,     /* Y0 pipe "addi" for TLS GD */
        R_TILEGX_IMM8_Y1_TLS_GD_ADD = 116,     /* Y1 pipe "addi" for TLS GD */
        R_TILEGX_TLS_IE_LOAD = 117,            /* "ld_tls" for TLS IE */
        R_TILEGX_IMM8_X0_TLS_ADD = 118,        /* X0 pipe "addi" for TLS GD/IE */
        R_TILEGX_IMM8_X1_TLS_ADD = 119,        /* X1 pipe "addi" for TLS GD/IE */
        R_TILEGX_IMM8_Y0_TLS_ADD = 120,        /* Y0 pipe "addi" for TLS GD/IE */
        R_TILEGX_IMM8_Y1_TLS_ADD = 121,        /* Y1 pipe "addi" for TLS GD/IE */
        R_TILEGX_GNU_VTINHERIT = 128,          /* GNU C++ vtable hierarchy */
        R_TILEGX_GNU_VTENTRY = 129             /* GNU C++ vtable member usage */
    }
}