using MyTool.Enums;
using System;
using System.Globalization;

namespace MyTool.PEAnalyzer.Resources
{
    /// <summary>
    /// PE资源解析器版本信息语言解析辅助模块
    /// 包含版本信息中语言和代码页相关解析的辅助函数
    /// </summary>
    internal static class PEResourceParserVersionLanguage
    {
        
        // 语言名称数组，按枚举类型索引
        private static readonly string[] englishLanguageNames = [
            "Process Default Language",
            "Arabic (Saudi Arabia)",
            "Bulgarian",
            "Catalan",
            "Chinese (Traditional)",
            "Czech",
            "Danish",
            "German",
            "Greek",
            "English (United States)",
            "Spanish (Traditional Sort)",
            "Finnish",
            "French (Standard)",
            "Hebrew",
            "Hungarian",
            "Icelandic",
            "Italian",
            "Japanese",
            "Korean",
            "Dutch",
            "Norwegian (Bokmal)",
            "Polish",
            "Portuguese (Brazilian)",
            "Romansh",
            "Romanian",
            "Russian",
            "Croatian",
            "Slovak",
            "Albanian",
            "Swedish",
            "Thai",
            "Turkish",
            "Urdu",
            "Indonesian",
            "Ukrainian",
            "Belarusian",
            "Slovenian",
            "Estonian",
            "Latvian",
            "Lithuanian",
            "Tajik",
            "Persian (Farsi)",
            "Vietnamese",
            "Armenian",
            "Azerbaijani (Latin)",
            "Basque",
            "Upper Sorbian",
            "Macedonian",
            "Setswana",
            "Afrikaans",
            "Georgian",
            "Faroese",
            "Hindi",
            "Maltese",
            "Sami (Northern)",
            "Malay",
            "Kazakh",
            "Kyrgyz",
            "Swahili",
            "Turkmen",
            "Uzbek (Latin)",
            "Tatar",
            "Bengali",
            "Punjabi",
            "Gujarati",
            "Odia",
            "Tamil",
            "Telugu",
            "Kannada",
            "Malayalam",
            "Assamese",
            "Marathi",
            "Sanskrit",
            "Mongolian (Cyrillic)",
            "Tibetan",
            "Welsh",
            "Syriac",
            "Sinhala",
            "Nepali",
            "Frisian",
            "Pashto",
            "Filipino",
            "Divehi",
            "Hausa",
            "Yoruba",
            "Quechua (Bolivia)",
            "Sepedi",
            "Bashkir",
            "Luxembourgish",
            "Greenlandic",
            "Igbo",
            "Tigrinya",
            "Hawaiian",
            "Yi",
            "Mapudungun",
            "Mohawk",
            "Breton",
            "Uyghur",
            "Maori",
            "Occitan",
            "Corsican",
            "Alsatian",
            "Sakha",
            "Kinyarwanda",
            "Wolof",
            "Dari",
            "SiSwati",
            "Low German",
            "Yakut",
            "Turkmen (Cyrillic)",
            "Chinese (Simplified)",
            "Arabic (Iraq)",
            "Chinese (Simplified)",
            "German (Switzerland)",
            "English (United Kingdom)",
            "Spanish (Mexico)",
            "French (Belgian)",
            "Italian (Switzerland)",
            "Dutch (Belgium)",
            "Norwegian (Nynorsk)",
            "Portuguese (Standard)",
            "Romanian (Moldova)",
            "Russian (Moldova)",
            "Serbian (Latin)",
            "Swedish (Finland)",
            "Urdu (India)",
            "Lithuanian (Classic)",
            "Azerbaijani (Cyrillic)",
            "Lower Sorbian",
            "Sami (Northern, Finland)",
            "Malay (Brunei Darussalam)",
            "Uzbek (Cyrillic)",
            "Bengali (India)",
            "Punjabi (India)",
            "Tamil (India)",
            "Mongolian (Traditional)",
            "Tibetan (PRC)",
            "Inuktitut (Latin)",
            "Kashmiri (Devanagari)",
            "Nepali (India)",
            "Quechua (Ecuador)",
            "Tigrinya (Eritrea)",
            "Chinese (Hong Kong S.A.R.)",
            "English (Australia)",
            "Spanish (Modern Sort)",
            "French (Canada)",
            "Serbian (Cyrillic)",
            "Quechua (Peru)",
            "Chinese (Singapore)",
            "English (Canada)",
            "Spanish (Guatemala)",
            "French (Switzerland)",
            "Croatian (Latin)",
            "Quechua (Bolivia)",
            "Arabic (Libya)",
            "Chinese (Macao S.A.R.)",
            "English (New Zealand)",
            "Spanish (Costa Rica)",
            "French (Luxembourg)",
            "Bosnian (Latin)",
            "Arabic (Algeria)",
            "English (Ireland)",
            "Spanish (Panama)",
            "French (Monaco)",
            "Arabic (Morocco)",
            "English (South Africa)",
            "Spanish (Dominican Republic)",
            "French (West Indies)",
            "Arabic (Tunisia)",
            "English (Jamaica)",
            "Spanish (Venezuela)",
            "French (Congo)",
            "Arabic (Oman)",
            "English (Caribbean)",
            "Spanish (Colombia)",
            "French (Senegal)",
            "Arabic (Yemen)",
            "English (Belize)",
            "Spanish (Peru)",
            "French (Mali)",
            "Arabic (Jordan)",
            "English (Trinidad)",
            "Spanish (Argentina)",
            "French (Côte d'Ivoire)",
            "Arabic (Lebanon)",
            "English (Zimbabwe)",
            "Spanish (Ecuador)",
            "French (Burkina Faso)",
            "Arabic (Kuwait)",
            "English (Philippines)",
            "Spanish (Chile)",
            "French (Benin)",
            "Arabic (U.A.E.)",
            "Spanish (Uruguay)",
            "French (Niger)",
            "Arabic (Bahrain)",
            "English (Indonesia)",
            "Spanish (Paraguay)",
            "French (Togo)",
            "Arabic (Qatar)",
            "English (Malaysia)",
            "Spanish (El Salvador)",
            "French (Chad)",
            "Arabic (Syria)",
            "English (Singapore)",
            "Spanish (Honduras)",
            "French (Central African Republic)",
            "English (U.A.E.)",
            "Spanish (Nicaragua)",
            "French (Congo [DRC])",
            "Spanish (Puerto Rico)",
            "French (Cameroon)",
            "Spanish (United States)",
            "French (Congo [Republic])",
            "Spanish (Latin America)",
            "French (Réunion)",
            "Spanish (Cuba)",
            "French (Mayotte)",
            "English (India)",
            "Spanish (Dominican Republic)",
            "French (Maghreb)",
            "English (Malaysia)",
            "Spanish (Bolivia)",
            "English (Singapore)",
            "Spanish (Paraguay)",
            "French (Equatorial Guinea)",
            "Spanish (Peru)",
            "French (Switzerland)",
            "Spanish (Uruguay)",
            "French (Rwanda)",
            "Spanish (Venezuela)",
            "French (North Africa)",
            "Unknown Language (0x{0:X4})"
        ];
        
        private static readonly string[] simplifiedChineseLanguageNames = [
            "进程默认语言",
            "阿拉伯语（沙特阿拉伯）",
            "保加利亚语",
            "加泰罗尼亚语",
            "中文（繁体）",
            "捷克语",
            "丹麦语",
            "德语",
            "希腊语",
            "英语（美国）",
            "西班牙语（传统排序）",
            "芬兰语",
            "法语（标准）",
            "希伯来语",
            "匈牙利语",
            "冰岛语",
            "意大利语",
            "日语",
            "韩语",
            "荷兰语",
            "挪威语（博克马尔）",
            "波兰语",
            "葡萄牙语（巴西）",
            "罗曼什语",
            "罗马尼亚语",
            "俄语",
            "克罗地亚语",
            "斯洛伐克语",
            "阿尔巴尼亚语",
            "瑞典语",
            "泰语",
            "土耳其语",
            "乌尔都语",
            "印度尼西亚语",
            "乌克兰语",
            "白俄罗斯语",
            "斯洛文尼亚语",
            "爱沙尼亚语",
            "拉脱维亚语",
            "立陶宛语",
            "塔吉克语",
            "波斯语（法尔斯语）",
            "越南语",
            "亚美尼亚语",
            "阿塞拜疆语（拉丁文）",
            "巴斯克语",
            "上索布语",
            "马其顿语",
            "茨瓦纳语",
            "南非荷兰语",
            "格鲁吉亚语",
            "法罗语",
            "印地语",
            "马耳他语",
            "萨米语（北部）",
            "马来语",
            "哈萨克语",
            "吉尔吉斯语",
            "斯瓦希里语",
            "土库曼语",
            "乌兹别克语（拉丁文）",
            "鞑靼语",
            "孟加拉语",
            "旁遮普语",
            "古吉拉特语",
            "奥里雅语",
            "泰米尔语",
            "泰卢固语",
            "卡纳达语",
            "马拉雅拉姆语",
            "阿萨姆语",
            "马拉地语",
            "梵语",
            "蒙古语（西里尔文）",
            "藏语",
            "威尔士语",
            "叙利亚语",
            "僧伽罗语",
            "尼泊尔语",
            "弗里西亚语",
            "普什图语",
            "菲律宾语",
            "迪维希语",
            "豪萨语",
            "约鲁巴语",
            "克丘亚语（玻利维亚）",
            "北索托语",
            "巴什基尔语",
            "卢森堡语",
            "格陵兰语",
            "伊博语",
            "提格利尼亚语",
            "夏威夷语",
            "彝语",
            "马普切语",
            "莫霍克语",
            "布列塔尼语",
            "维吾尔语",
            "毛利语",
            "奥克西坦语",
            "科西嘉语",
            "阿尔萨斯语",
            "雅库特语",
            "卢旺达语",
            "沃洛夫语",
            "达里语",
            "斯瓦蒂语",
            "低地德语",
            "雅库特语",
            "土库曼语（西里尔文）",
            "中文（简体）",
            "阿拉伯语（伊拉克）",
            "中文（简体）",
            "德语（瑞士）",
            "英语（英国）",
            "西班牙语（墨西哥）",
            "法语（比利时）",
            "意大利语（瑞士）",
            "荷兰语（比利时）",
            "挪威语（尼诺斯克）",
            "葡萄牙语（标准）",
            "罗马尼亚语（摩尔多瓦）",
            "俄语（摩尔多瓦）",
            "塞尔维亚语（拉丁文）",
            "瑞典语（芬兰）",
            "乌尔都语（印度）",
            "立陶宛语（经典）",
            "阿塞拜疆语（西里尔文）",
            "下索布语",
            "萨米语（北部，芬兰）",
            "马来语（文莱达鲁萨兰国）",
            "乌兹别克语（西里尔文）",
            "孟加拉语（印度）",
            "旁遮普语（印度）",
            "泰米尔语（印度）",
            "蒙古语（传统）",
            "藏语（中国）",
            "因纽特语（拉丁文）",
            "克什米尔语（天城文）",
            "尼泊尔语（印度）",
            "克丘亚语（厄瓜多尔）",
            "提格利尼亚语（厄立特里亚）",
            "中文（香港特别行政区）",
            "英语（澳大利亚）",
            "西班牙语（现代排序）",
            "法语（加拿大）",
            "塞尔维亚语（西里尔文）",
            "克丘亚语（秘鲁）",
            "中文（新加坡）",
            "英语（加拿大）",
            "西班牙语（危地马拉）",
            "法语（瑞士）",
            "克罗地亚语（拉丁文）",
            "克丘亚语（玻利维亚）",
            "阿拉伯语（利比亚）",
            "中文（澳门特别行政区）",
            "英语（新西兰）",
            "西班牙语（哥斯达黎加）",
            "法语（卢森堡）",
            "波斯尼亚语（拉丁文）",
            "阿拉伯语（阿尔及利亚）",
            "英语（爱尔兰）",
            "西班牙语（巴拿马）",
            "法语（摩纳哥）",
            "阿拉伯语（摩洛哥）",
            "英语（南非）",
            "西班牙语（多米尼加共和国）",
            "法语（加蓬）",
            "阿拉伯语（突尼斯）",
            "英语（牙买加）",
            "西班牙语（委内瑞拉）",
            "法语（刚果）",
            "阿拉伯语（阿曼）",
            "英语（加勒比海地区）",
            "西班牙语（哥伦比亚）",
            "法语（塞内加尔）",
            "阿拉伯语（也门）",
            "英语（伯利兹）",
            "西班牙语（秘鲁）",
            "法语（马里）",
            "阿拉伯语（约旦）",
            "英语（特立尼达和多巴哥）",
            "西班牙语（阿根廷）",
            "法语（科特迪瓦）",
            "阿拉伯语（黎巴嫩）",
            "英语（津巴布韦）",
            "西班牙语（厄瓜多尔）",
            "法语（布基纳法索）",
            "阿拉伯语（科威特）",
            "英语（菲律宾）",
            "西班牙语（智利）",
            "法语（贝宁）",
            "阿拉伯语（阿联酋）",
            "西班牙语（乌拉圭）",
            "法语（尼日尔）",
            "阿拉伯语（巴林）",
            "英语（印度尼西亚）",
            "西班牙语（巴拉圭）",
            "法语（多哥）",
            "阿拉伯语（卡塔尔）",
            "英语（马来西亚）",
            "西班牙语（萨尔瓦多）",
            "法语（乍得）",
            "阿拉伯语（叙利亚）",
            "英语（新加坡）",
            "西班牙语（洪都拉斯）",
            "法语（中非共和国）",
            "英语（阿拉伯联合酋长国）",
            "西班牙语（尼加拉瓜）",
            "法语（刚果共和国）",
            "西班牙语（波多黎各）",
            "法语（喀麦隆）",
            "西班牙语（美国）",
            "法语（刚果民主共和国）",
            "西班牙语（拉丁美洲）",
            "法语（留尼汪）",
            "西班牙语（古巴）",
            "法语（马约特）",
            "英语（印度）",
            "西班牙语（多米尼加共和国）",
            "法语（马格里布）",
            "英语（马来西亚）",
            "西班牙语（玻利维亚）",
            "英语（新加坡）",
            "西班牙语（巴拉圭）",
            "法语（赤道几内亚）",
            "西班牙语（秘鲁）",
            "法语（瑞士）",
            "西班牙语（乌拉圭）",
            "法语（卢旺达）",
            "西班牙语（委内瑞拉）",
            "法语（北非）",
            "未知语言 (0x{0:X4})"
        ];
        
        private static readonly string[] traditionalChineseLanguageNames = [
            "進程默認語言",
            "阿拉伯語（沙特阿拉伯）",
            "保加利亞語",
            "加泰羅尼亞語",
            "中文（繁體）",
            "捷克語",
            "丹麥語",
            "德語",
            "希臘語",
            "英語（美國）",
            "西班牙語（傳統排序）",
            "芬蘭語",
            "法語（標準）",
            "希伯來語",
            "匈牙利語",
            "冰島語",
            "意大利語",
            "日語",
            "韓語",
            "荷蘭語",
            "挪威語（博克馬爾）",
            "波蘭語",
            "葡萄牙語（巴西）",
            "羅曼什語",
            "羅馬尼亞語",
            "俄語",
            "克羅地亞語",
            "斯洛伐克語",
            "阿爾巴尼亞語",
            "瑞典語",
            "泰語",
            "土耳其語",
            "烏爾都語",
            "印度尼西亞語",
            "烏克蘭語",
            "白俄羅斯語",
            "斯洛文尼亞語",
            "愛沙尼亞語",
            "拉脫維亞語",
            "立陶宛語",
            "塔吉克語",
            "波斯語（法爾斯語）",
            "越南語",
            "亞美尼亞語",
            "阿塞拜疆語（拉丁文）",
            "巴斯克語",
            "上索布語",
            "馬其頓語",
            "茨瓦納語",
            "南非荷蘭語",
            "格魯吉亞語",
            "法羅語",
            "印地語",
            "馬耳他語",
            "薩米語（北部）",
            "馬來語",
            "哈薩克語",
            "吉爾吉斯語",
            "斯瓦希里語",
            "土庫曼語",
            "烏茲別克語（拉丁文）",
            "韃靼語",
            "孟加拉語",
            "旁遮普語",
            "古吉拉特語",
            "奧里雅語",
            "泰米爾語",
            "泰盧固語",
            "卡納達語",
            "馬拉雅拉姆語",
            "阿薩姆語",
            "馬拉地語",
            "梵語",
            "蒙古語（西里爾文）",
            "藏語",
            "威爾士語",
            "敘利亞語",
            "僧伽羅語",
            "尼泊爾語",
            "弗裡西亞語",
            "普什圖語",
            "菲律賓語",
            "迪維希語",
            "豪薩語",
            "約魯巴語",
            "克丘亞語（玻利維亞）",
            "北索托語",
            "巴什基爾語",
            "盧森堡語",
            "格陵蘭語",
            "伊博語",
            "提格利尼亞語",
            "夏威夷語",
            "彝語",
            "馬普切語",
            "莫霍克語",
            "布列塔尼語",
            "維吾爾語",
            "毛利語",
            "奧克西坦語",
            "科西嘉語",
            "阿爾薩斯語",
            "雅庫特語",
            "盧旺達語",
            "沃洛夫語",
            "達里語",
            "斯瓦蒂語",
            "低地德語",
            "雅庫特語",
            "土庫曼語（西里爾文）",
            "中文（簡體）",
            "阿拉伯語（伊拉克）",
            "中文（簡體）",
            "德語（瑞士）",
            "英語（英國）",
            "西班牙語（墨西哥）",
            "法語（比利時）",
            "意大利語（瑞士）",
            "荷蘭語（比利時）",
            "挪威語（尼諾斯克）",
            "葡萄牙語（標準）",
            "羅馬尼亞語（摩爾多瓦）",
            "俄語（摩爾多瓦）",
            "塞爾維亞語（拉丁文）",
            "瑞典語（芬蘭）",
            "烏爾都語（印度）",
            "立陶宛語（經典）",
            "阿塞拜疆語（西里爾文）",
            "下索布語",
            "薩米語（北部，芬蘭）",
            "馬來語（汶萊達魯薩蘭國）",
            "烏茲別克語（西里爾文）",
            "孟加拉語（印度）",
            "旁遮普語（印度）",
            "泰米爾語（印度）",
            "蒙古語（傳統）",
            "藏語（中國）",
            "因紐特語（拉丁文）",
            "克什米爾語（天城文）",
            "尼泊爾語（印度）",
            "克丘亞語（厄瓜多爾）",
            "提格利尼亞語（厄立特裡亞）",
            "中文（香港特別行政區）",
            "英語（澳大利亞）",
            "西班牙語（現代排序）",
            "法語（加拿大）",
            "塞爾維亞語（西里爾文）",
            "克丘亞語（秘魯）",
            "中文（新加坡）",
            "英語（加拿大）",
            "西班牙語（危地馬拉）",
            "法語（瑞士）",
            "克羅地亞語（拉丁文）",
            "克丘亞語（玻利維亞）",
            "阿拉伯語（利比亞）",
            "中文（澳門特別行政區）",
            "英語（新西蘭）",
            "西班牙語（哥斯達黎加）",
            "法語（盧森堡）",
            "波斯尼亞語（拉丁文）",
            "阿拉伯語（阿爾及利亞）",
            "英語（愛爾蘭）",
            "西班牙語（巴拿馬）",
            "法語（摩納哥）",
            "阿拉伯語（摩洛哥）",
            "英語（南非）",
            "西班牙語（多米尼加共和國）",
            "法語（加蓬）",
            "阿拉伯語（突尼斯）",
            "英語（牙買加）",
            "西班牙語（委內瑞拉）",
            "法語（剛果）",
            "阿拉伯語（阿曼）",
            "英語（加勒比海地區）",
            "西班牙語（哥倫比亞）",
            "法語（塞內加爾）",
            "阿拉伯語（也門）",
            "英語（伯利茲）",
            "西班牙語（秘魯）",
            "法語（馬里）",
            "阿拉伯語（約旦）",
            "英語（特立尼達和多巴哥）",
            "西班牙語（阿根廷）",
            "法語（科特迪瓦）",
            "阿拉伯語（黎巴嫩）",
            "英語（津巴布韋）",
            "西班牙語（厄瓜多爾）",
            "法語（布基納法索）",
            "阿拉伯語（科威特）",
            "英語（菲律賓）",
            "西班牙語（智利）",
            "法語（貝寧）",
            "阿拉伯語（阿聯酋）",
            "西班牙語（烏拉圭）",
            "法語（尼日爾）",
            "阿拉伯語（巴林）",
            "英語（印度尼西亞）",
            "西班牙語（巴拉圭）",
            "法語（多哥）",
            "阿拉伯語（卡塔爾）",
            "英語（馬來西亞）",
            "西班牙語（薩爾瓦多）",
            "法語（乍得）",
            "阿拉伯語（敘利亞）",
            "英語（新加坡）",
            "西班牙語（洪都拉斯）",
            "法語（中非共和國）",
            "英語（阿拉伯聯合酋長國）",
            "西班牙語（尼加拉瓜）",
            "法語（剛果共和國）",
            "西班牙語（波多黎各）",
            "法語（喀麥隆）",
            "西班牙語（美國）",
            "法語（剛果民主共和國）",
            "西班牙語（拉丁美洲）",
            "法語（留尼汪）",
            "西班牙語（古巴）",
            "法語（馬約特）",
            "英語（印度）",
            "西班牙語（多米尼加共和國）",
            "法語（馬格里布）",
            "英語（馬來西亞）",
            "西班牙語（玻利維亞）",
            "英語（新加坡）",
            "西班牙語（巴拉圭）",
            "法語（赤道幾內亞）",
            "西班牙語（秘魯）",
            "法語（瑞士）",
            "西班牙語（烏拉圭）",
            "法語（盧旺達）",
            "西班牙語（委內瑞拉）",
            "法語（北非）",
            "未知語言 (0x{0:X4})"
        ];
        
        // 代码页名称数组，按枚举类型索引
        private static readonly string[] englishCodePageNames = [
            "Default Code Page",
            "IBM EBCDIC US-Canada",
            "OEM United States",
            "IBM EBCDIC International",
            "Arabic (ASMO 708)",
            "Arabic (DOS)",
            "Greek (DOS)",
            "Baltic (DOS)",
            "Western European (DOS)",
            "Central European (DOS)",
            "OEM Cyrillic",
            "Turkish (DOS)",
            "OEM Multilingual Latin I",
            "Portuguese (DOS)",
            "Icelandic (DOS)",
            "Hebrew (DOS)",
            "French Canadian (DOS)",
            "Arabic (864)",
            "Nordic (DOS)",
            "Cyrillic (DOS)",
            "Greek, Modern (DOS)",
            "Thai (Windows)",
            "Japanese (Shift-JIS)",
            "Chinese Simplified (GB2312)",
            "Korean",
            "Chinese Traditional (Big5)",
            "UTF-16 (Little endian)",
            "UTF-16 (Big endian)",
            "Central European (Windows)",
            "Cyrillic (Windows)",
            "Western European (Windows)",
            "Greek (Windows)",
            "Turkish (Windows)",
            "Hebrew (Windows)",
            "Arabic (Windows)",
            "Baltic (Windows)",
            "Vietnamese (Windows)",
            "Western European (Mac)",
            "Japanese (Mac)",
            "Chinese Traditional (Mac)",
            "Korean (Mac)",
            "Arabic (Mac)",
            "Hebrew (Mac)",
            "Greek (Mac)",
            "Cyrillic (Mac)",
            "Chinese Simplified (Mac)",
            "Thai (Mac)",
            "Central European (Mac)",
            "Icelandic (Mac)",
            "Turkish (Mac)",
            "Croatian (Mac)",
            "UTF-32 (Little endian)",
            "UTF-32 (Big endian)",
            "Chinese Simplified (GB2312-80)",
            "ISO 8859-1 Latin 1",
            "ISO 8859-2 Central European",
            "ISO 8859-3 Latin 3",
            "ISO 8859-4 Baltic",
            "ISO 8859-5 Cyrillic",
            "ISO 8859-6 Arabic",
            "ISO 8859-7 Greek",
            "ISO 8859-8 Hebrew",
            "ISO 8859-9 Turkish",
            "ISO 8859-13 Estonian",
            "ISO 8859-15 Latin 9",
            "EUC Simplified Chinese",
            "EUC Korean",
            "HZ-GB2312 Simplified Chinese",
            "GB18030 Simplified Chinese (4 byte)",
            "UTF-7",
            "UTF-8",
            "Unknown Code Page ({0})"
        ];
        
        private static readonly string[] simplifiedChineseCodePageNames = [
            "默认代码页",
            "IBM EBCDIC 美国/加拿大",
            "OEM 美国",
            "IBM EBCDIC 国际",
            "阿拉伯语 (ASMO 708)",
            "阿拉伯语 (DOS)",
            "希腊语 (DOS)",
            "波罗的海语 (DOS)",
            "西欧 (DOS)",
            "中欧 (DOS)",
            "OEM 西里尔文",
            "土耳其语 (DOS)",
            "OEM 多语言拉丁语 I",
            "葡萄牙语 (DOS)",
            "冰岛语 (DOS)",
            "希伯来语 (DOS)",
            "法语加拿大 (DOS)",
            "阿拉伯语 (864)",
            "北欧 (DOS)",
            "西里尔文 (DOS)",
            "希腊语，现代 (DOS)",
            "泰语 (Windows)",
            "日语 (Shift-JIS)",
            "中文简体 (GB2312)",
            "韩语",
            "中文繁体 (Big5)",
            "UTF-16 (小端序)",
            "UTF-16 (大端序)",
            "中欧 (Windows)",
            "西里尔文 (Windows)",
            "西欧 (Windows)",
            "希腊语 (Windows)",
            "土耳其语 (Windows)",
            "希伯来语 (Windows)",
            "阿拉伯语 (Windows)",
            "波罗的海语 (Windows)",
            "越南语 (Windows)",
            "西欧 (Mac)",
            "日语 (Mac)",
            "中文繁体 (Mac)",
            "韩语 (Mac)",
            "阿拉伯语 (Mac)",
            "希伯来语 (Mac)",
            "希腊语 (Mac)",
            "西里尔文 (Mac)",
            "中文简体 (Mac)",
            "泰语 (Mac)",
            "中欧 (Mac)",
            "冰岛语 (Mac)",
            "土耳其语 (Mac)",
            "克罗地亚语 (Mac)",
            "UTF-32 (小端序)",
            "UTF-32 (大端序)",
            "中文简体 (GB2312-80)",
            "ISO 8859-1 拉丁语 1",
            "ISO 8859-2 中欧",
            "ISO 8859-3 拉丁语 3",
            "ISO 8859-4 波罗的海语",
            "ISO 8859-5 西里尔文",
            "ISO 8859-6 阿拉伯语",
            "ISO 8859-7 希腊语",
            "ISO 8859-8 希伯来语",
            "ISO 8859-9 土耳其语",
            "ISO 8859-13 爱沙尼亚语",
            "ISO 8859-15 拉丁语 9",
            "EUC 中文简体",
            "EUC 韩语",
            "HZ-GB2312 中文简体",
            "GB18030 中文简体 (4 字节)",
            "UTF-7",
            "UTF-8",
            "未知代码页 ({0})"
        ];
        
        private static readonly string[] traditionalChineseCodePageNames = [
            "默認代碼頁",
            "IBM EBCDIC 美國/加拿大",
            "OEM 美國",
            "IBM EBCDIC 國際",
            "阿拉伯語 (ASMO 708)",
            "阿拉伯語 (DOS)",
            "希臘語 (DOS)",
            "波羅的海語 (DOS)",
            "西歐 (DOS)",
            "中歐 (DOS)",
            "OEM 西里爾文",
            "土耳其語 (DOS)",
            "OEM 多語言拉丁語 I",
            "葡萄牙語 (DOS)",
            "冰島語 (DOS)",
            "希伯來語 (DOS)",
            "法語加拿大 (DOS)",
            "阿拉伯語 (864)",
            "北歐 (DOS)",
            "西里爾文 (DOS)",
            "希臘語，現代 (DOS)",
            "泰語 (Windows)",
            "日語 (Shift-JIS)",
            "中文簡體 (GB2312)",
            "韓語",
            "中文繁體 (Big5)",
            "UTF-16 (小端序)",
            "UTF-16 (大端序)",
            "中歐 (Windows)",
            "西里爾文 (Windows)",
            "西歐 (Windows)",
            "希臘語 (Windows)",
            "土耳其語 (Windows)",
            "希伯來語 (Windows)",
            "阿拉伯語 (Windows)",
            "波羅的海語 (Windows)",
            "越南語 (Windows)",
            "西歐 (Mac)",
            "日語 (Mac)",
            "中文繁體 (Mac)",
            "韓語 (Mac)",
            "阿拉伯語 (Mac)",
            "希伯來語 (Mac)",
            "希臘語 (Mac)",
            "西里爾文 (Mac)",
            "中文簡體 (Mac)",
            "泰語 (Mac)",
            "中歐 (Mac)",
            "冰島語 (Mac)",
            "土耳其語 (Mac)",
            "克羅地亞語 (Mac)",
            "UTF-32 (小端序)",
            "UTF-32 (大端序)",
            "中文簡體 (GB2312-80)",
            "ISO 8859-1 拉丁語 1",
            "ISO 8859-2 中歐",
            "ISO 8859-3 拉丁語 3",
            "ISO 8859-4 波羅的海語",
            "ISO 8859-5 西里爾文",
            "ISO 8859-6 阿拉伯語",
            "ISO 8859-7 希臘語",
            "ISO 8859-8 希伯來語",
            "ISO 8859-9 土耳其語",
            "ISO 8859-13 愛沙尼亞語",
            "ISO 8859-15 拉丁語 9",
            "EUC 中文簡體",
            "EUC 韓語",
            "HZ-GB2312 中文簡體",
            "GB18030 中文簡體 (4 字節)",
            "UTF-7",
            "UTF-8",
            "未知代碼頁 ({0})"
        ];

        /// <summary>
        /// 将语言ID和代码页转换为可读的文本信息
        /// </summary>
        /// <param name="languageId">语言ID</param>
        /// <param name="codePage">代码页</param>
        /// <returns>可读的翻译信息</returns>
        internal static string GetReadableTranslationInfo(uint languageId, uint codePage)
        {
            // 获取语言名称
            string languageName = GetLanguageName(languageId);
            
            // 获取代码页名称
            string codePageName = GetCodePageName(codePage);
            
            // 返回格式化的字符串
            return $"{languageName} (0x{languageId:X4}), {codePageName} ({codePage})";
        }

        /// <summary>
        /// 根据语言ID获取语言名称
        /// </summary>
        /// <param name="languageId">语言ID</param>
        /// <returns>语言名称</returns>
        private static string GetLanguageName(uint languageId)
        {
            // 根据当前语言类型选择对应的语言名称数组
            string[] languageNames = GlobalState.CurrentLanguageType switch
            {
                LanguageType.SimplifiedChinese => simplifiedChineseLanguageNames,
                LanguageType.TraditionalChinese => traditionalChineseLanguageNames,
                _ => englishLanguageNames
            };

            // 常见的语言ID映射
            return languageId switch
            {
                0x0400 => languageNames[0],
                0x0401 => languageNames[1],
                0x0402 => languageNames[2],
                0x0403 => languageNames[3],
                0x0404 => languageNames[4],
                0x0405 => languageNames[5],
                0x0406 => languageNames[6],
                0x0407 => languageNames[7],
                0x0408 => languageNames[8],
                0x0409 => languageNames[9],
                0x040A => languageNames[10],
                0x040B => languageNames[11],
                0x040C => languageNames[12],
                0x040D => languageNames[13],
                0x040E => languageNames[14],
                0x040F => languageNames[15],
                0x0410 => languageNames[16],
                0x0411 => languageNames[17],
                0x0412 => languageNames[18],
                0x0413 => languageNames[19],
                0x0414 => languageNames[20],
                0x0415 => languageNames[21],
                0x0416 => languageNames[22],
                0x0417 => languageNames[23],
                0x0418 => languageNames[24],
                0x0419 => languageNames[25],
                0x041A => languageNames[26],
                0x041B => languageNames[27],
                0x041C => languageNames[28],
                0x041D => languageNames[29],
                0x041E => languageNames[30],
                0x041F => languageNames[31],
                0x0420 => languageNames[32],
                0x0421 => languageNames[33],
                0x0422 => languageNames[34],
                0x0423 => languageNames[35],
                0x0424 => languageNames[36],
                0x0425 => languageNames[37],
                0x0426 => languageNames[38],
                0x0427 => languageNames[39],
                0x0428 => languageNames[40],
                0x0429 => languageNames[41],
                0x042A => languageNames[42],
                0x042B => languageNames[43],
                0x042C => languageNames[44],
                0x042D => languageNames[45],
                0x042E => languageNames[46],
                0x042F => languageNames[47],
                0x0432 => languageNames[48],
                0x0436 => languageNames[49],
                0x0437 => languageNames[50],
                0x0438 => languageNames[51],
                0x0439 => languageNames[52],
                0x043A => languageNames[53],
                0x043B => languageNames[54],
                0x043E => languageNames[55],
                0x043F => languageNames[56],
                0x0440 => languageNames[57],
                0x0441 => languageNames[58],
                0x0442 => languageNames[59],
                0x0443 => languageNames[60],
                0x0444 => languageNames[61],
                0x0445 => languageNames[62],
                0x0446 => languageNames[63],
                0x0447 => languageNames[64],
                0x0448 => languageNames[65],
                0x0449 => languageNames[66],
                0x044A => languageNames[67],
                0x044B => languageNames[68],
                0x044C => languageNames[69],
                0x044D => languageNames[70],
                0x044E => languageNames[71],
                0x044F => languageNames[72],
                0x0450 => languageNames[73],
                0x0451 => languageNames[74],
                0x0452 => languageNames[75],
                0x045A => languageNames[76],
                0x045B => languageNames[77],
                0x0461 => languageNames[78],
                0x0462 => languageNames[79],
                0x0463 => languageNames[80],
                0x0464 => languageNames[81],
                0x0465 => languageNames[82],
                0x0468 => languageNames[83],
                0x046A => languageNames[84],
                0x046B => languageNames[85],
                0x046C => languageNames[86],
                0x046D => languageNames[87],
                0x046E => languageNames[88],
                0x046F => languageNames[89],
                0x0470 => languageNames[90],
                0x0473 => languageNames[91],
                0x0475 => languageNames[92],
                0x0478 => languageNames[93],
                0x047A => languageNames[94],
                0x047C => languageNames[95],
                0x047E => languageNames[96],
                0x0480 => languageNames[97],
                0x0481 => languageNames[98],
                0x0482 => languageNames[99],
                0x0483 => languageNames[100],
                0x0484 => languageNames[101],
                0x0485 => languageNames[102],
                0x0486 => languageNames[103],
                0x0487 => languageNames[104],
                0x0488 => languageNames[105],
                0x048C => languageNames[106],
                0x048F => languageNames[107],
                0x0491 => languageNames[108],
                0x0493 => languageNames[109],
                0x0800 => languageNames[110],
                0x0801 => languageNames[111],
                0x0804 => languageNames[112],
                0x0807 => languageNames[113],
                0x0809 => languageNames[114],
                0x080A => languageNames[115],
                0x080C => languageNames[116],
                0x0810 => languageNames[117],
                0x0813 => languageNames[118],
                0x0814 => languageNames[119],
                0x0816 => languageNames[120],
                0x0818 => languageNames[121],
                0x0819 => languageNames[122],
                0x081A => languageNames[123],
                0x081D => languageNames[124],
                0x0820 => languageNames[125],
                0x0827 => languageNames[126],
                0x082C => languageNames[127],
                0x082E => languageNames[128],
                0x083B => languageNames[129],
                0x083E => languageNames[130],
                0x0843 => languageNames[131],
                0x0845 => languageNames[132],
                0x0846 => languageNames[133],
                0x0849 => languageNames[134],
                0x0850 => languageNames[135],
                0x0851 => languageNames[136],
                0x085D => languageNames[137],
                0x0860 => languageNames[138],
                0x0861 => languageNames[139],
                0x086B => languageNames[140],
                0x0873 => languageNames[141],
                0x0C04 => languageNames[142],
                0x0C09 => languageNames[143],
                0x0C0A => languageNames[144],
                0x0C0C => languageNames[145],
                0x0C1A => languageNames[146],
                0x0C6B => languageNames[147],
                0x1004 => languageNames[148],
                0x1009 => languageNames[149],
                0x100A => languageNames[150],
                0x100C => languageNames[151],
                0x101A => languageNames[152],
                0x106B => languageNames[153],
                0x1401 => languageNames[154],
                0x1404 => languageNames[155],
                0x1409 => languageNames[156],
                0x140A => languageNames[157],
                0x140C => languageNames[158],
                0x141A => languageNames[159],
                0x1801 => languageNames[160],
                0x1809 => languageNames[161],
                0x180A => languageNames[162],
                0x180C => languageNames[163],
                0x1C01 => languageNames[164],
                0x1C09 => languageNames[165],
                0x1C0A => languageNames[166],
                0x1C0C => languageNames[167],
                0x2001 => languageNames[168],
                0x2009 => languageNames[169],
                0x200A => languageNames[170],
                0x200C => languageNames[171],
                0x2401 => languageNames[172],
                0x2409 => languageNames[173],
                0x240A => languageNames[174],
                0x240C => languageNames[175],
                0x2801 => languageNames[176],
                0x2809 => languageNames[177],
                0x280A => languageNames[178],
                0x280C => languageNames[179],
                0x2C01 => languageNames[180],
                0x2C09 => languageNames[181],
                0x2C0A => languageNames[182],
                0x2C0C => languageNames[183],
                0x3001 => languageNames[184],
                0x3009 => languageNames[185],
                0x300A => languageNames[186],
                0x300C => languageNames[187],
                0x3401 => languageNames[188],
                0x3409 => languageNames[189],
                0x340A => languageNames[190],
                0x340C => languageNames[191],
                0x3801 => languageNames[192],
                0x380A => languageNames[193],
                0x380C => languageNames[194],
                0x3C01 => languageNames[195],
                0x3C09 => languageNames[196],
                0x3C0A => languageNames[197],
                0x3C0C => languageNames[198],
                0x4001 => languageNames[199],
                0x4009 => languageNames[200],
                0x400A => languageNames[201],
                0x400C => languageNames[202],
                0x4401 => languageNames[203],
                0x4409 => languageNames[204],
                0x440A => languageNames[205],
                0x440C => languageNames[206],
                0x4809 => languageNames[207],
                0x480A => languageNames[208],
                0x480C => languageNames[209],
                0x4C0A => languageNames[210],
                0x4C0C => languageNames[211],
                0x500A => languageNames[212],
                0x500C => languageNames[213],
                0x540A => languageNames[214],
                0x540C => languageNames[215],
                0x580A => languageNames[216],
                0x580C => languageNames[217],
                0x6009 => languageNames[218],
                0x640A => languageNames[219],
                0x640C => languageNames[220],
                0x6809 => languageNames[221],
                0x6C0A => languageNames[222],
                0x7009 => languageNames[223],
                0x700A => languageNames[224],
                0x700C => languageNames[225],
                0x740A => languageNames[226],
                0x740C => languageNames[227],
                0x780A => languageNames[228],
                0x780C => languageNames[229],
                0x7C0A => languageNames[230],
                0x7C0C => languageNames[231],
                _ => string.Format(languageNames[232], languageId)
            };
        }

        /// <summary>
        /// 根据代码页获取代码页名称
        /// </summary>
        /// <param name="codePage">代码页</param>
        /// <returns>代码页名称</returns>
        private static string GetCodePageName(uint codePage)
        {
            // 根据当前语言类型选择对应的代码页名称数组
            string[] codePageNames = GlobalState.CurrentLanguageType switch
            {
                LanguageType.SimplifiedChinese => simplifiedChineseCodePageNames,
                LanguageType.TraditionalChinese => traditionalChineseCodePageNames,
                _ => englishCodePageNames
            };

            // 常见的代码页映射
            return codePage switch
            {
                0 => codePageNames[0],
                37 => codePageNames[1],
                437 => codePageNames[2],
                500 => codePageNames[3],
                708 => codePageNames[4],
                720 => codePageNames[5],
                737 => codePageNames[6],
                775 => codePageNames[7],
                850 => codePageNames[8],
                852 => codePageNames[9],
                855 => codePageNames[10],
                857 => codePageNames[11],
                858 => codePageNames[12],
                860 => codePageNames[13],
                861 => codePageNames[14],
                862 => codePageNames[15],
                863 => codePageNames[16],
                864 => codePageNames[17],
                865 => codePageNames[18],
                866 => codePageNames[19],
                869 => codePageNames[20],
                874 => codePageNames[21],
                932 => codePageNames[22],
                936 => codePageNames[23],
                949 => codePageNames[24],
                950 => codePageNames[25],
                1200 => codePageNames[26],
                1201 => codePageNames[27],
                1250 => codePageNames[28],
                1251 => codePageNames[29],
                1252 => codePageNames[30],
                1253 => codePageNames[31],
                1254 => codePageNames[32],
                1255 => codePageNames[33],
                1256 => codePageNames[34],
                1257 => codePageNames[35],
                1258 => codePageNames[36],
                10000 => codePageNames[37],
                10001 => codePageNames[38],
                10002 => codePageNames[39],
                10003 => codePageNames[40],
                10004 => codePageNames[41],
                10005 => codePageNames[42],
                10006 => codePageNames[43],
                10007 => codePageNames[44],
                10008 => codePageNames[45],
                10021 => codePageNames[46],
                10029 => codePageNames[47],
                10079 => codePageNames[48],
                10081 => codePageNames[49],
                10082 => codePageNames[50],
                12000 => codePageNames[51],
                12001 => codePageNames[52],
                20936 => codePageNames[53],
                28591 => codePageNames[54],
                28592 => codePageNames[55],
                28593 => codePageNames[56],
                28594 => codePageNames[57],
                28595 => codePageNames[58],
                28596 => codePageNames[59],
                28597 => codePageNames[60],
                28598 => codePageNames[61],
                28599 => codePageNames[62],
                28603 => codePageNames[63],
                28605 => codePageNames[64],
                51936 => codePageNames[65],
                51949 => codePageNames[66],
                52936 => codePageNames[67],
                54936 => codePageNames[68],
                65000 => codePageNames[69],
                65001 => codePageNames[70],
                _ => string.Format(codePageNames[71], codePage)
            };
        }
    }
}