using System.Collections.Generic;

namespace MyTool
{
    public static partial class ConstString
    {
        // MySQL 错误码
        public static readonly Dictionary<int, string> MySqlErrorsMap = new Dictionary<int, string>
        {
            { 1000, "Hashchk" },
            { 1001, "ISAMchk" },
            { 1002, "NO" },
            { 1003, "YES" },
            { 1004, "Can't create file" },
            { 1005, "Can't create table" },
            { 1006, "Can't create database" },
            { 1007, "Database exists" },
            { 1008, "Database doesn't exist" },
            { 1009, "Can't drop database" },
            { 1010, "Can't drop database" },
            { 1011, "Error on drop" },
            { 1012, "Can't read record" },
            { 1013, "Can't get status" },
            { 1014, "Can't get working directory" },
            { 1015, "Can't lock file" },
            { 1016, "Can't open file" },
            { 1017, "Can't find file" },
            { 1018, "Can't read dir" },
            { 1019, "Can't change dir" },
            { 1020, "Record has changed since last read" },
            { 1021, "Disk full" },
            { 1022, "Can't write; duplicate key" },
            { 1023, "Error on close" },
            { 1024, "Error reading file" },
            { 1025, "Error on rename" },
            { 1026, "Error writing file" },
            { 1027, "Table marked as crashed" },
            { 1028, "Fleck error" },
            { 1029, "View doesn't exist" },
            { 1030, "Got error from storage engine" },
            { 1031, "Table storage engine doesn't support specified option" },
            { 1032, "Can't find record" },
            { 1033, "Incorrect information" },
            { 1034, "Incorrect key file" },
            { 1035, "Old key file" },
            { 1036, "Table is read only" },
            { 1037, "Out of memory" },
            { 1038, "Out of sort memory" },
            { 1039, "Unexpected EOF found" },
            { 1040, "Too many connections" },
            { 1041, "Out of memory" },
            { 1042, "Can't get hostname" },
            { 1043, "Bad handshake" },
            { 1044, "Access denied for user to database" },
            { 1045, "Access denied" },
            { 1046, "No database selected" },
            { 1047, "Unknown command" },
            { 1048, "Column cannot be null" },
            { 1049, "Unknown database" },
            { 1050, "Table already exists" },
            { 1051, "Unknown table" },
            { 1052, "Column ambiguous" },
            { 1053, "Server shutdown in progress" },
            { 1054, "Unknown column" },
            { 1055, "Field not in GROUP BY" },
            { 1056, "Wrong group field" },
            { 1057, "Wrong sum select" },
            { 1058, "Wrong value count" },
            { 1059, "Too long identifier" },
            { 1060, "Duplicate column name" },
            { 1061, "Duplicate key name" },
            { 1062, "Duplicate entry" },
            { 1063, "Wrong column specifier" },
            { 1064, "Syntax error" },
            { 1065, "Empty query" },
            { 1066, "Nonunique table" },
            { 1067, "Invalid default" },
            { 1068, "Multiple primary key" },
            { 1069, "Too many keys" },
            { 1070, "Too many key parts" },
            { 1071, "Specified key was too long" },
            { 1072, "Key column doesn't exist in table" },
            { 1073, "BLOB column used as key" },
            { 1074, "Too big row size" },
            { 1075, "Wrong auto key" },
            { 1076, "Ready" },
            { 1077, "Normal shutdown" },
            { 1078, "Got signal" },
            { 1079, "Shutdown complete" },
            { 1080, "Forcing close" },
            { 1081, "Can't create IP socket" },
            { 1082, "Table not found" },
            { 1083, "Field separator argument is not what is expected" },
            { 1084, "Can't read record" },
            { 1090, "You can't delete all columns with ALTER TABLE" },
            { 1091, "Can't DROP" },
            { 1100, "Table was not locked with LOCK TABLES" },
            { 1101, "BLOB/TEXT column can't have a default value" },
            { 1102, "Incorrect database name" },
            { 1103, "Incorrect table name" },
            { 1104, "The SELECT would examine more than MAX_JOIN_SIZE rows" },
            { 1106, "Unknown procedure" },
            { 1107, "Incorrect parameter count to procedure" },
            { 1109, "Unknown table" },
            { 1110, "Column already exists" },
            { 1111, "Invalid use of group function" },
            { 1112, "Table uses an extension that doesn't exist in this MySQL version" },
            { 1113, "A table must have at least 1 column" },
            { 1114, "The table is full" },
            { 1115, "Unknown character set" },
            { 1116, "Too many tables" },
            { 1117, "Too many columns" },
            { 1118, "Row size too large" },
            { 1119, "Thread stack overrun" },
            { 1120, "Cross dependency found in OUTER JOIN" },
            { 1121, "Table handler doesn't support NULL in given index" },
            { 1122, "Couldn't load function" },
            { 1123, "Can't initialize function" },
            { 1124, "No paths allowed for shared library" },
            { 1125, "Function already exists" },
            { 1126, "Can't open shared library" },
            { 1127, "Can't find function in library" },
            { 1128, "Function is not defined" },
            { 1129, "Host is blocked" },
            { 1130, "Host not allowed to connect" },
            { 1131, "You are using MySQL as an anonymous user" },
            { 1132, "You must have privileges" },
            { 1133, "Can't find any matching row in the user table" },
            { 1136, "Column count doesn't match" },
            { 1137, "Can't reopen table" },
            { 1138, "Invalid use of NULL value" },
            { 1139, "Got error from regexp" },
            { 1140, "Mixing of GROUP columns" },
            { 1141, "There is no such grant defined for user" },
            { 1142, "INSERT command denied to user" },
            { 1143, "SELECT command denied to user" },
            { 1144, "UPDATE command denied to user" },
            { 1145, "DELETE command denied to user" },
            { 1146, "Table doesn't exist" },
            { 1147, "There is no such grant defined for user on host" },
            { 1148, "The used command is not allowed with this MySQL version" },
            { 1149, "You have an error in your SQL syntax" },
            { 1152, "Aborted connection" },
            { 1153, "Got a packet bigger than max_allowed_packet bytes" },
            { 1154, "Got a read error from the connection pipe" },
            { 1155, "Got an error from fcntl" },
            { 1156, "Got packets out of order" },
            { 1157, "Couldn't uncompress communication packet" },
            { 1158, "Got an error reading communication packets" },
            { 1159, "Got timeout reading communication packets" },
            { 1160, "Got an error writing communication packets" },
            { 1161, "Got timeout writing communication packets" },
            { 1162, "Result string is longer than max_allowed_packet bytes" },
            { 1163, "The used table type doesn't support BLOB/TEXT columns" },
            { 1164, "The used table type doesn't support AUTO_INCREMENT columns" },
            { 1165, "INSERT DELAYED can't be used with table" },
            { 1166, "Incorrect column name" },
            { 1167, "The used storage engine can't index column" },
            { 1168, "Unable to open underlying table" },
            { 1169, "Can't write, because of unique constraint" },
            { 1170, "BLOB/TEXT column used in key specification" },
            { 1171, "All parts of a PRIMARY KEY must be NOT NULL" },
            { 1172, "Result consisted of more than one row" },
            { 1173, "This table type requires a primary key" },
            { 1174, "This version of MySQL is not compiled with RAID support" },
            { 1175, "You are using safe update mode" },
            { 1176, "Key does not exist in table" },
            { 1177, "Can't open table" },
            { 1178, "The storage engine does not support the ALTER TABLE statement" },
            { 1179, "You are not allowed to execute this command in a transaction" },
            { 1180, "Got error during COMMIT" },
            { 1181, "Got error during ROLLBACK" },
            { 1182, "Got error closing tablespace" },
            { 1183, "Got error opening tablespace" },
            { 1184, "Got error changing log file" },
            { 1185, "Abort: InnoDB needs to be recompiled with higher UNIV_INNODB_MONITOR" },
            { 1186, "Binlog closed" },
            { 1187, "Failed rebuilding table" },
            { 1188, "Error in master heartbeat" },
            { 1189, "Net error reading from master" },
            { 1190, "Net error writing to master" },
            { 1191, "Can't find FULLTEXT index matching the column list" },
            { 1192, "Can't execute the given command because you have active locked tables" },
            { 1193, "Unknown system variable" },
            { 1194, "Table is marked as crashed and should be repaired" },
            { 1195, "Table is marked as crashed and last repair failed" },
            { 1196, "Warning: Some non-transactional changed tables couldn't be rolled back" },
            { 1197, "Multi-statement transaction required more than max_binlog_cache_size bytes" },
            { 1198, "This operation cannot be performed with a running slave" },
            { 1199, "This operation requires a running slave" },
            { 1200, "The server is not configured as slave" },
            { 1201, "Could not initialize master info structure" },
            { 1202, "Could not create slave thread" },
            { 1203, "User already has more than max_user_connections active connections" },
            { 1204, "You may only use constant expressions with SET" },
            { 1205, "Lock wait timeout exceeded" },
            { 1206, "The total number of locks exceeds the lock table size" },
            { 1207, "Update locks cannot be acquired during a READ UNCOMMITTED transaction" },
            { 1208, "DROP DATABASE failed" },
            { 1209, "Cannot delete or update a parent row" },
            { 1210, "Incorrect arguments to" },
            { 1211, "Access denied; you need the RELOAD privilege for this operation" },
            { 1212, "ALTER TABLE with duplicate UNIQUE/FULLTEXT/SPATIAL indexes" },
            { 1213, "Deadlock found when trying to get lock" },
            { 1214, "The used table type doesn't support FULLTEXT indexes" },
            { 1215, "Cannot add foreign key constraint" },
            { 1216, "Cannot add or update a child row" },
            { 1217, "Cannot delete or update a parent row" },
            { 1218, "Error connecting to master" },
            { 1219, "Error running query on master" },
            { 1220, "Error when executing command" },
            { 1221, "Incorrect usage of UNION and ORDER BY" },
            { 1222, "The used SELECT statements have a different number of columns" },
            { 1223, "Can't execute the query because you have a conflicting read lock" },
            { 1224, "Mixing of transactional and non-transactional tables is disabled" },
            { 1225, "Option used twice in statement" },
            { 1226, "User has exceeded the max_questions resource" },
            { 1227, "Access denied; you need the SUPER privilege for this operation" },
            { 1228, "Variable is a SESSION variable and can't be used with SET GLOBAL" },
            { 1229, "Variable is a GLOBAL variable and should be set with SET GLOBAL" },
            { 1230, "Variable doesn't have a default value" },
            { 1231, "Variable can't be set to the value of" },
            { 1232, "Incorrect argument type to function" },
            { 1233, "Incorrect usage of" },
            { 1234, "Incorrect usage of" },
            { 1235, "This version of MySQL doesn't yet support" },
            { 1236, "Got fatal error from master when reading data from binary log" },
            { 1237, "Slave SQL thread ignored the query because of replicate-*-table rules" },
            { 1238, "Variable is a read only variable" },
            { 1239, "Incorrect foreign key definition" },
            { 1240, "Key reference and table reference don't match" },
            { 1241, "Operand should contain 1 column(s)" },
            { 1242, "Subquery returns more than 1 row" },
            { 1243, "Unknown prepared statement handler given to" },
            { 1244, "Help topic not found" },
            { 1245, "Cyclic reference on subqueries" },
            { 1246, "Converting column from to" },
            { 1247, "Reference to table not supported in this context" },
            { 1248, "Every derived table must have its own alias" },
            { 1249, "Select reduced the number of rows" },
            { 1250, "Table from one of the SELECTs cannot be used in" },
            { 1251, "Client does not support authentication protocol requested by server" },
            { 1252, "All parts of a SPATIAL index must be NOT NULL" },
            { 1253, "COLLATION is not valid for CHARACTER SET" },
            { 1254, "Slave SQL thread stopped because UDF function is not defined" },
            { 1255, "Slave SQL thread stopped because UDF function is not defined" },
            { 1256, "String is too long for column" },
            { 1257, "Too long string" },
            { 1258, "Too long row" },
            { 1259, "Replication event checksum verification failed" },
            { 1260, "Row was trimmed" },
            { 1261, "Row has wrong number of columns" },
            { 1262, "Row was truncated" },
            { 1263, "Column set to default value" },
            { 1264, "Out of range value for column" },
            { 1265, "Data truncated for column" },
            { 1266, "Using storage engine for table" },
            { 1267, "Illegal mix of collations" },
            { 1268, "Table is read only" },
            { 1269, "Can't drop one or more of the requested users" },
            { 1270, "Illegal mix of collations" },
            { 1271, "Illegal mix of collations at character set level" },
            { 1272, "Illegal mix of collations for operation" },
            { 1273, "Unknown collation" },
            { 1274, "SSL parameters in CHANGE MASTER are ignored" },
            { 1275, "Server is running in secure-auth mode" },
            { 1276, "Field or reference to field not in GROUP BY clause" },
            { 1277, "Invalid use of an aggregate function" },
            { 1278, "Partition not defined" },
            { 1279, "The ORDER BY clause must contain all columns in the GROUP BY clause" },
            { 1280, "For SELECT DISTINCT, ORDER BY expressions must appear in select list" },
            { 1281, "Unknown table" },
            { 1282, "Key column doesn't exist in table" },
            { 1283, "Table storage engine doesn't support specified option" },
            { 1284, "Uncompressed data size too large" },
            { 1285, "Table is already up to date" },
            { 1286, "Unknown storage engine" },
            { 1287, "is deprecated and will be removed in a future release" },
            { 1288, "The target table of the statement is not updatable" },
            { 1289, "The feature is disabled" },
            { 1290, "The MySQL server is running with the option so it cannot execute this statement" },
            { 1291, "Column has duplicated value" },
            { 1292, "Truncated incorrect value" },
            { 1293, "Incorrect table definition" },
            { 1294, "Invalid ON UPDATE clause for stored function" },
            { 1295, "This command is not supported in the prepared statement protocol yet" },
            { 1296, "Got error from storage engine" },
            { 1297, "Got temporary error from storage engine" },
            { 1298, "Unknown or incorrect time zone" },
            { 1299, "Invalid TIMESTAMP value in column at row" },
            { 1300, "Invalid character string" },
            { 1301, "Federated server not found" },
            { 1302, "Federated table not found" },
            { 1303, "Federated table creation failed" },
            { 1304, "Federated table already exists" },
            { 1305, "Federated table does not exist" },
            { 1306, "Federated table is not supported" },
            { 1307, "Federated table is not supported" },
            { 1308, "Federated table is not supported" },
            { 1309, "Federated table is not supported" },
            { 1310, "Federated table is not supported" },
            { 1311, "Federated table is not supported" },
            { 1312, "PROCEDURE can't return a result set in the given context" },
            { 1313, "RETURN is only allowed in a FUNCTION" },
            { 1314, "FUNCTION is not allowed in the given context" },
            { 1315, "MODIFY COLUMN is not supported" },
            { 1316, "Master key rotation is not supported by this storage engine" },
            { 1317, "Query execution was interrupted" },
            { 1318, "Incorrect number of arguments for PROCEDURE" },
            { 1319, "Undefined CONDITION" },
            { 1320, "No RETURN found in FUNCTION" },
            { 1321, "FUNCTION is not allowed in the given context" },
            { 1322, "PROCEDURE is not allowed in the given context" },
            { 1323, "Cursor is not allowed in the given context" },
            { 1324, "Undefined CURSOR" },
            { 1325, "Cursor is already open" },
            { 1326, "Cursor is not open" },
            { 1327, "Undeclared variable" },
            { 1328, "Incorrect number of FETCH variables" },
            { 1329, "No data - zero rows fetched, selected, or processed" },
            { 1330, "Duplicate parameter" },
            { 1331, "Duplicate variable" },
            { 1332, "Duplicate condition" },
            { 1333, "Duplicate cursor" },
            { 1334, "Failed to ALTER TABLE" },
            { 1335, "Subquery value not supported" },
            { 1336, "STORED PROGRAMS and TRIGGERS are not supported" },
            { 1337, "Variable or condition declaration after cursor or handler declaration" },
            { 1338, "Cursor declaration after handler declaration" },
            { 1339, "Case not found for CASE statement" },
            { 1340, "Not allowed to return NULL from a function that returns a non-nullable type" },
            { 1341, "Event execution failed" },
            { 1342, "Event execution failed" },
            { 1343, "Event execution failed" },
            { 1344, "Event execution failed" },
            { 1345, "Event execution failed" },
            { 1346, "Event execution failed" },
            { 1347, "is not BASE TABLE" },
            { 1348, "Column is not updatable" },
            { 1349, "View SELECT contains a subquery in the FROM clause" },
            { 1350, "View SELECT contains a subquery in the WHERE clause" },
            { 1351, "View SELECT contains a subquery in the SELECT clause" },
            { 1352, "View SELECT contains a subquery in the ORDER BY clause" },
            { 1353, "View SELECT contains a subquery in the GROUP BY clause" },
            { 1354, "View SELECT contains a subquery in the HAVING clause" },
            { 1355, "View SELECT contains a UNION" },
            { 1356, "View SELECT contains a JOIN" },
            { 1357, "Cannot change thread logging mode inside a stored function or trigger" },
            { 1358, "View SELECT contains a HAVING clause" },
            { 1359, "View SELECT contains a LIMIT clause" },
            { 1360, "View SELECT contains a PROCEDURE" },
            { 1361, "View SELECT contains a INTO clause" },
            { 1362, "Updating of table is not allowed in a stored function or trigger" },
            { 1363, "No DEFAULT value for column" },
            { 1364, "Field doesn't have a default value" },
            { 1365, "Division by 0" },
            { 1366, "Incorrect string value" },
            { 1367, "Illegal double value" },
            { 1368, "Illegal decimal value" },
            { 1369, "CHECK OPTION failed" },
            { 1370, "Access denied; you need privileges for this operation" },
            { 1371, "Access denied; you need privileges for this operation" },
            { 1372, "Password hash should be a string" },
            { 1373, "Cannot drop one or more of the requested users" },
            { 1374, "Can't execute the given command because you have active locked tables" },
            { 1375, "Server is running in secure-auth mode" },
            { 1376, "Federated server not found" },
            { 1377, "Federated table not found" },
            { 1378, "Federated table creation failed" },
            { 1379, "Federated table already exists" },
            { 1380, "Federated table does not exist" },
            { 1381, "Federated table is not supported" },
            { 1382, "Federated table is not supported" },
            { 1383, "Federated table is not supported" },
            { 1384, "Federated table is not supported" },
            { 1385, "Federated table is not supported" },
            { 1386, "Federated table is not supported" },
            { 1387, "Federated table is not supported" },
            { 1388, "Federated table is not supported" },
            { 1389, "Federated table is not supported" },
            { 1390, "Federated table is not supported" },
            { 1391, "Federated table is not supported" },
            { 1392, "Federated table is not supported" },
            { 1393, "Federated table is not supported" },
            { 1394, "Federated table is not supported" },
            { 1395, "Federated table is not supported" },
            { 1396, "Operation CREATE USER failed for" },
            { 1397, "XAER_NOTA: Unknown XID" },
            { 1398, "XAER_INVAL: Invalid arguments (or unsupported command)" },
            { 1399, "XAER_RMFAIL: The command cannot be executed when global transaction is in the state" },
            { 1400, "XAER_OUTSIDE: Some work is done outside global transaction" },
            { 1401, "XAER_RMERR: Fatal error occurred in the transaction branch" },
            { 1402, "XA_RBROLLBACK: Transaction branch was rolled back" },
            { 1403, "There is no such grant defined for user on host on routine" },
            { 1404, "Failed to grant EXECUTE and ALTER ROUTINE privileges" },
            { 1405, "Failed to revoke all privileges to dropped routine" },
            { 1406, "Data too long for column" },
            { 1407, "Failed to grant EXECUTE and ALTER ROUTINE privileges" },
            { 1408, "Failed to revoke all privileges to dropped routine" },
            { 1409, "Cannot delete or update a parent row" },
            { 1410, "Access denied; you need privileges for this operation" },
            { 1411, "Incorrect value" },
            { 1412, "Table definition has changed" },
            { 1413, "Duplicate handler declared in the same block" },
            { 1414, "OUT or INOUT argument is not a variable or NEW pseudo-variable" },
            { 1415, "Not allowed to return a result set from a stored function" },
            { 1416, "Cannot get geometry object from data you send to the GEOMETRY field" },
            { 1417, "A routine failed and has neither NO SQL nor READS SQL DATA in its declaration" },
            { 1418, "This function has none of DETERMINISTIC, NO SQL, or READS SQL DATA in its declaration" },
            { 1419, "You do not have the SUPER privilege and binary logging is enabled" },
            { 1420, "You do not have the SUPER privilege and binary logging is enabled" },
            { 1421, "You do not have the SUPER privilege and binary logging is enabled" },
            { 1422, "Explicit or implicit commit is not allowed in stored function or trigger" },
            { 1423, "Field level privileges are not supported for views" },
            { 1424, "Routine body for is not syntactically correct" },
            { 1425, "Too big scale for column at row" },
            { 1426, "Too big precision for column at row" },
            { 1427, "For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column at row)" },
            { 1428, "You can't combine write-locking of system tables with other tables or lock types" },
            { 1429, "Unable to connect to foreign data source" },
            { 1430, "There was an error processing the query" },
            { 1431, "The foreign data source you are trying to reference does not exist" },
            { 1432, "Can't create federated table. The data source connection string is not in the correct format" },
            { 1433, "The data source connection string is not in the correct format" },
            { 1434, "Can't create federated table. Foreign data src error" },
            { 1435, "Trigger in wrong schema" },
            { 1436, "Thread stack overrun" },
            { 1437, "Too high level of nesting for select" },
            { 1438, "Name becomes empty" },
            { 1439, "Display width out of range for column" },
            { 1440, "XAER_DUPID: The XID already exists" },
            { 1441, "Datetime function overflow" },
            { 1442, "Can't update table in stored function/trigger because it is already used by statement which invoked this stored function/trigger" },
            { 1443, "The definition of table prevents operation on table" },
            { 1444, "The prepared statement contains a stored routine call that refers to that same statement" },
            { 1445, "Not allowed to set autocommit from a stored function or trigger" },
            { 1446, "Definer is not fully qualified" },
            { 1447, "View definer is not fully qualified" },
            { 1448, "You need the SUPER privilege for creation view with" },
            { 1449, "The user specified as a definer does not exist" },
            { 1450, "Changing schema from to is not allowed" },
            { 1451, "Cannot delete or update a parent row" },
            { 1452, "Cannot add or update a child row" },
            { 1453, "Variable is not a variable component" },
            { 1454, "Failed to read view" },
            { 1455, "Table charset does not match temp table charset" },
            { 1456, "Recursive limit reached" },
            { 1457, "Failed to grant EXECUTE and ALTER ROUTINE privileges" },
            { 1458, "Table does not exist" },
            { 1459, "Table is read only" },
            { 1460, "Same name for table and alias" },
            { 1461, "Can bind a LONG value only for insert into a LONG column" },
            { 1462, "Data truncated for functional index" },
            { 1463, "Data truncated for functional index" },
            { 1464, "Row in wrong partition" },
            { 1465, "XML nodes do not match" },
            { 1466, "Malformed file" },
            { 1467, "Wrong parameters for" },
            { 1468, "Wrong parameters for" },
            { 1469, "Wrong parameters for" },
            { 1470, "String is too long for key" },
            { 1471, "The table does not comply with the requirements by an external plugin" },
            { 1472, "Column count does not match value count" },
            { 1473, "Row size too large" },
            { 1474, "Table has no partition for value" },
            { 1475, "Row size too large" },
            { 1476, "Row size too large" },
            { 1477, "Row size too large" },
            { 1478, "Row size too large" },
            { 1479, "Row size too large" },
            { 1480, "Row size too large" },
            { 1481, "Row size too large" },
            { 1482, "Row size too large" },
            { 1483, "Row size too large" },
            { 1484, "Row size too large" },
            { 1485, "Row size too large" },
            { 1486, "Row size too large" },
            { 1487, "Row size too large" },
            { 1488, "Row size too large" },
            { 1489, "Row size too large" },
            { 1490, "Row size too large" },
            { 1491, "Row size too large" },
            { 1492, "Row size too large" },
            { 1493, "Row size too large" },
            { 1494, "Row size too large" },
            { 1495, "Row size too large" },
            { 1496, "Row size too large" },
            { 1497, "Row size too large" },
            { 1498, "Row size too large" },
            { 1499, "Row size too large" },
            { 1500, "Row size too large" },
            { 1501, "Row size too large" },
            { 1502, "Row size too large" },
            { 1503, "Row size too large" },
            { 1504, "Row size too large" },
            { 1505, "Row size too large" },
            { 1506, "Row size too large" },
            { 1507, "Row size too large" },
            { 1508, "Row size too large" },
            { 1509, "Row size too large" },
            { 1510, "Row size too large" },
            { 1511, "Row size too large" },
            { 1512, "Row size too large" },
            { 1513, "Row size too large" },
            { 1514, "Row size too large" },
            { 1515, "Row size too large" },
            { 1516, "Row size too large" },
            { 1517, "Row size too large" },
            { 1518, "Row size too large" },
            { 1519, "Row size too large" },
            { 1520, "Row size too large" },
            { 1521, "Row size too large" },
            { 1522, "Row size too large" },
            { 1523, "Row size too large" },
            { 1524, "Plugin is not loaded" },
            { 1525, "Incorrect datetime value" },
            { 1526, "Table has no partition for some existing values" },
            { 1527, "Failed to store row in the table" },
            { 1528, "Failed to create table" },
            { 1529, "Failed to alter table" },
            { 1530, "Failed to drop table" },
            { 1531, "Failed to create index" },
            { 1532, "Failed to alter index" },
            { 1533, "Failed to drop index" },
            { 1534, "Failed to create view" },
            { 1535, "Failed to alter view" },
            { 1536, "Failed to drop view" },
            { 1537, "Failed to create schema" },
            { 1538, "Failed to alter schema" },
            { 1539, "Failed to drop schema" },
            { 1540, "Failed to create trigger" },
            { 1541, "Failed to alter trigger" },
            { 1542, "Failed to drop trigger" },
            { 1543, "Failed to create event" },
            { 1544, "Failed to alter event" },
            { 1545, "Failed to drop event" },
            { 1546, "Failed to create function" },
            { 1547, "Failed to alter function" },
            { 1548, "Failed to drop function" },
            { 1549, "Failed to create procedure" },
            { 1550, "Failed to alter procedure" },
            { 1551, "Failed to drop procedure" },
            { 1552, "Failed to create user" },
            { 1553, "Failed to alter user" },
            { 1554, "Failed to drop user" },
            { 1555, "Failed to create role" },
            { 1556, "Failed to alter role" },
            { 1557, "Failed to drop role" },
            { 1558, "Column count doesn't match value count at row" },
            { 1559, "Cannot load from table" },
            { 1560, "Cannot delete from table which is used by a view" },
            { 1561, "Cannot delete from table which is used by a stored function or trigger" },
            { 1562, "Cannot delete from table which is used by a stored procedure" },
            { 1563, "Cannot delete from table which is used by an event" },
            { 1564, "Cannot delete from table which is used by a function" },
            { 1565, "Cannot delete from table which is used by a trigger" },
            { 1566, "Cannot delete from table which is used by a view" },
            { 1567, "Incorrect table name" },
            { 1568, "Transaction level is not allowed while autocommit is enabled" },
            { 1569, "ALTER EVENT statement must contain at least one event attribute" },
            { 1570, "MySQL server has gone away" },
            { 1571, "MySQL client ran out of memory" },
            { 1572, "Statement is unsafe because it uses a LIMIT clause" },
            { 1573, "Statement is unsafe because it uses INSERT DELAYED" },
            { 1574, "Statement is unsafe because it uses REPLACE" },
            { 1575, "Statement is unsafe because it uses INSERT IGNORE" },
            { 1576, "Statement is unsafe because it uses INSERT...ON DUPLICATE KEY UPDATE" },
            { 1577, "Statement is unsafe because it uses INSERT...SELECT" },
            { 1578, "Statement is unsafe because it uses UPDATE IGNORE" },
            { 1579, "Statement is unsafe because it uses DELETE IGNORE" },
            { 1580, "Statement is unsafe because it uses CREATE TEMPORARY TABLE" },
            { 1581, "Statement is unsafe because it uses DROP TEMPORARY TABLE" },
            { 1582, "Incorrect number of arguments for native function" },
            { 1583, "Incorrect parameters in the call to native function" },
            { 1584, "Incorrect parameters in the call to stored function" },
            { 1585, "This function is not defined for the current SQL mode" },
            { 1586, "Duplicate entry for key" },
            { 1587, "The table does not comply with the requirements by an external plugin" },
            { 1588, "Column count doesn't match value count at row" },
            { 1589, "Can't load function" },
            { 1590, "Can't initialize function" },
            { 1591, "No paths allowed for shared library" },
            { 1592, "Function already exists" },
            { 1593, "Can't open shared library" },
            { 1594, "Can't find function in library" },
            { 1595, "Function is not defined" },
            { 1596, "Can't initialize function" },
            { 1597, "No paths allowed for shared library" },
            { 1598, "Function already exists" },
            { 1599, "Can't open shared library" },
            { 1600, "Can't find function in library" },
            { 1601, "Function is not defined" },
            { 1602, "Can't initialize function" },
            { 1603, "No paths allowed for shared library" },
            { 1604, "Function already exists" },
            { 1605, "Can't open shared library" },
            { 1606, "Can't find function in library" },
            { 1607, "Function is not defined" },
            { 1608, "Can't initialize function" },
            { 1609, "No paths allowed for shared library" },
            { 1610, "Function already exists" },
            { 1611, "Can't open shared library" },
            { 1612, "Can't find function in library" },
            { 1613, "Function is not defined" },
            { 1614, "Transactional DDL statements are not allowed" },
            { 1615, "Prepared statement needs to be re-prepared" },
            { 1616, "DELAYED option not supported for table" },
            { 1617, "The master info structure does not exist" },
            { 1618, "is deprecated and will be removed in a future release" },
            { 1619, "Aborted connection to db" },
            { 1620, "Access denied; you need privileges for this operation" },
            { 1621, "Access denied; you need privileges for this operation" },
            { 1622, "Access denied; you need privileges for this operation" },
            { 1623, "Access denied; you need privileges for this operation" },
            { 1624, "Access denied; you need privileges for this operation" },
            { 1625, "Access denied; you need privileges for this operation" },
            { 1626, "Access denied; you need privileges for this operation" },
            { 1627, "Access denied; you need privileges for this operation" },
            { 1628, "Access denied; you need privileges for this operation" },
            { 1629, "Access denied; you need privileges for this operation" },
            { 1630, "FUNCTION does not exist. Check the Function Name Spelling and Check the Function Exists" },
            { 1631, "Database" },
            { 1632, "Table" },
            { 1633, "Partition" },
            { 1634, "Subpartition" },
            { 1635, "Constraint" },
            { 1636, "Index" },
            { 1637, "Trigger" },
            { 1638, "Event" },
            { 1639, "Routine" },
            { 1640, "Tablespace" },
            { 1641, "Schema" },
            { 1642, "Savepoint" },
            { 1643, "Role" },
            { 1644, "User" },
            { 1645, "Plugin" },
            { 1646, "Log file" },
            { 1647, "General log" },
            { 1648, "Slow log" },
            { 1649, "Relay log" },
            { 1650, "Binary log" },
            { 1651, "Error log" },
            { 1652, "Audit log" },
            { 1653, "Firewall" },
            { 1654, "Firewall trace" },
            { 1655, "Firewall users" },
            { 1656, "Firewall whitelist" },
            { 1657, "Performance schema" },
            { 1658, "Information schema" },
            { 1659, "Sys schema" },
            { 1660, "mysql schema" },
            { 1661, "test schema" },
            { 1662, "world schema" },
            { 1663, "sakila schema" },
            { 1664, "employees schema" },
            { 1665, "northwind schema" },
            { 1666, "classicmodels schema" },
            { 1667, "menagerie schema" },
            { 1668, "AirportDB schema" },
            { 1669, "World2 schema" },
            { 1670, "World3 schema" },
            { 1671, "World4 schema" },
            { 1672, "World5 schema" },
            { 1673, "World6 schema" },
            { 1674, "World7 schema" },
            { 1675, "World8 schema" },
            { 1676, "World9 schema" },
            { 1677, "World10 schema" },
            { 1678, "World11 schema" },
            { 1679, "World12 schema" },
            { 1680, "World13 schema" },
            { 1681, "World14 schema" },
            { 1682, "World15 schema" },
            { 1683, "World16 schema" },
            { 1684, "World17 schema" },
            { 1685, "World18 schema" },
            { 1686, "World19 schema" },
            { 1687, "World20 schema" },
            { 1688, "World21 schema" },
            { 1689, "World22 schema" },
            { 1690, "BIGINT UNSIGNED value is out of range" },
            { 1691, "Multiple defaults" },
            { 1692, "Invalid default value for" },
            { 1693, "Multiple defaults" },
            { 1694, "Invalid default value for" },
            { 1695, "Multiple defaults" },
            { 1696, "Invalid default value for" },
            { 1697, "Multiple defaults" },
            { 1698, "Access denied for user using password" },
            { 1699, "Invalid default value for" },
            { 1700, "Multiple defaults" },
            { 1701, "Invalid default value for" },
            { 1702, "Multiple defaults" },
            { 1703, "Invalid default value for" },
            { 1704, "Multiple defaults" },
            { 1705, "Invalid default value for" },
            { 1706, "Multiple defaults" },
            { 1707, "Invalid default value for" },
            { 1708, "Multiple defaults" },
            { 1709, "Index column size too large" },
            { 1710, "Invalid default value for" },
            { 1711, "Multiple defaults" },
            { 1712, "Invalid default value for" },
            { 1713, "Multiple defaults" },
            { 1714, "Invalid default value for" },
            { 1715, "Multiple defaults" },
            { 1716, "Invalid default value for" },
            { 1717, "Access denied; you need privileges for this operation" },
            { 1718, "Multiple defaults" },
            { 1719, "Invalid default value for" },
            { 1720, "Multiple defaults" },
            { 1721, "Invalid default value for" },
            { 1722, "Multiple defaults" },
            { 1723, "Invalid default value for" },
            { 1724, "Multiple defaults" },
            { 1725, "Invalid default value for" },
            { 1726, "Multiple defaults" },
            { 1727, "Invalid default value for" },
            { 1728, "Multiple defaults" },
            { 1729, "Invalid default value for" },
            { 1730, "Multiple defaults" },
            { 1731, "Invalid default value for" },
            { 1732, "Multiple defaults" },
            { 1733, "Invalid default value for" },
            { 1734, "Multiple defaults" },
            { 1735, "Invalid default value for" },
            { 1736, "Multiple defaults" },
            { 1737, "Invalid default value for" },
            { 1738, "Multiple defaults" },
            { 1739, "Invalid default value for" },
            { 1740, "Multiple defaults" },
            { 1741, "Invalid default value for" },
            { 1742, "Multiple defaults" },
            { 1743, "Invalid default value for" },
            { 1744, "Multiple defaults" },
            { 1745, "Invalid default value for" },
            { 1746, "Multiple defaults" },
            { 1747, "Invalid default value for" },
            { 1748, "Multiple defaults" },
            { 1749, "Invalid default value for" },
            { 1750, "Multiple defaults" },
            { 1751, "Invalid default value for" },
            { 1752, "Multiple defaults" },
            { 1753, "Invalid default value for" },
            { 1754, "Multiple defaults" },
            { 1755, "Invalid default value for" },
            { 1756, "Multiple defaults" },
            { 1757, "Invalid default value for" },
            { 1758, "Multiple defaults" },
            { 1759, "Invalid default value for" },
            { 1760, "Multiple defaults" },
            { 1761, "Invalid default value for" },
            { 1762, "Multiple defaults" },
            { 1763, "Invalid default value for" },
            { 1764, "Multiple defaults" },
            { 1765, "Invalid default value for" },
            { 1766, "Multiple defaults" },
            { 1767, "Invalid default value for" },
            { 1768, "Multiple defaults" },
            { 1769, "Invalid default value for" },
            { 1770, "Multiple defaults" },
            { 1771, "Invalid default value for" },
            { 1772, "Multiple defaults" },
            { 1773, "Invalid default value for" },
            { 1774, "Multiple defaults" },
            { 1775, "Invalid default value for" },
            { 1776, "Multiple defaults" },
            { 1777, "Invalid default value for" },
            { 1778, "Multiple defaults" },
            { 1779, "Invalid default value for" },
            { 1780, "Multiple defaults" },
            { 1781, "Invalid default value for" },
            { 1782, "Multiple defaults" },
            { 1783, "Invalid default value for" },
            { 1784, "Multiple defaults" },
            { 1785, "Invalid default value for" },
            { 1786, "Multiple defaults" },
            { 1787, "Invalid default value for" },
            { 1788, "Multiple defaults" },
            { 1789, "Invalid default value for" },
            { 1790, "Multiple defaults" },
            { 1791, "Invalid default value for" },
            { 1792, "Multiple defaults" },
            { 1793, "Invalid default value for" },
            { 1794, "Multiple defaults" },
            { 1795, "Invalid default value for" },
            { 1796, "Multiple defaults" },
            { 1797, "Invalid default value for" },
            { 1798, "Multiple defaults" },
            { 1799, "Invalid default value for" },
            { 1800, "Multiple defaults" },
            { 1801, "Invalid default value for" },
            { 1802, "Multiple defaults" },
            { 1803, "Invalid default value for" },
            { 1804, "Multiple defaults" },
            { 1805, "Invalid default value for" },
            { 1806, "Multiple defaults" },
            { 1807, "Invalid default value for" },
            { 1808, "Multiple defaults" },
            { 1809, "Invalid default value for" },
            { 1810, "Multiple defaults" },
            { 1811, "Invalid default value for" },
            { 1812, "Multiple defaults" },
            { 1813, "Invalid default value for" },
            { 1814, "Multiple defaults" },
            { 1815, "Invalid default value for" },
            { 1816, "Multiple defaults" },
            { 1817, "Invalid default value for" },
            { 1818, "Multiple defaults" },
            { 1819, "Invalid default value for" },
            { 1820, "Multiple defaults" },
            { 1821, "Invalid default value for" },
            { 1822, "Multiple defaults" },
            { 1823, "Invalid default value for" },
            { 1824, "Multiple defaults" },
            { 1825, "Invalid default value for" },
            { 1826, "Multiple defaults" },
            { 1827, "Invalid default value for" },
            { 1828, "Multiple defaults" },
            { 1829, "Invalid default value for" },
            { 1830, "Multiple defaults" },
            { 1831, "Invalid default value for" },
            { 1832, "Multiple defaults" },
            { 1833, "Invalid default value for" },
            { 1834, "Multiple defaults" },
            { 1835, "Invalid default value for" },
            { 1836, "Multiple defaults" },
            { 1837, "Invalid default value for" },
            { 1838, "Multiple defaults" },
            { 1839, "Invalid default value for" },
            { 1840, "Multiple defaults" },
            { 1841, "Invalid default value for" },
            { 1842, "Multiple defaults" },
            { 1843, "Invalid default value for" },
            { 1844, "Multiple defaults" },
            { 1845, "Invalid default value for" },
            { 1846, "Multiple defaults" },
            { 1847, "Invalid default value for" },
            { 1848, "Multiple defaults" },
            { 1849, "Invalid default value for" },
            { 1850, "Multiple defaults" },
            { 1851, "Invalid default value for" }
        };
    }
}