using MyTool.Enums;

namespace MyTool
{
    public static partial class ConstString
    {
        // ODBC 错误码 - 英文
        private static readonly Dictionary<string, string> OdbcErrorsMapEnglish = new()
        {
            { "00000", "Success" },
            { "01000", "General warning" },
            { "01002", "Disconnect error" },
            { "01004", "Data truncated" },
            { "01006", "Privilege not revoked" },
            { "01S00", "Invalid connection string attribute" },
            { "01S01", "Error in row" },
            { "01S02", "Option value changed" },
            { "01S03", "No rows updated or deleted" },
            { "01S04", "More than one row updated or deleted" },
            { "01S05", "Function sequence error" },
            { "01S06", "Attempt to fetch before result set returned first row" },
            { "07001", "Wrong number of parameters" },
            { "07006", "Restricted data type violation" },
            { "07S01", "Invalid use of default parameter" },
            { "08001", "Unable to connect to data source" },
            { "08002", "Connection in use" },
            { "08003", "Connection not open" },
            { "08004", "Data source rejected establishment of connection" },
            { "08007", "Connection failure during transaction" },
            { "08S01", "Communication link failure" },
            { "21S01", "Insert value list does not match column list" },
            { "21S02", "Degree of derived table does not match column list" },
            { "22001", "String data, right-truncated" },
            { "22002", "Indicator variable required but not supplied" },
            { "22003", "Numeric value out of range" },
            { "22005", "Error in assignment" },
            { "22008", "Datetime field overflow" },
            { "22012", "Division by zero" },
            { "22026", "String data length mismatch" },
            { "23000", "Integrity constraint violation" },
            { "24000", "Invalid cursor state" },
            { "25000", "Invalid transaction state" },
            { "28000", "Invalid authorization specification" },
            { "34000", "Invalid cursor name" },
            { "37000", "Syntax error or access violation" },
            { "3C000", "Duplicate cursor name" },
            { "40001", "Serialization failure" },
            { "42000", "Syntax error or access violation" },
            { "70100", "Operation cancelled" },
            { "IM001", "Driver does not support this function" },
            { "IM002", "Data source name not found and no default driver specified" },
            { "IM003", "Specified driver could not be loaded" },
            { "IM004", "Driver's SQLAllocEnv failed" },
            { "IM005", "Driver's SQLAllocConnect failed" },
            { "IM006", "Driver's SQLSetConnectOption failed" },
            { "IM007", "No data source or driver specified; dialog prohibited" },
            { "IM008", "Dialog failed" },
            { "IM009", "Unable to load translation DLL" },
            { "IM010", "Data source name too long" },
            { "IM011", "Driver name too long" },
            { "IM012", "DRIVER keyword syntax error" },
            { "IM013", "Trace file error" },
            { "S0001", "Base table or view already exists" },
            { "S0002", "Base table not found" },
            { "S0011", "Index already exists" },
            { "S0012", "Index not found" },
            { "S0021", "Column already exists" },
            { "S0022", "Column not found" },
            { "S0023", "Column has no default value" },
            { "S1000", "General error" },
            { "S1001", "Memory allocation failure" },
            { "S1002", "Invalid column number" },
            { "S1003", "Program type out of range" },
            { "S1004", "SQL data type out of range" },
            { "S1008", "Operation cancelled" },
            { "S1009", "Invalid argument value" },
            { "S1010", "Function sequence error" },
            { "S1011", "Operation invalid at this time" },
            { "S1012", "Invalid transaction operation code specified" },
            { "S1015", "No cursor name available" },
            { "S1090", "Invalid string or buffer length" },
            { "S1091", "Descriptor type out of range" },
            { "S1092", "Option type out of range" },
            { "S1093", "Invalid parameter number" },
            { "S1094", "Invalid precision value" },
            { "S1095", "Function type out of range" },
            { "S1096", "Info type out of range" },
            { "S1097", "Column type out of range" },
            { "S1098", "Scope type out of range" },
            { "S1099", "Nullable type out of range" },
            { "S1100", "Uniqueness option type out of range" },
            { "S1101", "Accuracy option type out of range" },
            { "S1103", "Direction option out of range" },
            { "S1104", "Invalid precision value" },
            { "S1105", "Invalid parameter type" },
            { "S1106", "Extract type out of range" },
            { "S1107", "Row value out of range" },
            { "S1108", "Concurrency option out of range" },
            { "S1109", "Invalid cursor position" },
            { "S1110", "Invalid driver completion" },
            { "S1111", "Invalid bookmark value" },
            { "S1C00", "Driver not capable" },
            { "S1DE0", "Operation completed successfully with no data" },
            { "S1T00", "Timeout expired" }
        };

        // ODBC 错误码 - 简体中文
        private static readonly Dictionary<string, string> OdbcErrorsMapSimplifiedChinese = new()
        {
            { "00000", "成功" },
            { "01000", "常规警告" },
            { "01002", "断开连接错误" },
            { "01004", "数据被截断" },
            { "01006", "未废除特权" },
            { "01S00", "无效连接字符串特性" },
            { "01S01", "行中的错误" },
            { "01S02", "选项值已更改" },
            { "01S03", "未更新或删除任何行" },
            { "01S04", "更新或删除了多行" },
            { "01S05", "取消操作被当成 FreeStmt/Close" },
            { "01S06", "设法在结果返回第一个行集之前进行提取" },
            { "07001", "参数个数错误" },
            { "07006", "违反受限制的数据类型特性" },
            { "07S01", "默认参数使用无效" },
            { "08001", "无法连接到数据源" },
            { "08002", "连接正在使用" },
            { "08003", "连接未打开" },
            { "08004", "数据源拒绝建立连接" },
            { "08007", "在执行事务的过程中连接失败" },
            { "08S01", "通讯链接失败" },
            { "21S01", "插入值列表与列列表不匹配" },
            { "21S02", "派生表的程度与列列表不匹配" },
            { "22001", "字符串数据右截断" },
            { "22002", "需要指示符变量，但未提供" },
            { "22003", "数字值超出范围" },
            { "22005", "分配时出错" },
            { "22008", "Datetime 字段溢出" },
            { "22012", "被零除错误" },
            { "22026", "字符串数据，长度不匹配" },
            { "23000", "违反完整性约束" },
            { "24000", "无效的游标状态" },
            { "25000", "无效的事务状态" },
            { "28000", "无效的授权规范" },
            { "34000", "无效的游标名称" },
            { "37000", "语法错误或违规访问" },
            { "3C000", "重复的游标名称" },
            { "40001", "串行错误" },
            { "42000", "语法错误或违规访问" },
            { "70100", "操作终止" },
            { "IM001", "驱动程序不支持本函数" },
            { "IM002", "未找到源名称并且未指定默认驱动程序" },
            { "IM003", "无法装载指定的驱动程序" },
            { "IM004", "驱动程序的 SQLAllocEnv 失败" },
            { "IM005", "驱动程序的 SQLAllocConnect 失败" },
            { "IM006", "驱动程序的 SQLSetConnectOption 失败" },
            { "IM007", "未指定数据源或驱动程序；禁止对话" },
            { "IM008", "对话失败" },
            { "IM009", "无法装载转换 DLL" },
            { "IM010", "数据源名称过长" },
            { "IM011", "驱动程序名称过长" },
            { "IM012", "DRIVER 关键字语法错误" },
            { "IM013", "跟踪文件错误" },
            { "S0001", "基表或视图已存在" },
            { "S0002", "未找到基表" },
            { "S0011", "索引已经存在" },
            { "S0012", "未找到索引" },
            { "S0021", "列已存在" },
            { "S0022", "未找到列" },
            { "S0023", "列无默认值" },
            { "S1000", "常规错误" },
            { "S1001", "内存分配失败" },
            { "S1002", "列编号无效" },
            { "S1003", "程序类型超出范围" },
            { "S1004", "SQL 数据类型超出范围" },
            { "S1008", "已取消操作" },
            { "S1009", "参数值无效" },
            { "S1010", "函数序列错误" },
            { "S1011", "操作在此时无效" },
            { "S1012", "所指定的事务操作代码无效" },
            { "S1015", "无可用的游标名称" },
            { "S1090", "字符串或缓冲区长度无效" },
            { "S1091", "描述符类型超出范围" },
            { "S1092", "选项类型超出范围" },
            { "S1093", "参数编号无效" },
            { "S1094", "小数位数值无效" },
            { "S1095", "函数类型超出范围" },
            { "S1096", "信息类型超出范围" },
            { "S1097", "列类型超出范围" },
            { "S1098", "作用域类型超出范围" },
            { "S1099", "可为空类型超出范围" },
            { "S1100", "唯一性选项类型超出范围" },
            { "S1101", "准确性选项类型超出范围" },
            { "S1103", "方向选项超出范围" },
            { "S1104", "精度值无效" },
            { "S1105", "参数类型无效" },
            { "S1106", "提取类型超出范围" },
            { "S1107", "行值超出范围" },
            { "S1108", "并发选项超出范围" },
            { "S1109", "游标位置无效" },
            { "S1110", "驱动程序完成无效" },
            { "S1111", "书签值无效" },
            { "S1C00", "驱动程序无法执行" },
            { "S1DE0", "执行值挂起时无数据" },
            { "S1T00", "超时失效" }
        };

        // ODBC 错误码 - 繁体中文
        private static readonly Dictionary<string, string> OdbcErrorsMapTraditionalChinese = new()
        {
            { "00000", "成功" },
            { "01000", "常規警告" },
            { "01002", "斷開連接錯誤" },
            { "01004", "數據被截斷" },
            { "01006", "未廢除特權" },
            { "01S00", "無效連接字符串特性" },
            { "01S01", "行中的錯誤" },
            { "01S02", "選項值已更改" },
            { "01S03", "未更新或刪除任何行" },
            { "01S04", "更新或刪除了多行" },
            { "01S05", "取消操作被當成 FreeStmt/Close" },
            { "01S06", "設法在結果返回第一個行集之前進行提取" },
            { "07001", "參數個數錯誤" },
            { "07006", "違反受限制的數據類型特性" },
            { "07S01", "默認參數使用無效" },
            { "08001", "無法連接到數據源" },
            { "08002", "連接正在使用" },
            { "08003", "連接未打開" },
            { "08004", "數據源拒絕建立連接" },
            { "08007", "在執行事務的過程中連接失敗" },
            { "08S01", "通訊鏈接失敗" },
            { "21S01", "插入值列表與列列表不匹配" },
            { "21S02", "派生表的程度與列列表不匹配" },
            { "22001", "字符串數據右截斷" },
            { "22002", "需要指示符變量，但未提供" },
            { "22003", "數字值超出範圍" },
            { "22005", "分配時出錯" },
            { "22008", "Datetime 字段溢出" },
            { "22012", "被零除錯誤" },
            { "22026", "字符串數據，長度不匹配" },
            { "23000", "違反完整性約束" },
            { "24000", "無效的游標狀態" },
            { "25000", "無效的事務狀態" },
            { "28000", "無效的授權規範" },
            { "34000", "無效的游標名稱" },
            { "37000", "語法錯誤或違規訪問" },
            { "3C000", "重複的游標名稱" },
            { "40001", "串行錯誤" },
            { "42000", "語法錯誤或違規訪問" },
            { "70100", "操作終止" },
            { "IM001", "驅動程序不支持本函數" },
            { "IM002", "未找到源名稱並且未指定默認驅動程序" },
            { "IM003", "無法裝載指定的驅動程序" },
            { "IM004", "驅動程序的 SQLAllocEnv 失敗" },
            { "IM005", "驅動程序的 SQLAllocConnect 失敗" },
            { "IM006", "驅動程序的 SQLSetConnectOption 失敗" },
            { "IM007", "未指定數據源或驅動程序；禁止對話" },
            { "IM008", "對話失敗" },
            { "IM009", "無法裝載轉換 DLL" },
            { "IM010", "數據源名稱過長" },
            { "IM011", "驅動程序名稱過長" },
            { "IM012", "DRIVER 關鍵字語法錯誤" },
            { "IM013", "跟蹤文件錯誤" },
            { "S0001", "基表或視圖已存在" },
            { "S0002", "未找到基表" },
            { "S0011", "索引已經存在" },
            { "S0012", "未找到索引" },
            { "S0021", "列已存在" },
            { "S0022", "未找到列" },
            { "S0023", "列無默認值" },
            { "S1000", "常規錯誤" },
            { "S1001", "內存分配失敗" },
            { "S1002", "列編號無效" },
            { "S1003", "程序類型超出範圍" },
            { "S1004", "SQL 數據類型超出範圍" },
            { "S1008", "已取消操作" },
            { "S1009", "參數值無效" },
            { "S1010", "函數序列錯誤" },
            { "S1011", "操作在此時無效" },
            { "S1012", "所指定的事務操作代碼無效" },
            { "S1015", "無可用的游標名稱" },
            { "S1090", "字符串或緩沖區長度無效" },
            { "S1091", "描述符類型超出範圍" },
            { "S1092", "選項類型超出範圍" },
            { "S1093", "參數編號無效" },
            { "S1094", "小數位數值無效" },
            { "S1095", "函數類型超出範圍" },
            { "S1096", "信息類型超出範圍" },
            { "S1097", "列類型超出範圍" },
            { "S1098", "作用域類型超出範圍" },
            { "S1099", "可為空類型超出範圍" },
            { "S1100", "唯一性選項類型超出範圍" },
            { "S1101", "準確性選項類型超出範圍" },
            { "S1103", "方向選項超出範圍" },
            { "S1104", "精度值無效" },
            { "S1105", "參數類型無效" },
            { "S1106", "提取類型超出範圍" },
            { "S1107", "行值超出範圍" },
            { "S1108", "並發選項超出範圍" },
            { "S1109", "游標位置無效" },
            { "S1110", "驅動程序完成無效" },
            { "S1111", "書簽值無效" },
            { "S1C00", "驅動程序無法執行" },
            { "S1DE0", "執行值掛起時無數據" },
            { "S1T00", "超時失效" }
        };

        // ODBC 错误码
        public static Dictionary<string, string> OdbcErrorsMap
        {
            get
            {
                return GlobalState.CurrentLanguageType switch
                {
                    LanguageType.SimplifiedChinese => OdbcErrorsMapSimplifiedChinese,
                    LanguageType.TraditionalChinese => OdbcErrorsMapTraditionalChinese,
                    _ => OdbcErrorsMapEnglish
                };
            }
        }
    }
}