namespace PersonalTools
{
    public static partial class ConstString
    {
        // MySQL 错误码 - 简体中文
        private static readonly Dictionary<long, string> MySqlErrorsMapSimplifiedChinese = new()
        {
            { 1, "操作不允许"},
            { 2, "没有这样的文件或目录"},
            { 3, "没有这样的进程"},
            { 4, "系统调用被中断"},
            { 5, "输入/输出错误"},
            { 6, "没有这样的设备或地址"},
            { 7, "参数列表过长"},
            { 8, "执行格式错误"},
            { 9, "错误的文件描述符"},
            { 10, "没有子进程"},
            { 11, "资源暂时不可用"},
            { 12, "无法分配内存"},
            { 13, "权限被拒绝"},
            { 14, "错误的地址"},
            { 15, "需要块设备"},
            { 16, "设备或资源忙"},
            { 17, "文件已存在"},
            { 18, "无效的跨设备链接"},
            { 19, "没有这样的设备"},
            { 20, "不是目录"},
            { 21, "是目录"},
            { 22, "无效参数"},
            { 23, "系统中打开文件过多"},
            { 24, "打开文件过多"},
            { 25, "设备的不适当ioctl操作"},
            { 26, "文本文件忙"},
            { 27, "文件过大"},
            { 28, "设备上没有剩余空间"},
            { 29, "非法寻址"},
            { 30, "只读文件系统"},
            { 31, "链接过多"},
            { 32, "管道破裂"},
            { 33, "数值参数超出定义域"},
            { 34, "数值结果超出范围"},
            { 35, "资源死锁已避免"},
            { 36, "文件名过长"},
            { 37, "没有可用的锁"},
            { 38, "功能未实现"},
            { 39, "目录非空"},
            { 40, "符号链接层级过多"},
            { 42, "没有所需类型的消息"},
            { 43, "标识符已移除"},
            { 44, "通道号超出范围"},
            { 45, "第2级未同步"},
            { 46, "第3级已停止"},
            { 47, "第3级已重置"},
            { 48, "链接号超出范围"},
            { 49, "协议驱动程序未附加"},
            { 50, "没有可用的CSI结构"},
            { 51, "第2级已停止"},
            { 52, "无效交换"},
            { 53, "无效请求描述符"},
            { 54, "交换已满"},
            { 55, "没有阳极"},
            { 56, "无效请求代码"},
            { 57, "无效插槽"},
            { 59, "错误的字体文件格式"},
            { 60, "设备不是流"},
            { 61, "没有可用数据"},
            { 62, "计时器已过期"},
            { 63, "流资源耗尽"},
            { 64, "机器不在网络上"},
            { 65, "包未安装"},
            { 66, "对象是远程的"},
            { 67, "链接已被切断"},
            { 68, "广告错误"},
            { 69, "挂载错误"},
            { 70, "发送时通信错误"},
            { 71, "协议错误"},
            { 72, "尝试多跳"},
            { 73, "RFS特定错误"},
            { 74, "错误消息"},
            { 75, "值对于定义的数据类型过大"},
            { 76, "网络上名称不唯一"},
            { 77, "文件描述符处于错误状态"},
            { 78, "远程地址已更改"},
            { 79, "无法访问所需的共享库"},
            { 80, "访问损坏的共享库"},
            { 81, "a.out中的.lib节损坏"},
            { 82, "尝试链接过多共享库"},
            { 83, "无法直接执行共享库"},
            { 84, "无效或不完整的多字节或宽字符"},
            { 85, "系统调用被中断应重新启动"},
            { 86, "流管道错误"},
            { 87, "用户过多"},
            { 88, "在非套接字上进行套接字操作"},
            { 89, "需要目标地址"},
            { 90, "消息过长"},
            { 91, "套接字的协议类型错误"},
            { 92, "协议不可用"},
            { 93, "协议不受支持"},
            { 94, "套接字类型不受支持"},
            { 95, "操作不受支持"},
            { 96, "协议族不受支持"},
            { 97, "协议不支持地址族"},
            { 98, "地址已在使用中"},
            { 99, "无法分配请求的地址"},
            { 100, "网络已关闭"},
            { 101, "网络不可达"},
            { 102, "网络在重置时断开连接"},
            { 103, "软件导致连接中止"},
            { 104, "对等方重置连接"},
            { 105, "没有可用的缓冲区空间"},
            { 106, "传输端点已连接"},
            { 107, "传输端点未连接"},
            { 108, "传输端点关闭后无法发送"},
            { 109, "引用过多：无法拼接"},
            { 110, "连接超时"},
            { 111, "连接被拒绝"},
            { 112, "主机已关闭"},
            { 113, "没有到主机的路由"},
            { 114, "操作已在进展中"},
            { 115, "操作现在在进展中"},
            { 116, "过时的文件句柄"},
            { 117, "结构需要清理"},
            { 118, "不是XENIX命名类型文件"},
            { 119, "没有可用的XENIX信号量"},
            { 120, "读取或更新时未找到键"},
            { 121, "写入或更新时键重复"},
            { 122, "处理程序中的内部（未指定）错误"},
            { 123, "自读取以来有人更改了行（当表被锁定以防止这种情况时）"},
            { 124, "给函数的索引错误"},
            { 125, "未定义的处理程序错误125"},
            { 126, "索引文件已损坏"},
            { 127, "记录文件已损坏"},
            { 128, "引擎内存不足"},
            { 129, "未定义的处理程序错误129"},
            { 130, "不正确的文件格式"},
            { 131, "数据库不支持的命令"},
            { 132, "旧的数据库文件"},
            { 133, "更新前未读取记录"},
            { 134, "记录已被删除（或记录文件已损坏）"},
            { 135, "记录文件中没有更多空间"},
            { 136, "索引文件中没有更多空间"},
            { 137, "没有更多记录（在文件末尾后读取）"},
            { 138, "表使用了不支持的扩展"},
            { 139, "行过大"},
            { 140, "错误的创建选项"},
            { 141, "写入或更新时唯一键或约束重复"},
            { 142, "表中使用了未知字符集"},
            { 143, "MERGE表的子表中存在冲突的表定义"},
            { 144, "表已损坏且上次修复失败"},
            { 145, "表被标记为已损坏应进行修复"},
            { 146, "锁超时；重试事务"},
            { 147, "锁表已满；使用更大的锁表重新启动程序"},
            { 148, "只读事务下不允许更新"},
            { 149, "锁死锁；重试事务"},
            { 150, "外键约束格式不正确"},
            { 151, "无法添加子行"},
            { 152, "无法删除父行"},
            { 153, "没有该名称的保存点"},
            { 154, "非唯一键块大小"},
            { 155, "引擎中不存在该表"},
            { 156, "存储引擎中已存在该表"},
            { 157, "无法连接到存储引擎"},
            { 158, "使用空间索引时发现意外的空指针"},
            { 159, "存储引擎中的表已更改"},
            { 160, "表中没有给定值的分区"},
            { 161, "基于行的二进制日志记录失败"},
            { 162, "外键约束中需要索引"},
            { 163, "维护外键约束将导致其他表中的重复键错误"},
            { 164, "表需要升级才能使用"},
            { 165, "表是只读的"},
            { 166, "获取下一个自增值失败"},
            { 167, "设置行自增值失败"},
            { 168, "引擎的未知（通用）错误"},
            { 169, "记录相同"},
            { 170, "无法记录此语句"},
            { 171, "事件已损坏导致读取非法数据"},
            { 172, "表是此版本不支持的新格式"},
            { 173, "事件无法处理没有其他处理程序错误发生"},
            { 174, "处理程序初始化期间发生致命错误"},
            { 175, "文件过短；预期文件中更多数据"},
            { 176, "读取校验和错误的页面"},
            { 177, "活动并发事务过多"},
            { 178, "记录与给定的分区集不匹配"},
            { 179, "索引列长度超出限制"},
            { 180, "索引已损坏"},
            { 181, "撤销记录过大"},
            { 182, "无效的InnoDB FTS文档ID"},
            { 183, "表正在用于外键检查"},
            { 184, "表空间已存在"},
            { 185, "列过多"},
            { 186, "行在错误的分区中"},
            { 187, "InnoDB处于只读模式"},
            { 188, "FTS查询超出结果缓存内存限制"},
            { 189, "临时文件写入失败"},
            { 190, "当innodb_forced_recovery > 0时不允许操作"},
            { 191, "FTS短语或邻近搜索中的单词过多"},
            { 1000, "ER_HASHCHK: hashchk"},
            { 1001, "ER_NISAMCHK: isamchk"},
            { 1002, "ER_NO: 否"},
            { 1003, "ER_YES: 是"},
            { 1004, "ER_CANT_CREATE_FILE: 无法创建文件'%-.200s'(错误号: %d - %s)"},
            { 1005, "ER_CANT_CREATE_TABLE: 无法创建表'%-.200s' (错误号: %d)"},
            { 1006, "ER_CANT_CREATE_DB: 无法创建数据库'%-.192s' (错误号: %d)"},
            { 1007, "ER_DB_CREATE_EXISTS: 无法创建数据库'%-.192s'；数据库已存在"},
            { 1008, "ER_DB_DROP_EXISTS: 无法删除数据库'%-.192s'；数据库不存在"},
            { 1009, "ER_DB_DROP_DELETE: 删除数据库错误（无法删除'%-.192s'，错误号: %d)"},
            { 1010, "ER_DB_DROP_RMDIR: 删除数据库错误（无法删除目录'%-.192s'，错误号: %d)"},
            { 1011, "ER_CANT_DELETE_FILE: 删除'%-.192s'时出错（错误号: %d - %s)"},
            { 1012, "ER_CANT_FIND_SYSTEM_REC: 无法读取系统表中的记录"},
            { 1013, "ER_CANT_GET_STAT: 无法获取'%-.200s'的状态（错误号: %d - %s)"},
            { 1014, "ER_CANT_GET_WD: 无法获取工作目录（错误号: %d - %s)"},
            { 1015, "ER_CANT_LOCK: 无法锁定文件（错误号: %d - %s)"},
            { 1016, "ER_CANT_OPEN_FILE: 无法打开文件: '%-.200s' (错误号: %d - %s)"},
            { 1017, "ER_FILE_NOT_FOUND: 找不到文件: '%-.200s' (错误号: %d - %s)"},
            { 1018, "ER_CANT_READ_DIR: 无法读取'%-.192s'的目录（错误号: %d - %s)"},
            { 1019, "ER_CANT_SET_WD: 无法更改目录到'%-.192s'（错误号: %d - %s)"},
            { 1020, "ER_CHECKREAD: 自上次读取以来记录已在表'%-.192s'中更改"},
            { 1021, "ER_DISK_FULL: 磁盘已满（%s）；等待有人释放一些空间...（错误号: %d - %s)"},
            { 1022, "ER_DUP_KEY: 无法写入；表'%-.192s'中的键重复"},
            { 1023, "ER_ERROR_ON_CLOSE: 关闭'%-.192s'时出错（错误号: %d - %s)"},
            { 1024, "ER_ERROR_ON_READ: 读取文件'%-.200s'时出错（错误号: %d - %s)"},
            { 1025, "ER_ERROR_ON_RENAME: 重命名'%-.210s'为'%-.210s'时出错（错误号: %d - %s)"},
            { 1026, "ER_ERROR_ON_WRITE: 写入文件'%-.200s'时出错（错误号: %d - %s)"},
            { 1027, "ER_FILE_USED: '%-.192s'被锁定以防止更改"},
            { 1028, "ER_FILSORT_ABORT: 排序已中止"},
            { 1029, "ER_FORM_NOT_FOUND: 视图'%-.192s'不存在于'%-.192s'"},
            { 1030, "ER_GET_ERRNO: 从存储引擎收到错误%d"},
            { 1031, "ER_ILLEGAL_HA: 表'%-.192s'的存储引擎没有此选项"},
            { 1032, "ER_KEY_NOT_FOUND: 在'%-.192s'中找不到记录"},
            { 1033, "ER_NOT_FORM_FILE: 文件'%-.200s'中的信息不正确"},
            { 1034, "ER_NOT_KEYFILE: 表'%-.200s'的键文件不正确；尝试修复它"},
            { 1035, "ER_OLD_KEYFILE: 表'%-.192s'的旧键文件；修复它！"},
            { 1036, "ER_OPEN_AS_READONLY: 表'%-.192s'是只读的"},
            { 1037, "ER_OUTOFMEMORY: 内存不足；重启服务器并重试（需要%d字节）"},
            { 1038, "ER_OUT_OF_SORTMEMORY: 排序内存不足，考虑增加服务器排序缓冲区大小"},
            { 1039, "ER_UNEXPECTED_EOF: 读取文件'%-.192s'时发现意外的EOF（错误号: %d - %s)"},
            { 1040, "ER_CON_COUNT_ERROR: 连接过多"},
            { 1041, "ER_OUT_OF_RESOURCES: 内存不足；检查mysqld或其他进程是否使用了所有可用内存；如果没有，您可能需要使用'ulimit'允许mysqld使用更多内存或添加更多交换空间"},
            { 1042, "ER_BAD_HOST_ERROR: 无法获取您地址的主机名"},
            { 1043, "ER_HANDSHAKE_ERROR: 握手错误"},
            { 1044, "ER_DBACCESS_DENIED_ERROR: 用户'%-.48s'@'%-.64s'对数据库'%-.192s'的访问被拒绝"},
            { 1045, "ER_ACCESS_DENIED_ERROR: 用户'%-.48s'@'%-.64s'的访问被拒绝（使用密码: %s)"},
            { 1046, "ER_NO_DB_ERROR: 未选择数据库"},
            { 1047, "ER_UNKNOWN_COM_ERROR: 未知命令"},
            { 1048, "ER_BAD_NULL_ERROR: 列'%-.192s'不能为null"},
            { 1049, "ER_BAD_DB_ERROR: 未知数据库'%-.192s'"},
            { 1050, "ER_TABLE_EXISTS_ERROR: 表'%-.192s'已存在"},
            { 1051, "ER_BAD_TABLE_ERROR: 未知表'%-.100s'"},
            { 1052, "ER_NON_UNIQ_ERROR: 列'%-.192s'在%-.192s中不明确"},
            { 1053, "ER_SERVER_SHUTDOWN: 服务器正在关闭"},
            { 1054, "ER_BAD_FIELD_ERROR: 在'%-.192s'中未知列'%-.192s'"},
            { 1055, "ER_WRONG_FIELD_WITH_GROUP: '%-.192s'不在GROUP BY中"},
            { 1056, "ER_WRONG_GROUP_FIELD: 无法在'%-.192s'上分组"},
            { 1057, "ER_WRONG_SUM_SELECT: 语句在同一语句中有求和函数和列"},
            { 1058, "ER_WRONG_VALUE_COUNT: 列计数与值计数不匹配"},
            { 1059, "ER_TOO_LONG_IDENT: 标识符名称'%-.100s'过长"},
            { 1060, "ER_DUP_FIELDNAME: 重复的列名'%-.192s'"},
            { 1061, "ER_DUP_KEYNAME: 重复的键名'%-.192s'"},
            { 1062, "ER_DUP_ENTRY: 键%d的重复条目'%-.192s'"},
            { 1063, "ER_WRONG_FIELD_SPEC: 列'%-.192s'的列说明符不正确"},
            { 1064, "ER_PARSE_ERROR: %s 在'%-.80s'附近，第%d行"},
            { 1065, "ER_EMPTY_QUERY: 查询为空"},
            { 1066, "ER_NONUNIQ_TABLE: 不唯一的表/别名: '%-.192s'"},
            { 1067, "ER_INVALID_DEFAULT: '%-.192s'的默认值无效"},
            { 1068, "ER_MULTIPLE_PRI_KEY: 定义了多个主键"},
            { 1069, "ER_TOO_MANY_KEYS: 指定的键过多；最多允许%d个键"},
            { 1070, "ER_TOO_MANY_KEY_PARTS: 指定的键部分过多；最多允许%d个部分"},
            { 1071, "ER_TOO_LONG_KEY: 指定的键过长；最大键长度为%d字节"},
            { 1072, "ER_KEY_COLUMN_DOES_NOT_EXITS: 键列'%-.192s'在表中不存在"},
            { 1073, "ER_BLOB_USED_AS_KEY: BLOB列'%-.192s'不能在使用表类型的键规范中使用"},
            { 1074, "ER_TOO_BIG_FIELDLENGTH: 列'%-.192s'的列长度过大（最大 = %lu）；请改用BLOB或TEXT"},
            { 1075, "ER_WRONG_AUTO_KEY: 不正确的表定义；只能有一个自动列且必须定义为键"},
            { 1076, "ER_READY: %s: 准备连接。版本: '%s'套接字: '%s'端口: %d"},
            { 1077, "ER_NORMAL_SHUTDOWN: %s: 正常关闭"},
            { 1078, "ER_GOT_SIGNAL: %s: 收到信号%d。正在中止！"},
            { 1079, "ER_SHUTDOWN_COMPLETE: %s: 关闭完成"},
            { 1080, "ER_FORCING_CLOSE: %s: 强制关闭线程%ld用户: '%-.48s'"},
            { 1081, "ER_IPSOCK_ERROR: 无法创建IP套接字"},
            { 1082, "ER_NO_SUCH_INDEX: 表'%-.192s'没有像CREATE INDEX中使用的索引；重新创建表"},
            { 1083, "ER_WRONG_FIELD_TERMINATORS: 字段分隔符参数不是预期的；请检查手册"},
            { 1084, "ER_BLOBS_AND_NO_TERMINATED: 不能将固定行长度与BLOB一起使用；请使用'fields terminated by'"},
            { 1085, "ER_TEXTFILE_NOT_READABLE: 文件'%-.128s'必须在数据库目录中或对所有用户可读"},
            { 1086, "ER_FILE_EXISTS_ERROR: 文件'%-.200s'已存在"},
            { 1087, "ER_LOAD_INFO: 记录: %ld 已删除: %ld 已跳过: %ld 警告: %ld"},
            { 1088, "ER_ALTER_INFO: 记录: %ld 重复: %ld"},
            { 1089, "ER_WRONG_SUB_KEY: 不正确的前缀键；使用的键部分不是字符串，使用的长度长于键部分，或者存储引擎不支持唯一前缀键"},
            { 1090, "ER_CANT_REMOVE_ALL_FIELDS: 不能使用ALTER TABLE删除所有列；请改用DROP TABLE"},
            { 1091, "ER_CANT_DROP_FIELD_OR_KEY: 无法DROP'%-.192s'；检查列/键是否存在"},
            { 1092, "ER_INSERT_INFO: 记录: %ld 重复: %ld 警告: %ld"},
            { 1093, "ER_UPDATE_TABLE_USED: 不能在FROM子句中为更新指定目标表'%-.192s'"},
            { 1094, "ER_NO_SUCH_THREAD: 未知线程ID: %lu"},
            { 1095, "ER_KILL_DENIED_ERROR: 您不是线程%lu的所有者"},
            { 1096, "ER_NO_TABLES_USED: 未使用表"},
            { 1097, "ER_TOO_BIG_SET: 列%-.192s和SET的字符串过多"},
            { 1098, "ER_NO_UNIQUE_LOGFILE: 无法生成唯一的日志文件名%-.200s.(1-999)"},
            { 1099, "ER_TABLE_NOT_LOCKED_FOR_WRITE: 表'%-.192s'已用READ锁锁定，无法更新"},
            { 1100, "ER_TABLE_NOT_LOCKED: 表'%-.192s'未用LOCK TABLES锁定"},
            { 1101, "ER_BLOB_CANT_HAVE_DEFAULT: BLOB/TEXT列'%-.192s'不能有默认值"},
            { 1102, "ER_WRONG_DB_NAME: 不正确的数据库名称'%-.100s'"},
            { 1103, "ER_WRONG_TABLE_NAME: 不正确的表名称'%-.100s'"},
            { 1104, "ER_TOO_BIG_SELECT: SELECT将检查超过MAX_JOIN_SIZE的行；检查您的WHERE并使用SET SQL_BIG_SELECTS=1或SET MAX_JOIN_SIZE=#如果SELECT正常"},
            { 1105, "ER_UNKNOWN_ERROR: 未知错误"},
            { 1106, "ER_UNKNOWN_PROCEDURE: 未知过程'%-.192s'"},
            { 1107, "ER_WRONG_PARAMCOUNT_TO_PROCEDURE: 过程'%-.192s'的参数计数不正确"},
            { 1108, "ER_WRONG_PARAMETERS_TO_PROCEDURE: 过程'%-.192s'的参数不正确"},
            { 1109, "ER_UNKNOWN_TABLE: 在%-.32s中未知表'%-.192s'"},
            { 1110, "ER_FIELD_SPECIFIED_TWICE: 列'%-.192s'被指定了两次"},
            { 1111, "ER_INVALID_GROUP_FUNC_USE: 分组函数的无效使用"},
            { 1112, "ER_UNSUPPORTED_EXTENSION: 表'%-.192s'使用了此MySQL版本中不存在的扩展"},
            { 1113, "ER_TABLE_MUST_HAVE_COLUMNS: 表必须至少有一列"},
            { 1114, "ER_RECORD_FILE_FULL: 表'%-.192s'已满"},
            { 1115, "ER_UNKNOWN_CHARACTER_SET: 未知字符集: '%-.64s'"},
            { 1116, "ER_TOO_MANY_TABLES: 表过多; MySQL只能在一个查询中使用%d个表"},
            { 1117, "ER_TOO_MANY_FIELDS: 列过多"},
            { 1118, "ER_TOO_BIG_ROWSIZE: 行大小过大。表'%-.192s'的最大行大小(不包括BLOB)是%lu。您必须将某些列更改为TEXT或BLOB"},
            { 1119, "ER_STACK_OVERRUN: 线程堆栈溢出: 已使用: %ld堆栈的%d。如果需要，请使用'mysqld --thread_stack=#'指定更大的堆栈"},
            { 1120, "ER_WRONG_OUTER_JOIN: 在OUTER JOIN中发现交叉依赖; 检查您的ON条件"},
            { 1121, "ER_NULL_COLUMN_IN_INDEX: 表'%-.192s'的列'%-.192s'用于键规范而没有NOT NULL标志"},
            { 1122, "ER_CANT_FIND_UDF: 无法加载函数'%-.192s'"},
            { 1123, "ER_CANT_INITIALIZE_UDF: 无法初始化函数'%-.192s'; %s"},
            { 1124, "ER_UDF_NO_PATHS: 不允许UDF的路径"},
            { 1125, "ER_UDF_EXISTS: 函数'%-.192s'已存在"},
            { 1126, "ER_CANT_OPEN_LIBRARY: 无法打开共享库'%-.192s'(错误号: %d %s)"},
            { 1127, "ER_CANT_FIND_DL_ENTRY: 无法在库中找到符号'%-.192s'"},
            { 1128, "ER_FUNCTION_NOT_DEFINED: 函数'%-.192s'未定义"},
            { 1129, "ER_HOST_IS_BLOCKED: 主机'%-.64s'被阻塞，因为有许多连接错误; 使用'mysqladmin flush-hosts'解除阻塞"},
            { 1130, "ER_HOST_NOT_PRIVILEGED: 主机'%-.64s'不允许连接到此MySQL服务器"},
            { 1131, "ER_PASSWORD_ANONYMOUS_USER: 您正在使用MySQL作为匿名用户，不允许匿名用户更改密码"},
            { 1132, "ER_PASSWORD_NOT_ALLOWED: 您必须有更新mysql数据库中表的权限才能更改密码"},
            { 1133, "ER_PASSWORD_NO_MATCH: 无法在用户表中找到任何匹配的行"},
            { 1134, "ER_UPDATE_INFO: 匹配的行: %ld已更改: %ld警告: %ld"},
            { 1135, "ER_CANT_CREATE_THREAD: 无法创建新线程(错误号%d); 如果您没有可用内存，可以查阅手册以获取可能的操作系统相关错误"},
            { 1136, "ER_WRONG_VALUE_COUNT_ON_ROW: 第%ld行的列计数与值计数不匹配"},
            { 1137, "ER_CANT_REOPEN_TABLE: 无法重新打开表: '%-.192s'"},
            { 1138, "ER_INVALID_USE_OF_NULL: '%-.192s'的无效NULL使用"},
            { 1139, "ER_REGEXP_ERROR: 从正则表达式得到错误"},
            { 1140, "ER_MIX_OF_GROUP_FUNC_AND_FIELDS: 在没有GROUP BY的聚合查询中，列'%-.192s'的混合使用是非法的"},
            { 1141, "ER_NONEXISTING_GRANT: 用户'%-.48s'@'%-.64s'对数据库'%-.192s'没有这样的权限"},
            { 1142, "ER_TABLEACCESS_DENIED_ERROR: 用户'%-.48s'@'%-.64s'对表'%-.192s'的%s命令被拒绝"},
            { 1143, "ER_COLUMNACCESS_DENIED_ERROR: 用户'%-.48s'@'%-.64s'对表'%-.192s'的列'%-.192s'的%s命令被拒绝"},
            { 1144, "ER_ILLEGAL_GRANT_FOR_TABLE: 表'%-.192s'的非法GRANT/REVOKE命令"},
            { 1145, "ER_GRANT_WRONG_HOST_OR_USER: GRANT主机或用户参数错误"},
            { 1146, "ER_NO_SUCH_TABLE: 表'%-.192s'.'%-.192s'不存在"},
            { 1147, "ER_NONEXISTING_TABLE_GRANT: 用户'%-.48s'@'%-.64s'对表'%-.192s'.'%-.192s'没有这样的权限"},
            { 1148, "ER_NOT_ALLOWED_COMMAND: 此MySQL版本不允许使用的命令"},
            { 1149, "ER_SYNTAX_ERROR: 您有语法错误; 请查阅与您的MySQL服务器版本对应的手册，以了解在'%-.80s'附近使用的正确语法"},
            { 1150, "ER_DELAYED_CANT_CHANGE_LOCK: 延迟插入线程无法获得请求的表的锁"},
            { 1151, "ER_TOO_MANY_DELAYED_THREADS: 延迟线程过多"},
            { 1152, "ER_ABORTING_CONNECTION: 中止连接%ld到数据库: '%-.192s'用户: '%-.48s'(%s)"},
            { 1153, "ER_NET_PACKET_TOO_LARGE: 获得大于'max_allowed_packet'字节的数据包"},
            { 1154, "ER_NET_READ_ERROR_FROM_PIPE: 从连接管道读取错误"},
            { 1155, "ER_NET_FCNTL_ERROR: 从网络获取fctnl错误"},
            { 1156, "ER_NET_PACKETS_OUT_OF_ORDER: 从网络获得无序的数据包"},
            { 1157, "ER_NET_UNCOMPRESS_ERROR: 无法解压缩通信数据包"},
            { 1158, "ER_NET_READ_ERROR: 读取通信数据包时出错"},
            { 1159, "ER_NET_READ_INTERRUPTED: 读取通信数据包超时"},
            { 1160, "ER_NET_ERROR_ON_WRITE: 写入通信数据包时出错"},
            { 1161, "ER_NET_WRITE_INTERRUPTED: 写入通信数据包超时"},
            { 1162, "ER_TOO_LONG_STRING: 结果字符串长于'max_allowed_packet'字节"},
            { 1163, "ER_TABLE_CANT_HANDLE_BLOB: 使用的表类型不支持BLOB/TEXT列"},
            { 1164, "ER_TABLE_CANT_HANDLE_AUTO_INCREMENT: 使用的表类型不支持AUTO_INCREMENT列"},
            { 1165, "ER_DELAYED_INSERT_TABLE_LOCKED: INSERT DELAYED无法使用，因为表被锁定"},
            { 1166, "ER_WRONG_COLUMN_NAME: 不正确的列名'%-.100s'"},
            { 1167, "ER_WRONG_KEY_COLUMN: 使用的存储引擎无法索引列'%-.192s'"},
            { 1168, "ER_WRONG_MRG_TABLE: 无法打开定义不同的表，或非MyISAM类型，或不存在"},
            { 1169, "ER_DUP_UNIQUE: 由于唯一约束，无法写入表'%-.192s'"},
            { 1170, "ER_BLOB_KEY_WITHOUT_LENGTH: BLOB/TEXT列'%-.192s'在键规范中使用而没有键长度"},
            { 1171, "ER_PRIMARY_CANT_HAVE_NULL: 所有主键部分必须是NOT NULL; 如果需要NULL键，请改用UNIQUE索引"},
            { 1172, "ER_TOO_MANY_ROWS: 结果包含多于一行"},
            { 1173, "ER_REQUIRES_PRIMARY_KEY: 此表类型需要主键"},
            { 1174, "ER_NO_RAID_COMPILED: 此MySQL版本未使用RAID支持编译"},
            { 1175, "ER_UPDATE_WITHOUT_KEY_IN_SAFE_MODE: 您正在使用安全更新模式，并且您尝试更新没有使用键的WHERE的表"},
            { 1176, "ER_KEY_DOES_NOT_EXITS: 键'%-.192s'在表'%-.192s'中不存在"},
            { 1177, "ER_CHECK_NO_SUCH_TABLE: 无法打开表"},
            { 1178, "ER_CHECK_NOT_IMPLEMENTED: 表的存储引擎不支持%s"},
            { 1179, "ER_CANT_DO_THIS_DURING_AN_TRANSACTION: 您不能在事务中执行此命令"},
            { 1180, "ER_ERROR_DURING_COMMIT: 提交期间出错%d - %s"},
            { 1181, "ER_ERROR_DURING_ROLLBACK: 回滚期间出错%d - %s"},
            { 1182, "ER_ERROR_DURING_FLUSH_LOGS: 刷新日志期间出错%d"},
            { 1183, "ER_ERROR_DURING_CHECKPOINT: 检查点期间出错%d"},
            { 1184, "ER_NEW_ABORTING_CONNECTION: 中止连接%ld到数据库: '%-.192s'用户: '%-.48s'主机: '%-.64s'(%s)"},
            { 1185, "ER_DUMP_NOT_IMPLEMENTED: 表的存储引擎不支持二进制表转储"},
            { 1186, "ER_FLUSH_MASTER_BINLOG_CLOSED: 由于主二进制日志关闭，Binlog转储失败"},
            { 1187, "ER_INDEX_REBUILD: 重新构建转储表的索引失败"},
            { 1188, "ER_MASTER: 来自主服务器的错误: '%-.64s'"},
            { 1189, "ER_MASTER_NET_READ: 从主服务器网络读取错误"},
            { 1190, "ER_MASTER_NET_WRITE: 网络写入主服务器错误"},
            { 1191, "ER_FT_MATCHING_KEY_NOT_FOUND: 无法找到与列列表匹配的FULLTEXT索引"},
            { 1192, "ER_LOCK_OR_ACTIVE_TRANSACTION: 无法执行给定的命令，因为您有活动的锁定表或活动的事务"},
            { 1193, "ER_UNKNOWN_SYSTEM_VARIABLE: 未知系统变量'%-.64s'"},
            { 1194, "ER_CRASHED_ON_USAGE: 表'%-.192s'被标记为已崩溃，应进行修复"},
            { 1195, "ER_CRASHED_ON_REPAIR: 表'%-.192s'被标记为已崩溃，上次修复失败"},
            { 1196, "ER_WARNING_NOT_COMPLETE_ROLLBACK: 某些非事务性更改的表无法回滚"},
            { 1197, "ER_TRANS_CACHE_FULL: 多语句事务需要超过'max_binlog_cache_size'字节的存储空间; 增加此mysqld变量并重试"},
            { 1198, "ER_SLAVE_MUST_STOP: 此操作无法在运行中的从服务器上执行; 先运行STOP SLAVE"},
            { 1199, "ER_SLAVE_NOT_RUNNING: 此操作需要运行中的从服务器; 配置从服务器并启动SLAVE"},
            { 1200, "ER_BAD_SLAVE: 服务器未配置为从服务器; 在配置文件中修复此问题或使用CHANGE MASTER TO"},
            { 1201, "ER_MASTER_INFO: 无法初始化主服务器信息结构; 更多错误消息可以在MySQL错误日志中找到"},
            { 1202, "ER_SLAVE_THREAD: 无法创建从服务器线程; 检查系统资源"},
            { 1203, "ER_TOO_MANY_USER_CONNECTIONS: 用户%-.64s已超过'max_user_connections'资源"},
            { 1204, "ER_SET_CONSTANTS_ONLY: 您只能使用SET设置常量表达式"},
            { 1205, "ER_LOCK_WAIT_TIMEOUT: 锁等待超时; 尝试重新启动事务"},
            { 1206, "ER_LOCK_TABLE_FULL: 锁表已满; 使用更大的锁表重新启动程序"},
            { 1207, "ER_READ_ONLY_TRANSACTION: 在只读事务下不允许更新"},
            { 1208, "ER_DROP_DB_WITH_READ_LOCK: 当线程持有全局读锁时，不允许DROP DATABASE"},
            { 1209, "ER_CREATE_DB_WITH_READ_LOCK: 当线程持有全局读锁时，不允许CREATE DATABASE"},
            { 1210, "ER_WRONG_ARGUMENTS: 传递给%s的参数不正确"},
            { 1211, "ER_NO_PERMISSION_TO_CREATE_USER: 不允许创建'%-.48s'@'%-.64s'用户"},
            { 1212, "ER_UNION_TABLES_IN_DIFFERENT_DIR: 不正确的表定义; 所有MERGE表必须在同一个数据库中"},
            { 1213, "ER_LOCK_DEADLOCK: 死锁发现时尝试获取锁; 尝试重新启动事务"},
            { 1214, "ER_TABLE_CANT_HANDLE_FT: 使用的表类型不支持FULLTEXT索引"},
            { 1215, "ER_CANNOT_ADD_FOREIGN: 无法添加外键约束"},
            { 1216, "ER_NO_REFERENCED_ROW: 无法添加或更新子行: 外键约束失败"},
            { 1217, "ER_ROW_IS_REFERENCED: 无法删除或更新父行: 外键约束失败"},
            { 1218, "ER_CONNECT_TO_MASTER: 连接到主服务器时出错: %s"},
            { 1219, "ER_QUERY_ON_MASTER: 在主服务器上执行查询时出错: %s"},
            { 1220, "ER_ERROR_WHEN_EXECUTING_COMMAND: 执行命令%s时出错: %s"},
            { 1221, "ER_WRONG_USAGE: %s和%s的错误用法"},
            { 1222, "ER_WRONG_NUMBER_OF_COLUMNS_IN_SELECT: 使用的SELECT语句具有不同的列数"},
            { 1223, "ER_CANT_UPDATE_WITH_READLOCK: 无法执行查询，因为您有活动的读锁"},
            { 1224, "ER_MIXING_NOT_ALLOWED: 不允许混合事务性表和非事务性表"},
            { 1225, "ER_DUP_ARGUMENT: 选项'%s'使用了两次在语句中"},
            { 1226, "ER_USER_LIMIT_REACHED: 用户'%-.64s'已超过'%s'资源(当前值: %ld)"},
            { 1227, "ER_SPECIFIC_ACCESS_DENIED_ERROR: 访问被拒绝; 您需要(至少一个)%s权限才能执行此操作"},
            { 1228, "ER_LOCAL_VARIABLE: 变量'%-.64s'是SESSION变量，不能与SET GLOBAL一起使用"},
            { 1229, "ER_GLOBAL_VARIABLE: 变量'%-.64s'是GLOBAL变量，应使用SET GLOBAL设置"},
            { 1230, "ER_NO_DEFAULT: 变量'%-.64s'没有默认值"},
            { 1231, "ER_WRONG_VALUE_FOR_VAR: 变量'%-.64s'不能设置为值'%-.200s'"},
            { 1232, "ER_WRONG_TYPE_FOR_VAR: 变量'%-.64s'的参数类型不正确"},
            { 1233, "ER_VAR_CANT_BE_READ: 变量'%-.64s'只能设置，不能读取"},
            { 1234, "ER_CANT_USE_OPTION_HERE: 此处不允许使用'%s'选项"},
            { 1235, "ER_NOT_SUPPORTED_YET: 此MySQL版本尚不支持'%s'"},
            { 1236, "ER_MASTER_FATAL_ERROR_READING_BINLOG: 从二进制日志读取数据时，主服务器发生致命错误: %s"},
            { 1237, "ER_SLAVE_IGNORED_TABLE: 从服务器SQL线程忽略查询，因为已设置replicate-*-table规则"},
            { 1238, "ER_INCORRECT_GLOBAL_LOCAL_VAR: 变量'%-.64s'是%s变量"},
            { 1239, "ER_WRONG_FK_DEF: 外键定义不正确: %s"},
            { 1240, "ER_KEY_REF_DO_NOT_MATCH_TABLE_REF: 键引用和表引用不匹配"},
            { 1241, "ER_OPERAND_COLUMNS: 操作数应包含%d列"},
            { 1242, "ER_SUBQUERY_NO_1_ROW: 子查询返回多于1行"},
            { 1243, "ER_UNKNOWN_STMT_HANDLER: 未知的准备语句处理程序(%.*s)给定给%s"},
            { 1244, "ER_CORRUPT_HELP_DB: 帮助数据库已损坏或不存在"},
            { 1245, "ER_CYCLIC_REFERENCE: 循环引用"},
            { 1246, "ER_AUTO_CONVERT: 将列'%-.192s'从%s转换为%s"},
            { 1247, "ER_ILLEGAL_REFERENCE: 引用'%-.64s'不被支持(%s)"},
            { 1248, "ER_DERIVED_MUST_HAVE_ALIAS: 每个派生表必须有自己的别名"},
            { 1249, "ER_SELECT_REDUCED: 选择%d在优化期间被减少"},
            { 1250, "ER_TABLENAME_NOT_ALLOWED_HERE: 表'%-.100s'来自其中一个SELECT，不能在%s中使用"},
            { 1251, "ER_NOT_SUPPORTED_AUTH_MODE: 客户端不支持服务器请求的身份验证协议; 考虑升级MySQL客户端"},
            { 1252, "ER_SPATIAL_CANT_HAVE_NULL: 空间索引的所有部分必须是NOT NULL"},
            { 1253, "ER_COLLATION_CHARSET_MISMATCH: 排序规则'%-.64s'对字符集'%-.64s'无效"},
            { 1254, "ER_SLAVE_WAS_RUNNING: 从服务器已在运行"},
            { 1255, "ER_SLAVE_WAS_NOT_RUNNING: 从服务器未运行"},
            { 1256, "ER_TOO_BIG_FOR_UNCOMPRESS: 未压缩的数据过大; 最大大小为%d(可能，未压缩数据的长度已损坏)"},
            { 1257, "ER_ZLIB_Z_MEM_ERROR: ZLIB: 内存不足"},
            { 1258, "ER_ZLIB_Z_BUF_ERROR: ZLIB: 输出缓冲区不足(可能，未压缩数据的长度已损坏)"},
            { 1259, "ER_ZLIB_Z_DATA_ERROR: ZLIB: 输入数据已损坏"},
            { 1260, "ER_CUT_VALUE_GROUP_CONCAT: 行%ld被GROUP_CONCAT()截断"},
            { 1261, "ER_WARN_TOO_FEW_RECORDS: 行%ld不包含所有列的数据"},
            { 1262, "ER_WARN_TOO_MANY_RECORDS: 行%ld被截断; 它包含的数据多于输入列"},
            { 1263, "ER_WARN_NULL_TO_NOTNULL: 列设置为默认值; 在行%ld为NULL提供给NOT NULL列"},
            { 1264, "ER_WARN_DATA_OUT_OF_RANGE: 行%ld的列数据超出范围"},
            { 1265, "WARN_DATA_TRUNCATED: 行%ld的数据被截断"},
            { 1266, "ER_WARN_USING_OTHER_HANDLER: 对表'%-.192s'使用存储引擎%s"},
            { 1267, "ER_CANT_AGGREGATE_2COLLATIONS: 操作'%s'的非法混合排序规则(%s,%s)和(%s,%s)"},
            { 1268, "ER_DROP_USER: 无法删除一个或多个请求的用户"},
            { 1269, "ER_REVOKE_GRANTS: 无法撤销一个或多个请求用户的权限"},
            { 1270, "ER_CANT_AGGREGATE_3COLLATIONS: 操作'%s'的非法混合排序规则(%s,%s)、(%s,%s)和(%s,%s)"},
            { 1271, "ER_CANT_AGGREGATE_NCOLLATIONS: 操作'%s'的非法混合排序规则"},
            { 1272, "ER_VARIABLE_IS_NOT_STRUCT: 变量'%-.64s'不是变量组件(不能用作XXXX.variable_name)"},
            { 1273, "ER_UNKNOWN_COLLATION: 未知排序规则: '%-.64s'"},
            { 1274, "ER_SLAVE_IGNORED_SSL_PARAMS: SSL参数在CHANGE MASTER中被忽略，因为此MySQL从服务器是在不支持SSL的情况下编译的; 它们可以在以后使用"},
            { 1275, "ER_SERVER_IS_IN_SECURE_AUTH_MODE: 服务器正在运行--secure-auth模式，但'%-.64s'@'%-.64s'有旧格式密码; 请将密码更改为新格式"},
            { 1276, "ER_WARN_FIELD_RESOLVED: 字段或引用'%-.64s%s%-.64s%s%-.64s'在SELECT中解析为'%-.64s%s%-.64s%s%-.64s'"},
            { 1277, "ER_BAD_SLAVE_UNTIL_COND: 不正确的参数或参数组合用于START SLAVE UNTIL"},
            { 1278, "ER_MISSING_SKIP_SLAVE: 执行START SLAVE UNTIL时建议使用SKIP_SLAVE_COUNTER选项，但未指定"},
            { 1279, "ER_UNTIL_COND_IGNORED: SQL线程未启动，因此UNTIL选项被忽略"},
            { 1280, "ER_WRONG_NAME_FOR_INDEX: 索引名称'%-.64s'不正确"},
            { 1281, "ER_WRONG_NAME_FOR_CATALOG: 目录名称'%-.64s'不正确"},
            { 1282, "ER_WARN_QC_RESIZE: 查询缓存未能设置大小%lu; 新大小%lu"},
            { 1283, "ER_BAD_FT_COLUMN: 列'%-.192s'不能用于FULLTEXT索引"},
            { 1284, "ER_UNKNOWN_KEY_CACHE: 未知键缓存: '%-.100s'"},
            { 1285, "ER_WARN_HOSTNAME_WONT_WORK: MySQL已使用'--skip-name-resolve'选项启动; 必须使用IP地址而不是主机名进行连接"},
            { 1286, "ER_UNKNOWN_STORAGE_ENGINE: 未知存储引擎: '%-.64s'"},
            { 1287, "ER_WARN_DEPRECATED_SYNTAX: '%s'已弃用，将在未来版本中删除。请使用%s代替"},
            { 1288, "ER_NON_UPDATABLE_TABLE: 目标表%s不可更新"},
            { 1289, "ER_FEATURE_DISABLED: '%s'功能已禁用; 需要使用%s重新编译"},
            { 1290, "ER_OPTION_PREVENTS_STATEMENT: MySQL服务器正在使用%s选项运行，因此无法执行此语句"},
            { 1291, "ER_DUPLICATED_VALUE_IN_TYPE: 列'%-.192s'在%s中有重复值'%-.128s'"},
            { 1292, "ER_TRUNCATED_WRONG_VALUE: 截断不正确的%s值: '%-.128s'"},
            { 1293, "ER_TOO_MUCH_AUTO_TIMESTAMP_COLS: 不正确的表定义; 只能有一个TIMESTAMP列使用CURRENT_TIMESTAMP作为DEFAULT或ON UPDATE"},
            { 1294, "ER_INVALID_ON_UPDATE: 列'%-.192s'的ON UPDATE子句无效"},
            { 1295, "ER_UNSUPPORTED_PS: 此命令在此MySQL版本中不支持准备语句"},
            { 1296, "ER_GET_ERRMSG: 从%s得到错误%d '%s'"},
            { 1297, "ER_GET_TEMPORARY_ERRMSG: 从%s得到临时错误%d '%s'"},
            { 1298, "ER_UNKNOWN_TIME_ZONE: 未知或错误的时区: '%-.64s'"},
            { 1299, "ER_WARN_INVALID_TIMESTAMP: 在行%ld的列'%-.192s'中检测到无效的TIMESTAMP值"},
            { 1300, "ER_INVALID_CHARACTER_STRING: 无效的%s字符串: '%-.64s'"},
            { 1301, "ER_WARN_ALLOWED_PACKET_OVERFLOWED: 结果%s大于max_allowed_packet(%ld) - 截断"},
            { 1302, "ER_CONFLICTING_DECLARATIONS: 冲突声明: '%s%s'和'%s%s'"},
            { 1303, "ER_SP_NO_RECURSIVE_CREATE: 无法从另一个存储例程创建%s"},
            { 1304, "ER_SP_ALREADY_EXISTS: %s %s已存在"},
            { 1305, "ER_SP_DOES_NOT_EXIST: %s %s不存在"},
            { 1306, "ER_SP_DROP_FAILED: 删除%s %s失败"},
            { 1307, "ER_SP_STORE_FAILED: 创建%s %s失败"},
            { 1308, "ER_SP_LILABEL_MISMATCH: %s无匹配标签: %s"},
            { 1309, "ER_SP_LABEL_REDEFINE: 重新定义标签%s"},
            { 1310, "ER_SP_LABEL_MISMATCH: 结束标签%s无匹配开始"},
            { 1311, "ER_SP_UNINIT_VAR: 引用未初始化的变量%s"},
            { 1312, "ER_SP_BADSELECT: 过程%s无法返回结果集在给定上下文中"},
            { 1313, "ER_SP_BADRETURN: 在函数中只允许RETURN"},
            { 1314, "ER_SP_BADSTATEMENT: 在存储过程中不允许%s"},
            { 1315, "ER_UPDATE_LOG_DEPRECATED_IGNORED: 更新日志已弃用，并替换为二进制日志; SET SQL_LOG_UPDATE已忽略"},
            { 1316, "ER_UPDATE_LOG_DEPRECATED_TRANSLATED: 更新日志已弃用，并替换为二进制日志; SET SQL_LOG_UPDATE已转换为SET SQL_LOG_BIN"},
            { 1317, "ER_QUERY_INTERRUPTED: 查询执行被中断"},
            { 1318, "ER_SP_WRONG_NO_OF_ARGS: 不正确的参数数量提供给%s %s; 预期%d，得到%d"},
            { 1319, "ER_SP_COND_MISMATCH: 未定义的CONDITION: %s"},
            { 1320, "ER_SP_NORETURN: 在函数%s中未找到RETURN"},
            { 1321, "ER_SP_NORETURNEND: 函数%s结束时缺少RETURN"},
            { 1322, "ER_SP_BAD_CURSOR_QUERY: 光标语句必须是SELECT"},
            { 1323, "ER_SP_BAD_CURSOR_SELECT: 光标SELECT不能有INTO"},
            { 1324, "ER_SP_CURSOR_MISMATCH: 未定义的CURSOR: %s"},
            { 1325, "ER_SP_CURSOR_ALREADY_OPEN: 光标已打开"},
            { 1326, "ER_SP_CURSOR_NOT_OPEN: 光标未打开"},
            { 1327, "ER_SP_UNDECLARED_VAR: 未声明的变量: %s"},
            { 1328, "ER_SP_WRONG_NO_OF_FETCH_ARGS: 不正确的参数数量提供给FETCH; 预期%d，得到%d"},
            { 1329, "ER_SP_FETCH_NO_DATA: 无数据 - 提取、选择或处理零行"},
            { 1330, "ER_SP_DUP_PARAM: 重复参数: %s"},
            { 1331, "ER_SP_DUP_VAR: 重复变量: %s"},
            { 1332, "ER_SP_DUP_COND: 重复条件: %s"},
            { 1333, "ER_SP_DUP_CURSOR: 重复光标: %s"},
            { 1334, "ER_SP_CANT_ALTER: 无法更改%s %s"},
            { 1335, "ER_SP_SUBSELECT_NYI: 子查询值尚不支持"},
            { 1336, "ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG: 在存储函数或触发器中不允许%s"},
            { 1337, "ER_SP_VARCOND_AFTER_CURSHNDLR: 变量或条件声明在光标或处理程序声明之后"},
            { 1338, "ER_SP_CURSOR_AFTER_HANDLER: 光标声明在处理程序声明之后"},
            { 1339, "ER_SP_CASE_NOT_FOUND: 未找到CASE语句的case: 在ELSE子句未找到case"},
            { 1340, "ER_FPARSER_TOO_BIG_FILE: 配置文件'%-.192s'过大"},
            { 1341, "ER_FPARSER_BAD_HEADER: 配置文件'%-.192s'的头部损坏"},
            { 1342, "ER_FPARSER_EOF_IN_COMMENT: 配置文件'%-.192s'中注释意外结束"},
            { 1343, "ER_FPARSER_ERROR_IN_PARAMETER: 配置文件'%-.192s'中参数错误"},
            { 1344, "ER_FPARSER_EOF_IN_UNKNOWN_PARAMETER: 配置文件'%-.192s'中未知参数意外结束"},
            { 1345, "ER_VIEW_NO_EXPLAIN: EXPLAIN无法发出; 缺少基础表的权限"},
            { 1346, "ER_FRM_UNKNOWN_TYPE: 文件'%-.192s'具有未知类型'%-.64s'在其头部"},
            { 1347, "ER_WRONG_OBJECT: '%-.192s'.'%-.192s'不是%s"},
            { 1348, "ER_NONUPDATEABLE_COLUMN: 列'%-.192s'不可更新"},
            { 1349, "ER_VIEW_SELECT_DERIVED: 视图的SELECT包含子查询在FROM子句中"},
            { 1350, "ER_VIEW_SELECT_CLAUSE: 视图的SELECT包含'%s'子句"},
            { 1351, "ER_VIEW_SELECT_VARIABLE: 视图的SELECT包含变量或参数"},
            { 1352, "ER_VIEW_SELECT_TMPTABLE: 视图的SELECT引用临时表'%-.192s'"},
            { 1353, "ER_VIEW_WRONG_LIST: 视图的SELECT和视图的字段列表具有不同的列计数"},
            { 1354, "ER_WARN_VIEW_MERGE: 视图合并算法无法在此处使用(假设未定义算法)"},
            { 1355, "ER_WARN_VIEW_WITHOUT_KEY: 正在更新的视图没有其基础表中完整键"},
            { 1356, "ER_VIEW_INVALID: 视图'%-.192s'.'%-.192s'引用无效表或列或其他视图或定义无效/没有定义"},
            { 1357, "ER_SP_NO_DROP_SP: 无法从另一个存储例程删除或更改%s"},
            { 1358, "ER_SP_GOTO_IN_HNDLR: GOTO不允许在存储过程处理程序中使用"},
            { 1359, "ER_TRG_ALREADY_EXISTS: 触发器已存在"},
            { 1360, "ER_TRG_DOES_NOT_EXIST: 触发器不存在"},
            { 1361, "ER_TRG_ON_VIEW_OR_TEMP_TABLE: 触发器的'%s'在视图或临时表上"},
            { 1362, "ER_TRG_CANT_CHANGE_ROW: 在%strigger中不允许更新%s行"},
            { 1363, "ER_TRG_NO_SUCH_ROW_IN_TRG: 在%s触发器中没有%s行"},
            { 1364, "ER_NO_DEFAULT_FOR_FIELD: 字段'%-.192s'没有默认值"},
            { 1365, "ER_DIVISION_BY_ZERO: 除以零"},
            { 1366, "ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: 行%ld的列'%-.192s'的不正确%s值: '%-.128s'"},
            { 1367, "ER_ILLEGAL_VALUE_FOR_TYPE: 类型%s的非法%s值"},
            { 1368, "ER_VIEW_NONUPD_CHECK: 检查选项在不可更新视图'%-.192s'.'%-.192s'上"},
            { 1369, "ER_VIEW_CHECK_FAILED: CHECK OPTION失败'%-.192s'.'%-.192s'"},
            { 1370, "ER_PROCACCESS_DENIED_ERROR: 用户'%-.48s'@'%-.64s'对例程'%-.192s'的%s权限被拒绝"},
            { 1371, "ER_RELAY_LOG_FAIL: 无法清除中继日志文件: %s"},
            { 1372, "ER_PASSWD_LENGTH: 密码哈希应为%d位十六进制数"},
            { 1373, "ER_UNKNOWN_TARGET_BINLOG: 在binlog索引中找不到目标日志"},
            { 1374, "ER_IO_ERR_LOG_INDEX_READ: 读取日志索引文件时I/O错误"},
            { 1375, "ER_BINLOG_PURGE_PROHIBITED: 服务器配置不允许binlog清除"},
            { 1376, "ER_FSEEK_FAIL: 在日志索引文件上fseek()失败"},
            { 1377, "ER_BINLOG_PURGE_FATAL_ERR: 在binlog清除期间发生致命错误"},
            { 1378, "ER_LOG_IN_USE: 可清除的日志正在使用中，将不清除"},
            { 1379, "ER_LOG_PURGE_UNKNOWN_ERR: 在日志清除期间发生未知错误"},
            { 1380, "ER_RELAY_LOG_INIT: 无法初始化中继日志结构; 更多错误消息可以在MySQL错误日志中找到"},
            { 1381, "ER_NO_BINARY_LOGGING: 您没有使用二进制日志记录"},
            { 1382, "ER_RESERVED_SYNTAX: '%s'语法已保留用于MySQL服务器内部使用"},
            { 1383, "ER_WSAS_FAILED: WSAStartup失败"},
            { 1384, "ER_DIFF_GROUPS_PROC: 无法使用不同的组处理程序处理过程"},
            { 1385, "ER_NO_GROUP_FOR_PROC: 对于该过程没有组处理程序"},
            { 1386, "ER_ORDER_WITH_PROC: 无法与ORDER一起使用过程"},
            { 1387, "ER_LOGGING_PROHIBIT_CHANGING_OF: 记录禁止更改%s"},
            { 1388, "ER_NO_FILE_MAPPING: 无法映射文件: %s, errno: %d"},
            { 1389, "ER_WRONG_MAGIC: %s中的错误魔法"},
            { 1390, "ER_PS_MANY_PARAM: 准备语句包含太多占位符"},
            { 1391, "ER_KEY_PART_0: 键部分'%-.192s'的长度不能为0"},
            { 1392, "ER_VIEW_CHECKSUM: 视图文本校验和不匹配"},
            { 1393, "ER_VIEW_MULTIUPDATE: 无法通过连接视图'%-.192s'.'%-.192s'修改多个基表"},
            { 1394, "ER_VIEW_NO_INSERT_FIELD_LIST: 无法插入到没有完整字段列表的连接视图'%-.192s'.'%-.192s'中"},
            { 1395, "ER_VIEW_DELETE_MERGE_VIEW: 无法从连接视图'%-.192s'.'%-.192s'中删除"},
            { 1396, "ER_CANNOT_USER: 操作%s对%s失败"},
            { 1397, "ER_XAER_NOTA: XAER_NOTA: 未知XID"},
            { 1398, "ER_XAER_INVAL: XAER_INVAL: 无效参数(或不支持的命令)"},
            { 1399, "ER_XAER_RMFAIL: XAER_RMFAIL: 资源管理器出错时命令失败"},
            { 1400, "ER_XAER_OUTSIDE: XAER_OUTSIDE: 某些工作是在全局事务之外完成的"},
            { 1401, "ER_XAER_RMERR: XAER_RMERR: 事务分支中出现资源管理器错误"},
            { 1402, "ER_XA_RBROLLBACK: XA_RBROLLBACK: 事务分支已回滚"},
            { 1403, "ER_NONEXISTING_PROC_GRANT: 没有为用户'%-.48s'在主机'%-.64s'上的例程'%-.192s'定义此类授权"},
            { 1404, "ER_PROC_AUTO_GRANT_FAIL: 无法授予EXECUTE和ALTER ROUTINE权限"},
            { 1405, "ER_PROC_AUTO_REVOKE_FAIL: 无法撤销EXECUTE和ALTER ROUTINE权限"},
            { 1406, "ER_DATA_TOO_LONG: 第%ld行列'%s'的数据过长"},
            { 1407, "ER_SP_BAD_SQLSTATE: 错误的SQLSTATE: '%s'"},
            { 1408, "ER_STARTUP: %s: 准备连接失败。%s"},
            { 1409, "ER_LOAD_FROM_FIXED_SIZE_ROWS_TO_VAR: 无法从具有固定大小行的文件加载到具有可变大小行的表中"},
            { 1410, "ER_CANT_CREATE_USER_WITH_GRANT: 您不允许使用GRANT创建用户"},
            { 1411, "ER_WRONG_VALUE_FOR_TYPE: 不正确的%s值: '%-.128s'用于函数%s"},
            { 1412, "ER_TABLE_DEF_CHANGED: 表定义已更改，请重试事务"},
            { 1413, "ER_SP_DUP_HANDLER: 重复的处理程序在相同块中声明"},
            { 1414, "ER_SP_NOT_VAR_ARG: 不允许OUT或INOUT参数用于%s %s"},
            { 1415, "ER_SP_NO_RETSET: 不允许从%s返回结果集"},
            { 1416, "ER_CANT_CREATE_GEOMETRY_OBJECT: 无法从发送给GEOMETRY字段的数据中获取几何对象"},
            { 1417, "ER_FAILED_ROUTINE_BREAK_BINLOG: 例程失败，并且二进制日志记录已启用; 如果存储的函数/触发器使用非确定性操作，则可能不安全"},
            { 1418, "ER_BINLOG_UNSAFE_ROUTINE: 此函数在其主体中没有DETERMINISTIC、NO SQL或READS SQL DATA，并且二进制日志记录已启用(您*可能*希望使用不太安全的log_bin_trust_function_creators变量)"},
            { 1419, "ER_BINLOG_CREATE_ROUTINE_NEED_SUPER: 您没有SUPER权限，并且二进制日志记录已启用(您*可能*希望使用不太安全的log_bin_trust_function_creators变量)"},
            { 1420, "ER_EXEC_STMT_WITH_OPEN_CURSOR: 您无法在准备好的语句中执行此命令，该语句具有与之关联的打开游标。请先关闭游标，然后再执行该语句。"},
            { 1421, "ER_STMT_HAS_NO_OPEN_CURSOR: 该语句没有打开的游标。"},
            { 1422, "ER_COMMIT_NOT_ALLOWED_IN_SF_OR_TRG: 在存储函数或触发器中不允许显式或隐式提交。"},
            { 1423, "ER_NO_DEFAULT_FOR_VIEW_FIELD: 视图'%-.192s'.'%-.192s'的基础表没有默认值"},
            { 1424, "ER_SP_NO_RECURSION: 不允许递归存储函数。"},
            { 1425, "ER_TOO_BIG_SCALE: 为列'%-.192s'指定了太大的比例%d。最大为%d。"},
            { 1426, "ER_TOO_BIG_PRECISION: 为列'%-.192s'指定了太大的精度%d。最大为%d。"},
            { 1427, "ER_M_BIGGER_THAN_D: 对于float(M,D)、double(M,D)或decimal(M,D)，M必须>= D(列'%-.192s')。"},
            { 1428, "ER_WRONG_LOCK_OF_SYSTEM_TABLE: 您无法将系统表'%-.192s'.'%-.192s'与%s锁定"},
            { 1429, "ER_CONNECT_TO_FOREIGN_DATA_SOURCE: 无法连接到外部数据源: %-.64s"},
            { 1430, "ER_QUERY_ON_FOREIGN_DATA_SOURCE: 对外部数据源的处理失败。数据源错误: %-.64s"},
            { 1431, "ER_FOREIGN_DATA_SOURCE_DOESNT_EXIST: 您尝试引用的外部数据源不存在。数据源名称: %-.64s"},
            { 1432, "ER_FOREIGN_DATA_STRING_INVALID_CANT_CREATE: 无法创建联合表。数据源连接字符串'%-.100s'格式不正确。"},
            { 1433, "ER_FOREIGN_DATA_STRING_INVALID: 数据源连接字符串'%-.100s'格式不正确。"},
            { 1434, "ER_CANT_CREATE_FEDERATED_TABLE: 无法创建联合表。外部数据源错误: %-.64s"},
            { 1435, "ER_TRG_IN_WRONG_SCHEMA: 触发器在错误的架构中"},
            { 1436, "ER_STACK_OVERRUN_NEED_MORE: 线程堆栈溢出: %ld字节的堆栈使用，%ld字节需要。使用'mysqld --thread_stack=#'指定更大的堆栈。"},
            { 1437, "ER_TOO_LONG_BODY: 例程体对于'%-.192s'过长"},
            { 1438, "ER_WARN_CANT_DROP_DEFAULT_KEYCACHE: 无法删除默认键缓存"},
            { 1439, "ER_TOO_BIG_DISPLAYWIDTH: 显示宽度超出范围对于列'%-.192s'(最大值=%lu)"},
            { 1440, "ER_XAER_DUPID: XAER_DUPID: XID已存在"},
            { 1441, "ER_DATETIME_FUNCTION_OVERFLOW: 日期时间函数: %s字段溢出"},
            { 1442, "ER_CANT_UPDATE_USED_TABLE_IN_SF_OR_TRG: 无法更新存储函数/触发器中的表'%-.192s'，因为它已被调用此存储函数/触发器的语句使用。"},
            { 1443, "ER_VIEW_PREVENT_UPDATE: 表'%-.192s'的定义不允许在表'%-.192s'上操作。"},
            { 1444, "ER_PS_NO_RECURSION: 准备好的语句包含对相同语句的引用。"},
            { 1445, "ER_SP_CANT_SET_AUTOCOMMIT: 不允许在存储函数或触发器中设置自动提交。"},
            { 1446, "ER_MALFORMED_DEFINER: 视图'%-.192s'.'%-.192s'的定义者格式不正确。"},
            { 1447, "ER_VIEW_FRM_NO_USER: 视图'%-.192s'.'%-.192s'的.frm文件中没有定义者信息。"},
            { 1448, "ER_VIEW_OTHER_USER: 您需要定义者/调用者权限才能使用视图'%-.192s'.'%-.192s'。"},
            { 1449, "ER_NO_SUCH_USER: 指定为定义者的用户'%-.48s'@'%-.64s'不存在。"},
            { 1450, "ER_FORBID_SCHEMA_CHANGE: 不允许将架构从'%-.64s'更改为'%-.64s'。"},
            { 1451, "ER_ROW_IS_REFERENCED_2: 无法删除或更新父行: 外键约束失败(%s)"},
            { 1452, "ER_NO_REFERENCED_ROW_2: 无法添加或更新子行: 外键约束失败(%s)"},
            { 1453, "ER_SP_BAD_VAR_SHADOW: 变量'%-.64s'必须用...声明或必须在...之前声明"},
            { 1454, "ER_TRG_NO_DEFINER: 触发器'%-.192s'.'%-.192s'没有定义者信息。"},
            { 1455, "ER_OLD_FILE_FORMAT: '%-.192s'具有旧格式，您应该重新创建此视图或获取更新的.frm文件"},
            { 1456, "ER_SP_RECURSION_LIMIT: 递归限制%d(如max_sp_recursion_depth变量所设置)已用完"},
            { 1457, "ER_SP_PROC_TABLE_CORRUPT: 无法从mysql.proc表加载例程%s。该表可能已损坏"},
            { 1458, "ER_SP_WRONG_NAME: 不正确的例程名称'%-.192s'"},
            { 1459, "ER_TABLE_NEEDS_UPGRADE: 表'%-.192s'.'%-.192s'需要升级。"},
            { 1460, "ER_SP_NO_AGGREGATE: 不允许聚合函数在%s"},
            { 1461, "ER_MAX_PREPARED_STMT_COUNT_REACHED: 无法创建超过max_prepared_stmt_count个预处理语句(当前值: %lu)"},
            { 1462, "ER_VIEW_RECURSIVE: 视图'%-.64s'.'%-.64s'的SELECT包含对自身的子查询引用"},
            { 1463, "ER_NON_GROUPING_FIELD_USED: 非分组字段'%-.192s'在HAVING子句中使用"},
            { 1464, "ER_TABLE_CANT_HANDLE_SPKEYS: 使用的表类型不支持SPATIAL索引"},
            { 1465, "ER_NO_TRIGGERS_ON_SYSTEM_SCHEMA: 不允许在系统表上创建触发器"},
            { 1466, "ER_REMOVED_SPACES: 前导空格从名称'%-.192s'中删除"},
            { 1467, "ER_AUTOINC_READ_FAILED: 无法从存储引擎读取自增值"},
            { 1468, "ER_USERNAME: 用户名"},
            { 1469, "ER_HOSTNAME: 主机名"},
            { 1470, "ER_WRONG_STRING_LENGTH: 字符串'%-.70s'对于%s太长(应为%d, 最大%d)"},
            { 1471, "ER_NON_INSERTABLE_TABLE: 表'%-.192s'.'%-.192s'的目标不可插入"},
            { 1472, "ER_ADMIN_WRONG_MRG_TABLE: 表'%-.192s'.'%-.192s'定义为MERGE表，但没有UNION=(表列表); 您必须修复此表"},
            { 1473, "ER_TOO_HIGH_LEVEL_OF_NESTING_FOR_SELECT: 对于SELECT的嵌套级别太高"},
            { 1474, "ER_NAME_BECOMES_EMPTY: 名称'%-.192s'变为空"},
            { 1475, "ER_AMBIGUOUS_FIELD_TERM: 第一个字段终止符与行终止符匹配，并且行终止符不是空的; 如果这不是您想要的，请检查您的数据"},
            { 1476, "ER_FOREIGN_SERVER_EXISTS: 外部服务器'%s'已存在"},
            { 1477, "ER_FOREIGN_SERVER_DOESNT_EXIST: 外部服务器'%s'不存在"},
            { 1478, "ER_ILLEGAL_HA_CREATE_OPTION: 表存储引擎'%s'不支持创建选项'%s'"},
            { 1479, "ER_PARTITION_REQUIRES_VALUES_ERROR: 语法错误: %s PARTITIONING需要VALUES %s的定义"},
            { 1480, "ER_PARTITION_WRONG_VALUES_ERROR: 只有%s PARTITIONING可以使用VALUES %s"},
            { 1481, "ER_PARTITION_MAXVALUE_ERROR: MAXVALUE只能在最后一个分区定义中使用"},
            { 1482, "ER_PARTITION_SUBPARTITION_ERROR: 子分区只能用于RANGE/LIST分区"},
            { 1483, "ER_PARTITION_SUBPART_MIX_ERROR: 必须在每个分区中定义相同数量的子分区"},
            { 1484, "ER_PARTITION_WRONG_NO_PART_ERROR: 错误的分区数，没有分区"},
            { 1485, "ER_PARTITION_WRONG_NO_SUBPART_ERROR: 错误的子分区数，没有子分区"},
            { 1486, "ER_WRONG_EXPR_IN_PARTITION_FUNC_ERROR: 分区函数中不允许常量、随机或时区相关表达式"},
            { 1487, "ER_NO_CONST_EXPR_IN_RANGE_OR_LIST_ERROR: 在RANGE/LIST VALUES中只允许常量表达式"},
            { 1488, "ER_FIELD_NOT_FOUND_PART_ERROR: 在分区函数中找不到字段"},
            { 1489, "ER_LIST_OF_FIELDS_ONLY_IN_HASH_ERROR: 字段列表仅在KEY分区中允许"},
            { 1490, "ER_INCONSISTENT_PARTITION_INFO_ERROR: 分区信息不一致"},
            { 1491, "ER_PARTITION_FUNC_NOT_ALLOWED_ERROR: 此分区函数不允许"},
            { 1492, "ER_PARTITIONS_MUST_BE_DEFINED_ERROR: 对于%s分区，必须定义分区"},
            { 1493, "ER_RANGE_NOT_INCREASING_ERROR: VALUES LESS THAN值必须严格递增"},
            { 1494, "ER_INCONSISTENT_TYPE_OF_FUNCTIONS_ERROR: VALUES值必须与分区函数具有相同类型"},
            { 1495, "ER_MULTIPLE_DEF_CONST_IN_LIST_PART_ERROR: LIST分区中不允许重复的条目"},
            { 1496, "ER_PARTITION_ENTRY_ERROR: 分区定义中的错误"},
            { 1497, "ER_MIX_HANDLER_ERROR: 此版本的MySQL尚不支持此表中的处理程序混合"},
            { 1498, "ER_PARTITION_NOT_DEFINED_ERROR: 对于表'%-.192s'.'%-.192s'，分区'%-.64s'未定义"},
            { 1499, "ER_TOO_MANY_PARTITIONS_ERROR: 分区太多，最大为%d"},
            { 1500, "ER_SUBPARTITION_ERROR: 子分区错误，无法分配子分区"},
            { 1501, "ER_CANT_CREATE_HANDLER_FILE: 无法创建特定的处理程序文件"},
            { 1502, "ER_BLOB_FIELD_IN_PART_FUNC_ERROR: BLOB字段在分区函数中不允许"},
            { 1503, "ER_UNIQUE_KEY_NEED_ALL_FIELDS_IN_PF: %-.192s必须包括表分区函数中的所有列"},
            { 1504, "ER_NO_PARTS_ERROR: 表'%-.192s'.'%-.192s'的分区数=0"},
            { 1505, "ER_PARTITION_MGMT_ON_NONPARTITIONED: 对非分区表的分区管理"},
            { 1506, "ER_FOREIGN_KEY_ON_PARTITIONED: 不支持分区表上的外键"},
            { 1507, "ER_DROP_PARTITION_NON_EXISTENT: 删除不存在的分区错误"},
            { 1508, "ER_DROP_LAST_PARTITION: 无法删除所有分区，请改用DROP TABLE"},
            { 1509, "ER_COALESCE_ONLY_ON_HASH_PARTITION: COALESCE PARTITION只能用于HASH/KEY分区"},
            { 1510, "ER_REORG_HASH_ONLY_ON_SAME_NO: REORGANIZE PARTITION只能用于重新组织分区而不更改其数量"},
            { 1511, "ER_REORG_NO_PARAM_ERROR: REORGANIZE PARTITION没有参数"},
            { 1512, "ER_ONLY_ON_RANGE_LIST_PARTITION: %s PARTITION只能用于RANGE/LIST分区"},
            { 1513, "ER_ADD_PARTITION_SUBPART_ERROR: 尝试添加具有错误数量的子分区的分区"},
            { 1514, "ER_ADD_PARTITION_NO_NEW_PARTITION_ERROR: 必须至少添加一个分区"},
            { 1515, "ER_COALESCE_PARTITION_NO_PARTITION_ERROR: 必须至少合并一个分区"},
            { 1516, "ER_REORG_PARTITION_NOT_EXIST_ERROR: 重新组织不存在的分区"},
            { 1517, "ER_SAME_NAME_PARTITION: 重复的分区名称'%-.64s'"},
            { 1518, "ER_NO_BINLOG_ERROR: 二进制日志记录已关闭; 可能需要重新启动服务器以启用它"},
            { 1519, "ER_CONSECUTIVE_REORG_PARTITIONS: 重新组织一组连续的分区时，它们必须按顺序排列"},
            { 1520, "ER_REORG_OUTSIDE_RANGE: 重新组织分区范围超出范围"},
            { 1521, "ER_PARTITION_FUNCTION_FAILURE: 分区功能故障"},
            { 1522, "ER_PART_STATE_ERROR: 分区状态错误"},
            { 1523, "ER_LIMITED_PART_RANGE: 此版本的MySQL尚不支持此分区范围"},
            { 1524, "ER_PLUGIN_IS_NOT_LOADED: 插件'%s'未加载"},
            { 1525, "ER_WRONG_VALUE: 不正确的%s值: '%-.64s'"},
            { 1526, "ER_NO_PARTITION_FOR_GIVEN_VALUE: 表没有分区用于值'%-.64s'"},
            { 1527, "ER_FILEGROUP_OPTION_ONLY_ONCE: 每个表只能使用一次FILEGROUP选项"},
            { 1528, "ER_CREATE_FILEGROUP_FAILED: 创建文件组失败"},
            { 1529, "ER_DROP_FILEGROUP_FAILED: 删除文件组失败"},
            { 1530, "ER_TABLESPACE_AUTO_EXTEND_ERROR: 表空间自动扩展错误"},
            { 1531, "ER_WRONG_SIZE_NUMBER: 大小数字语法错误"},
            { 1532, "ER_SIZE_OVERFLOW_ERROR: 大小溢出错误"},
            { 1533, "ER_ALTER_FILEGROUP_FAILED: 更改文件组失败"},
            { 1534, "ER_BINLOG_ROW_LOGGING_FAILED: 二进制日志行记录失败: %s"},
            { 1535, "ER_BINLOG_ROW_WRONG_TABLE_DEF: 表定义在主从服务器上不匹配: %s"},
            { 1536, "ER_BINLOG_ROW_RBR_TO_SBR: 无法使用语句格式在从服务器上执行行事件"},
            { 1537, "ER_EVENT_ALREADY_EXISTS: 事件'%-.192s'已存在"},
            { 1538, "ER_EVENT_STORE_FAILED: 创建/更改事件'%-.192s'失败"},
            { 1539, "ER_EVENT_DOES_NOT_EXIST: 未知事件'%-.192s'"},
            { 1540, "ER_EVENT_CANT_ALTER: 无法更改事件'%-.192s'"},
            { 1541, "ER_EVENT_DROP_FAILED: 删除事件'%-.192s'失败"},
            { 1542, "ER_EVENT_INTERVAL_NOT_POSITIVE_OR_TOO_BIG: 事件间隔既不是正数也不是太大"},
            { 1543, "ER_EVENT_ENDS_BEFORE_STARTS: 事件结束在开始之前"},
            { 1544, "ER_EVENT_EXEC_TIME_IN_THE_PAST: 事件执行时间在过去，ON COMPLETION NOT PRESERVE设置。事件在创建后立即被删除。"},
            { 1545, "ER_EVENT_OPEN_TABLE_FAILED: 无法打开mysql.event表"},
            { 1546, "ER_EVENT_NEITHER_M_EXPR_NOR_M_AT: 事件'%-.192s'既没有表达式也没有AT子句"},
            { 1547, "ER_COL_COUNT_DOESNT_MATCH_CORRUPTED: 列计数错误。预期%d，找到%d。表可能已损坏"},
            { 1548, "ER_CANNOT_LOAD_FROM_TABLE: 无法从mysql.%s加载。该表可能已损坏"},
            { 1549, "ER_EVENT_CANNOT_DELETE: 无法从mysql.event删除事件"},
            { 1550, "ER_EVENT_COMPILE_ERROR: 事件体编译期间出错"},
            { 1551, "ER_EVENT_SAME_NAME: 相同的新旧事件名称"},
            { 1552, "ER_EVENT_DATA_TOO_LONG: 列'%s'的数据过长"},
            { 1553, "ER_DROP_INDEX_FK: 无法删除索引'%-.192s': 外键约束中需要"},
            { 1554, "ER_WARN_DEPRECATED_SYNTAX_WITH_VER: 语法'%s'已弃用，将在MySQL %s中删除。请改用%s"},
            { 1555, "ER_CANT_WRITE_LOCK_LOG_TABLE: 您无法写锁定日志表。只允许读访问"},
            { 1556, "ER_CANT_LOCK_LOG_TABLE: 您无法对日志表使用锁。"},
            { 1557, "ER_FOREIGN_DUPLICATE_KEY: 维护表'%.192s'的外键约束，条目'%-.192s'，键%d将导致重复条目"},
            { 1558, "ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE: mysql.%s的列计数错误。预期%d，找到%d。使用MySQL %d创建，现在运行%d。请使用mysql_upgrade修复此错误。"},
            { 1559, "ER_TEMP_TABLE_PREVENTS_SWITCH_OUT_OF_RBR: 当会话有打开的临时表时，无法从基于行的二进制日志格式切换"},
            { 1560, "ER_STORED_FUNCTION_PREVENTS_SWITCH_BINLOG_FORMAT: 无法在存储函数或触发器内部更改二进制日志格式"},
            { 1561, "ER_NDB_CANT_SWITCH_BINLOG_FORMAT: NDB集群引擎尚不支持动态更改binlog格式"},
            { 1562, "ER_PARTITION_NO_TEMPORARY: 无法创建具有分区的临时表"},
            { 1563, "ER_PARTITION_CONST_DOMAIN_ERROR: 分区常量超出分区函数域"},
            { 1564, "ER_PARTITION_FUNCTION_IS_NOT_ALLOWED: 不允许此分区函数"},
            { 1565, "ER_DDL_LOG_ERROR: DDL日志中的错误"},
            { 1566, "ER_NULL_IN_VALUES_LESS_THAN: 在VALUES LESS THAN中不允许使用NULL值"},
            { 1567, "ER_WRONG_PARTITION_NAME: 不正确的分区名称"},
            { 1568, "ER_CANT_CHANGE_TX_CHARACTERISTICS: 事务正在进行时无法更改事务特征"},
            { 1569, "ER_DUP_ENTRY_AUTOINCREMENT_CASE: ALTER TABLE导致自动递增重新排序，导致键'%-.192s'的重复条目'%-.192s'"},
            { 1570, "ER_EVENT_MODIFY_QUEUE_ERROR: 内部调度程序错误%d"},
            { 1571, "ER_EVENT_SET_VAR_ERROR: 调度程序启动/停止期间出错。错误代码%u"},
            { 1572, "ER_PARTITION_MERGE_ERROR: 引擎不能在分区表中使用"},
            { 1573, "ER_CANT_ACTIVATE_LOG: 无法激活'%-.64s'日志"},
            { 1574, "ER_RBR_NOT_AVAILABLE: 服务器未使用基于行的复制构建"},
            { 1575, "ER_BASE64_DECODE_ERROR: base64字符串解码失败"},
            { 1576, "ER_EVENT_RECURSION_FORBIDDEN: 当存在主体时，禁止事件DDL语句的递归"},
            { 1577, "ER_EVENTS_DB_ERROR: 无法继续，因为在服务器启动时发现事件调度程序使用的系统表已损坏"},
            { 1578, "ER_ONLY_INTEGERS_ALLOWED: 此处只允许整数作为数字"},
            { 1579, "ER_UNSUPORTED_LOG_ENGINE: 此存储引擎不能用于日志表"},
            { 1580, "ER_BAD_LOG_STATEMENT: 如果启用了日志记录，则无法对日志表执行'%s'"},
            { 1581, "ER_CANT_RENAME_LOG_TABLE: 无法重命名'%s'。启用日志记录时，重命名到/从日志表必须重命名两个表: 日志表到存档表，另一个表回到'%s'"},
            { 1582, "ER_WRONG_PARAMCOUNT_TO_NATIVE_FCT: 调用本机函数'%-.192s'的参数计数不正确"},
            { 1583, "ER_WRONG_PARAMETERS_TO_NATIVE_FCT: 调用本机函数'%-.192s'的参数不正确"},
            { 1584, "ER_WRONG_PARAMETERS_TO_STORED_FCT: 调用存储函数'%-.192s'的参数不正确"},
            { 1585, "ER_NATIVE_FCT_NAME_COLLISION: 此函数'%-.192s'与本机函数同名"},
            { 1586, "ER_DUP_ENTRY_WITH_KEY_NAME: 键'%-.192s'的重复条目'%-.64s'"},
            { 1587, "ER_BINLOG_PURGE_EMFILE: 打开的文件太多，请再次执行命令"},
            { 1588, "ER_EVENT_CANNOT_CREATE_IN_THE_PAST: 事件执行时间在过去，ON COMPLETION NOT PRESERVE设置。事件在创建后立即被删除。"},
            { 1589, "ER_EVENT_CANNOT_ALTER_IN_THE_PAST: 事件执行时间在过去，ON COMPLETION NOT PRESERVE设置。事件未更改。请指定未来的时间。"},
            { 1590, "ER_SLAVE_INCIDENT: 主服务器上发生事件%s。消息: %-.64s"},
            { 1591, "ER_NO_PARTITION_FOR_GIVEN_VALUE_SILENT: 表没有某些现有值的分区"},
            { 1592, "ER_BINLOG_UNSAFE_STATEMENT: 由于BINLOG_FORMAT = STATEMENT，不安全的语句写入二进制日志。%s"},
            { 1593, "ER_SLAVE_FATAL_ERROR: 致命错误: %s"},
            { 1594, "ER_SLAVE_RELAY_LOG_READ_FAILURE: 中继日志读取失败: %s"},
            { 1595, "ER_SLAVE_RELAY_LOG_WRITE_FAILURE: 中继日志写入失败: %s"},
            { 1596, "ER_SLAVE_CREATE_EVENT_FAILURE: 创建%s失败"},
            { 1597, "ER_SLAVE_MASTER_COM_FAILURE: 主命令%s失败: %s"},
            { 1598, "ER_BINLOG_LOGGING_IMPOSSIBLE: 无法进行二进制日志记录。消息: %s"},
            { 1599, "ER_VIEW_NO_CREATION_CTX: 视图`%-.64s`.`%-.64s`没有创建上下文"},
            { 1600, "ER_VIEW_INVALID_CREATION_CTX: 视图`%-.64s`.`%-.64s`的创建上下文无效"},
            { 1601, "ER_SR_INVALID_CREATION_CTX: 存储例程`%-.64s`.`%-.64s`的创建上下文无效"},
            { 1602, "ER_TRG_CORRUPTED_FILE: 表`%-.64s`.`%-.64s`的TRG文件已损坏"},
            { 1603, "ER_TRG_NO_CREATION_CTX: 表`%-.64s`.`%-.64s`的触发器没有创建上下文"},
            { 1604, "ER_TRG_INVALID_CREATION_CTX: 表`%-.64s`.`%-.64s`的触发器创建上下文无效"},
            { 1605, "ER_EVENT_INVALID_CREATION_CTX: 事件`%-.64s`.`%-.64s`的创建上下文无效"},
            { 1606, "ER_TRG_CANT_OPEN_TABLE: 无法为触发器`%-.64s`.`%-.64s`打开表"},
            { 1607, "ER_CANT_CREATE_SROUTINE: 无法创建存储例程`%-.64s`。检查警告"},
            { 1608, "ER_NEVER_USED: 模糊的从服务器模式组合。%s"},
            { 1609, "ER_NO_FORMAT_DESCRIPTION_EVENT_BEFORE_BINLOG_STATEMENT: 类型为`%s`的BINLOG语句前面没有格式描述BINLOG语句。"},
            { 1610, "ER_SLAVE_CORRUPT_EVENT: 检测到损坏的复制事件"},
            { 1611, "ER_LOAD_DATA_INVALID_COLUMN: LOAD DATA中的无效列引用(%-.64s)"},
            { 1612, "ER_LOG_PURGE_NO_FILE: 未找到正在清除的日志%s"},
            { 1613, "ER_XA_RBTIMEOUT: XA_RBTIMEOUT: 事务分支已回滚: 耗时过长"},
            { 1614, "ER_XA_RBDEADLOCK: XA_RBDEADLOCK: 事务分支已回滚: 检测到死锁"},
            { 1615, "ER_NEED_REPREPARE: 预处理语句需要重新准备"},
            { 1616, "ER_DELAYED_NOT_SUPPORTED: 表'%-.192s'不支持DELAYED选项"},
            { 1617, "WARN_NO_MASTER_INFO: 主信息结构不存在"},
            { 1618, "WARN_OPTION_IGNORED: <%-.64s>选项被忽略"},
            { 1619, "WARN_PLUGIN_DELETE_BUILTIN: 无法删除内置插件"},
            { 1620, "WARN_PLUGIN_BUSY: 插件正忙，将在关闭时卸载"},
            { 1621, "ER_VARIABLE_IS_READONLY: %s变量'%s'是只读的。使用SET %s分配值"},
            { 1622, "ER_WARN_ENGINE_TRANSACTION_ROLLBACK: 存储引擎%s不支持此语句的回滚。事务已回滚，必须重新启动"},
            { 1623, "ER_SLAVE_HEARTBEAT_FAILURE: 意外的主服务器心跳数据: %s"},
            { 1624, "ER_SLAVE_HEARTBEAT_VALUE_OUT_OF_RANGE: 请求的心跳周期值为负数或超过最大允许值(%s秒)。"},
            { 1625, "ER_NDB_REPLICATION_SCHEMA_ERROR: mysql.ndb_replication表的架构错误。消息: %-.64s"},
            { 1626, "ER_CONFLICT_FN_PARSE_ERROR: 解析冲突函数时出错。消息: %-.64s"},
            { 1627, "ER_EXCEPTIONS_WRITE_ERROR: 写入异常表失败。消息: %-.128s"},
            { 1628, "ER_TOO_LONG_TABLE_COMMENT: 表'%-.64s'的注释过长(最大值=%lu)"},
            { 1629, "ER_TOO_LONG_FIELD_COMMENT: 字段'%-.64s'的注释过长(最大值=%lu)"},
            { 1630, "ER_FUNC_INEXISTENT_NAME_COLLISION: 函数%s不存在。请参考手册中的'函数名称解析'部分"},
            { 1631, "ER_DATABASE_NAME: 数据库"},
            { 1632, "ER_TABLE_NAME: 表"},
            { 1633, "ER_PARTITION_NAME: 分区"},
            { 1634, "ER_SUBPARTITION_NAME: 子分区"},
            { 1635, "ER_TEMPORARY_NAME: 临时"},
            { 1636, "ER_RENAMED_NAME: 重命名"},
            { 1637, "ER_TOO_MANY_CONCURRENT_TRXS: 活动并发事务过多"},
            { 1638, "ER_SLAVE_CHANNEL_DOES_NOT_EXIST: 复制通道'%-.64s'不存在"},
            { 1639, "ER_SLAVE_MULTIPLE_CHANNELS_HOST_PORT: 对于给定的主服务器主机和端口组合，不能有多个复制通道"},
            { 1640, "ER_SLAVE_CHANNEL_NAME_INVALID_OR_TOO_LONG: 复制通道名称无效或过长"},
            { 1641, "ER_SLAVE_NEW_CHANNEL_WRONG_REPOSITORY: 不能创建新的复制通道。请检查复制存储库"},
            { 1642, "ER_SLAVE_CHANNEL_DELETE: 无法删除复制通道'%-.64s'"},
            { 1643, "ER_SLAVE_CHANNEL_CREATE: 无法创建复制通道'%-.64s'"},
            { 1644, "ER_SLAVE_CHANNEL_MASTER: 无法将复制通道'%-.64s'连接到主服务器"},
            { 1645, "ER_SLAVE_MULTIPLE_CHANNELS_CMD: 此命令需要指定复制通道名称"},
            { 1646, "ER_SLAVE_MAX_CHANNELS_EXCEEDED: 超过最大复制通道数限制"},
            { 1647, "ER_SLAVE_CHANNEL_MUST_STOP: 在更改复制通道之前必须停止它"},
            { 1648, "ER_SLAVE_CHANNEL_NOT_RUNNING: 复制通道'%-.64s'未运行"},
            { 1649, "ER_SLAVE_CHANNEL_WAS_RUNNING: 复制通道'%-.64s'正在运行"},
            { 1650, "ER_SLAVE_CHANNEL_WAS_NOT_RUNNING: 复制通道'%-.64s'未运行"},
            { 1651, "ER_SLAVE_CHANNEL_SQL_THREAD_MUST_STOP: 在更改复制通道之前必须停止SQL线程"},
            { 1652, "ER_SLAVE_CHANNEL_SQL_SKIP_COUNTER: 当复制通道运行时，不能设置sql_slave_skip_counter"},
            { 1653, "ER_WRONG_FIELD_WITH_GROUP: 表达式#%d的SELECT列表不在GROUP BY子句中，并且包含非聚合列'%-.192s'，该列在功能上不依赖于GROUP BY子句中的列; 这与sql_mode=only_full_group_by不兼容"},
            { 1654, "ER_WRONG_GROUP_FIELD: 不能在GROUP BY子句中使用表达式#%d"},
            { 1655, "ER_WRONG_SUM_SELECT: 语句包含集合函数和GROUP BY子句中的列，但SELECT列表中的列'%-.192s'既不在GROUP BY子句中，也不在集合函数中"},
            { 1656, "ER_WRONG_VALUE_COUNT: 列计数不匹配值计数"},
            { 1657, "ER_TOO_LONG_IDENT: 标识符'%-.100s'过长"},
            { 1658, "ER_DUP_FIELDNAME: 重复的列名'%-.192s'"},
            { 1659, "ER_DUP_KEYNAME: 重复的键名'%-.64s'"},
            { 1660, "ER_DUP_ENTRY: 键'%-.192s'的重复条目'%-.192s'"},
            { 1661, "ER_WRONG_FIELD_SPEC: 列'%-.100s'的说明不正确"},
            { 1662, "ER_PARSE_ERROR: %s near '%-.80s' at line %d"},
            { 1663, "ER_EMPTY_QUERY: 查询为空"},
            { 1664, "ER_NONUNIQ_TABLE: 表'%-.192s'不唯一"},
            { 1665, "ER_INVALID_DEFAULT: 列'%-.192s'的默认值无效"},
            { 1666, "ER_MULTIPLE_PRI_KEY: 定义了多个主键"},
            { 1667, "ER_TOO_MANY_KEYS: 指定了太多键; 最大允许%d个键"},
            { 1668, "ER_TOO_MANY_KEY_PARTS: 指定了太多键部分; 最大允许%d个部分"},
            { 1669, "ER_TOO_LONG_KEY: 指定的键过长; 最大键长度为%d字节"},
            { 1670, "ER_KEY_COLUMN_DOES_NOT_EXITS: 键列'%-.192s'在表中不存在"},
            { 1671, "ER_BLOB_USED_AS_KEY: 使用的BLOB/TEXT列'%-.192s'用于键规范，没有使用键长度"},
            { 1672, "ER_TOO_BIG_FIELDLENGTH: 列'%-.192s'的长度过大(max = %lu); 使用BLOB或TEXT代替"},
            { 1673, "ER_WRONG_AUTO_KEY: 表定义不正确; 只能有一个自动列，并且必须定义为键"},
            { 1674, "ER_READY: %s: 准备连接。版本: '%s' 套接字: '%s' 端口: %d"},
            { 1675, "ER_NORMAL_SHUTDOWN: %s: 正常关闭"},
            { 1676, "ER_GOT_SIGNAL: %s: 收到信号%d。正在中止!"},
            { 1677, "ER_SHUTDOWN_COMPLETE: %s: 关闭完成"},
            { 1678, "ER_FORCING_CLOSE: %s: 强制关闭线程%ld 用户: '%-.48s'"},
            { 1679, "ER_IPSOCK_ERROR: 无法创建IP套接字"},
            { 1680, "ER_NO_SUCH_INDEX: 表'%-.192s'没有这样的索引'%-.192s'(算法=复制)"},
            { 1681, "ER_WRONG_FIELD_TERMINATORS: 字段分隔符参数不正确"},
            { 1682, "ER_BLOBS_AND_NO_TERMINATED: 不能使用固定行格式处理BLOB; 请使用字段分隔符"},
            { 1683, "ER_TEXTFILE_NOT_READABLE: 文本文件不可读"},
            { 1684, "ER_FILE_EXISTS_ERROR: 文件'%-.200s'已存在"},
            { 1685, "ER_LOAD_INFO: 记录: %ld 已删除: %ld 跳过: %ld 警告: %ld"},
            { 1686, "ER_ALTER_INFO: 记录: %ld 重复: %ld"},
            { 1687, "ER_WRONG_SUB_KEY: 不正确的子部分键; 使用的键部分不是字符串，使用的长度或键类型"},
            { 1688, "ER_CANT_REMOVE_ALL_FIELDS: 不能删除所有列; 使用DROP TABLE代替"},
            { 1689, "ER_CANT_DROP_FIELD_OR_KEY: 不能删除'%-.192s'; 检查列/键是否存在"},
            { 1690, "ER_INSERT_INFO: 记录: %ld 重复: %ld 警告: %ld"},
            { 1691, "ER_UPDATE_TABLE_USED: 您不能在FROM子句中指定目标表'%-.192s'进行更新"},
            { 1692, "ER_NO_SUCH_THREAD: 未知线程ID: %lu"},
            { 1693, "ER_KILL_DENIED_ERROR: 您不是线程%lu的所有者"},
            { 1694, "ER_NO_TABLES_USED: 没有使用表"},
            { 1695, "ER_TOO_BIG_SET: 列%s和SET的字符串过多"},
            { 1696, "ER_NO_UNIQUE_LOGFILE: 无法生成唯一日志文件名%s.(1-999)"},
            { 1697, "ER_TABLE_NOT_LOCKED_FOR_WRITE: 表'%-.192s'未使用WRITE锁定"},
            { 1698, "ER_TABLE_NOT_LOCKED: 表'%-.192s'未锁定"},
            { 1699, "ER_BLOB_CANT_HAVE_DEFAULT: BLOB/TEXT列'%-.192s'不能有默认值"},
            { 1700, "ER_WRONG_DB_NAME: 不正确的数据库名称'%-.100s'"},
            { 1701, "ER_WRONG_TABLE_NAME: 不正确的表名'%-.100s'"},
            { 1702, "ER_TOO_BIG_SELECT: 选择的列过多"},
            { 1703, "ER_UNKNOWN_ERROR: 未知错误"},
            { 1704, "ER_UNKNOWN_PROCEDURE: 未知过程'%-.192s'"},
            { 1705, "ER_WRONG_PARAMCOUNT_TO_PROCEDURE: 过程'%-.192s'的参数计数不正确"},
            { 1706, "ER_WRONG_PARAMETERS_TO_PROCEDURE: 过程'%-.192s'的参数不正确"},
            { 1707, "ER_UNKNOWN_TABLE: 表'%-.192s'中的未知列'%-.192s'"},
            { 1708, "ER_FIELD_SPECIFIED_TWICE: 列'%-.192s'被指定了两次"},
            { 1709, "ER_INVALID_GROUP_FUNC_USE: 组函数的无效使用"},
            { 1710, "ER_UNSUPPORTED_EXTENSION: 表'%-.192s'使用该扩展中不支持的扩展"},
            { 1711, "ER_TABLE_MUST_HAVE_COLUMNS: 表必须至少有1列"},
            { 1712, "ER_RECORD_FILE_FULL: 表'%-.192s'已满"},
            { 1713, "ER_UNKNOWN_CHARACTER_SET: 未知字符集: '%-.64s'"},
            { 1714, "ER_BINLOG_UNSAFE_INSERT_IGNORE_SELECT: INSERT IGNORE... SELECT不安全，因为SELECT检索行的顺序决定了哪些(如果有)行被忽略。此顺序无法预测，并且可能在主服务器和从服务器上不同"},
            { 1715, "ER_BINLOG_UNSAFE_INSERT_SELECT_UPDATE: INSERT... SELECT... ON DUPLICATE KEY UPDATE不安全，因为SELECT检索行的顺序决定了哪些行被更新。此顺序无法预测，并且可能在主服务器和从服务器上不同"},
            { 1716, "ER_BINLOG_UNSAFE_REPLACE_SELECT: REPLACE... SELECT不安全，因为SELECT检索行的顺序决定了哪些行被替换。此顺序无法预测，并且可能在主服务器和从服务器上不同"},
            { 1717, "ER_BINLOG_UNSAFE_CREATE_IGNORE_SELECT: CREATE... IGNORE... SELECT不安全，因为SELECT检索行的顺序决定了哪些行被忽略。此顺序无法预测，并且可能在主服务器和从服务器上不同"},
            { 1718, "ER_BINLOG_UNSAFE_CREATE_REPLACE_SELECT: CREATE... REPLACE... SELECT不安全，因为SELECT检索行的顺序决定了哪些行被替换。此顺序无法预测，并且可能在主服务器和从服务器上不同"},
            { 1719, "ER_BINLOG_UNSAFE_UPDATE_IGNORE: UPDATE IGNORE不安全，因为行的更新顺序决定了哪些行被忽略。此顺序无法预测，并且可能在主服务器和从服务器上不同"},
            { 1720, "ER_PLUGIN_NO_UNINSTALL: 插件'%s'已标记为不可卸载。您需要先停止服务器才能卸载它"},
            { 1721, "ER_PLUGIN_NO_INSTALL: 插件'%s'已标记为不可安装。您需要先停止服务器才能安装它"},
            { 1722, "ER_BINLOG_UNSAFE_WRITE_AUTOINC_SELECT: 对具有自增列的表执行INSERT... SELECT语句不安全，因为SELECT检索行的顺序决定了哪些行被分配了哪些自增值。此顺序无法预测，并且可能在主服务器和从服务器上不同"},
            { 1723, "ER_BINLOG_UNSAFE_CREATE_SELECT_AUTOINC: 对具有自增列的表执行CREATE... SELECT语句不安全，因为SELECT检索行的顺序决定了哪些行被分配了哪些自增值。此顺序无法预测，并且可能在主服务器和从服务器上不同"},
            { 1724, "ER_BINLOG_UNSAFE_INSERT_TWO_KEYS: INSERT INTO... ON DUPLICATE KEY UPDATE在不安全的语句二进制日志记录模式下不安全，因为受影响的行数无法预测"},
            { 1725, "ER_TABLE_IN_FK_CHECK: 无法在表'%-.192s'上执行操作，因为外键检查正在运行"},
            { 1726, "ER_UNSUPPORTED_ENGINE: 存储引擎'%s'不支持%s"},
            { 1727, "ER_BINLOG_UNSAFE_AUTOINC_NOT_FIRST: 自增列不是表中的第一列时不安全"},
            { 1728, "ER_CANNOT_LOAD_FROM_TABLE_V2: 无法从%s.%s加载。该表可能已损坏"},
            { 1729, "ER_MASTER_DELAY_VALUE_OUT_OF_RANGE: 请求的主服务器延迟值'%ld'超出范围。必须介于0和%ld之间"},
            { 1730, "ER_ONLY_FD_AND_RBR_EVENTS_ALLOWED_IN_BINLOG_STATEMENT: 只有格式描述和行事件允许在BINLOG语句中"},
            { 1731, "ER_PARTITION_EXCHANGE_DIFFERENT_OPTION: 非分区表'%-.64s'和分区表'%-.64s'在分区交换中不共享相同的%s选项"},
            { 1732, "ER_PARTITION_EXCHANGE_PART_TABLE: 表'%-.64s'是分区表。只能与非分区表交换分区"},
            { 1733, "ER_PARTITION_EXCHANGE_TEMP_TABLE: 表'%-.64s'是临时表。不能与分区交换"},
            { 1734, "ER_PARTITION_INSTEAD_OF_SUBPARTITION: 子分区表只能与子分区交换，不能与分区交换"},
            { 1735, "ER_UNKNOWN_PARTITION: 表'%-.192s'中的未知分区'%-.64s'"},
            { 1736, "ER_TABLES_DIFFERENT_METADATA: 表具有不同的定义"},
            { 1737, "ER_ROW_DOES_NOT_MATCH_PARTITION: 找到一行不匹配给定分区"},
            { 1738, "ER_BINLOG_CACHE_SIZE_GREATER_THAN_MAX: 选项binlog_cache_size(%lu)大于max_binlog_cache_size(%lu); 将binlog_cache_size设置为等于max_binlog_cache_size"},
            { 1739, "ER_WARN_INDEX_NOT_APPLICABLE: 由于类型或排序规则转换，无法使用索引%s进行%s访问"},
            { 1740, "ER_PARTITION_EXCHANGE_FOREIGN_KEY: 分区交换不能在外键约束中执行; 表'%-.192s'，约束'%-.64s'"},
            { 1741, "ER_NO_SUCH_KEY_VALUE: 键值'%-.192s'在表'%-.192s'中未找到"},
            { 1742, "ER_RPL_INFO_DATA_TOO_LONG: 数据对于列'%-.192s'过长"},
            { 1743, "ER_NETWORK_READ_EVENT_CHECKSUM_FAILURE: 从网络读取时复制事件校验和失败"},
            { 1744, "ER_BINLOG_READ_EVENT_CHECKSUM_FAILURE: 从二进制日志读取时复制事件校验和失败"},
            { 1745, "ER_BINLOG_STMT_CACHE_SIZE_GREATER_THAN_MAX: 选项binlog_stmt_cache_size(%lu)大于max_binlog_stmt_cache_size(%lu); 将binlog_stmt_cache_size设置为等于max_binlog_stmt_cache_size"},
            { 1746, "ER_CANT_UPDATE_TABLE_IN_CREATE_TABLE_SELECT: 不能在子查询中更新表'%-.192s'，该表也用于CREATE/ALTER TABLE语句的外部查询"},
            { 1747, "ER_PARTITION_CLAUSE_ON_NONPARTITIONED: 非分区表'%-.192s'上的PARTITION子句"},
            { 1748, "ER_ROW_DOES_NOT_MATCH_GIVEN_PARTITION_SET: 行不匹配给定的分区集"},
            { 1749, "ER_NO_SUCH_PARTITION: 表'%-.192s'中的分区'%-.64s'不存在"},
            { 1750, "ER_CHANGE_RPL_INFO_REPOSITORY_FAILURE: 更改复制存储库类型时失败: %s"},
            { 1751, "ER_WARNING_NOT_COMPLETE_ROLLBACK_WITH_CREATED_TEMP_TABLE: 某些临时表的创建无法回滚"},
            { 1752, "ER_WARNING_NOT_COMPLETE_ROLLBACK_WITH_DROPPED_TEMP_TABLE: 某些临时表被删除，但这些操作无法回滚"},
            { 1753, "ER_MTS_FEATURE_IS_NOT_SUPPORTED: %s在多线程从服务器模式下不受支持。%s"},
            { 1754, "ER_MTS_UPDATED_DBS_GREATER_MAX: 修改的数据库数量超过最大值%d; 数据库名称将不包含在复制事件元数据中"},
            { 1755, "ER_MTS_CANT_PARALLEL: 无法在并行模式下执行当前事件组。遇到事件%s，中继日志名称%s，位置%s，这阻止了在并行模式下执行此事件组。原因: %s"},
            { 1756, "ER_MTS_INCONSISTENT_DATA: %s"},
            { 1757, "ER_FULLTEXT_NOT_SUPPORTED_WITH_PARTITIONING: 分区表不支持FULLTEXT索引"},
            { 1758, "ER_DA_INVALID_CONDITION_NUMBER: 无效的条件编号"},
            { 1759, "ER_INSECURE_PLAIN_TEXT: 在不使用SSL/TLS的情况下以明文发送密码极其不安全"},
            { 1760, "ER_INSECURE_CHANGE_MASTER: 在主信息存储库中存储MySQL用户名或密码信息不安全，因此不推荐。请考虑使用START SLAVE的USER和PASSWORD连接选项; 有关更多信息，请参阅MySQL手册中的'START SLAVE语法'"},
            { 1761, "ER_FOREIGN_DUPLICATE_KEY_WITH_CHILD_INFO: 表'%.192s'的外键约束，记录'%-.192s'将导致表'%.192s'中的重复条目，键'%.192s'"},
            { 1762, "ER_FOREIGN_DUPLICATE_KEY_WITHOUT_CHILD_INFO: 表'%.192s'的外键约束，记录'%-.192s'将导致子表中的重复条目"},
            { 1763, "ER_SQLTHREAD_WITH_SECURE_SLAVE: 当仅启动从服务器SQL线程时，无法设置身份验证选项"},
            { 1764, "ER_TABLE_HAS_NO_FT: 表没有FULLTEXT索引来支持此查询"},
            { 1765, "ER_VARIABLE_NOT_SETTABLE_IN_SF_OR_TRIGGER: 系统变量%.200s不能在存储函数或触发器中设置"},
            { 1766, "ER_VARIABLE_NOT_SETTABLE_IN_TRANSACTION: 当有正在进行的事务时，不能设置系统变量%.200s"},
            { 1767, "ER_GTID_NEXT_IS_NOT_IN_GTID_NEXT_LIST: 系统变量@@SESSION.GTID_NEXT的值为%.200s，未在@@SESSION.GTID_NEXT_LIST中列出"},
            { 1768, "ER_CANT_CHANGE_GTID_NEXT_IN_TRANSACTION_WHEN_GTID_NEXT_LIST_IS_NULL: 系统变量@@SESSION.GTID_NEXT不能在事务内部更改"},
            { 1769, "ER_SET_STATEMENT_CANNOT_INVOKE_FUNCTION: 语句'SET %.200s'不能调用存储函数"},
            { 1770, "ER_GTID_NEXT_CANT_BE_AUTOMATIC_IF_GTID_NEXT_LIST_IS_NON_NULL: 当@@SESSION.GTID_NEXT_LIST为非NULL时，系统变量@@SESSION.GTID_NEXT不能为'AUTOMATIC'"},
            { 1771, "ER_SKIPPING_LOGGED_TRANSACTION: 跳过事务%.200s，因为它已被执行并记录"},
            { 1772, "ER_MALFORMED_GTID_SET_SPECIFICATION: 格式错误的GTID集规范'%.200s'"},
            { 1773, "ER_MALFORMED_GTID_SET_ENCODING: 格式错误的GTID集编码"},
            { 1774, "ER_MALFORMED_GTID_SPECIFICATION: 格式错误的GTID规范'%.200s'"},
            { 1775, "ER_GNO_EXHAUSTED: 无法生成全局事务标识符: 整数组件达到最大值。使用新的server_uuid重新启动服务器"},
            { 1776, "ER_BAD_SLAVE_AUTO_POSITION: 当MASTER_AUTO_POSITION处于活动状态时，不能设置参数MASTER_LOG_FILE、MASTER_LOG_POS、RELAY_LOG_FILE和RELAY_LOG_POS"},
            { 1777, "ER_AUTO_POSITION_REQUIRES_GTID_MODE_ON: 只有当@@GLOBAL.GTID_MODE = ON时，才能执行CHANGE MASTER TO MASTER_AUTO_POSITION = 1"},
            { 1778, "ER_CANNOT_DO_IMPLICIT_COMMIT_IN_TRX_WHEN_GTID_NEXT_IS_SET: 当@@SESSION.GTID_NEXT != AUTOMATIC时，不能在事务内部执行具有隐式提交的语句"},
            { 1779, "ER_GTID_MODE_2_OR_3_REQUIRES_ENFORCE_GTID_CONSISTENCY_ON: @@GLOBAL.GTID_MODE = ON或UPGRADE_STEP_2需要@@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1"},
            { 1780, "ER_GTID_MODE_REQUIRES_BINLOG: @@GLOBAL.GTID_MODE = ON或UPGRADE_STEP_1或UPGRADE_STEP_2需要--log-bin和--log-slave-updates"},
            { 1781, "ER_CANT_SET_GTID_NEXT_TO_GTID_WHEN_GTID_MODE_IS_OFF: 当@@GLOBAL.GTID_MODE = OFF时，@@SESSION.GTID_NEXT不能设置为UUID:NUMBER"},
            { 1782, "ER_CANT_SET_GTID_NEXT_TO_ANONYMOUS_WHEN_GTID_MODE_IS_ON: 当@@GLOBAL.GTID_MODE = ON时，@@SESSION.GTID_NEXT不能设置为ANONYMOUS"},
            { 1783, "ER_CANT_SET_GTID_NEXT_LIST_TO_NON_NULL_WHEN_GTID_MODE_IS_OFF: 当@@GLOBAL.GTID_MODE = OFF时，@@SESSION.GTID_NEXT_LIST不能设置为非NULL值"},
            { 1784, "ER_FOUND_GTID_EVENT_WHEN_GTID_MODE_IS_OFF: 当@@GLOBAL.GTID_MODE = OFF时，找到Gtid_log_event或Previous_gtids_log_event"},
            { 1785, "ER_GTID_UNSAFE_NON_TRANSACTIONAL_TABLE: 当@@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1时，对非事务性表的更新只能在自动提交语句或单语句事务中完成，并且永远不能与对事务性表的更新在同一语句中"},
            { 1786, "ER_GTID_UNSAFE_CREATE_SELECT: 当@@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1时，禁止CREATE TABLE ... SELECT"},
            { 1787, "ER_GTID_UNSAFE_CREATE_DROP_TEMPORARY_TABLE_IN_TRANSACTION: 当@@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1时，语句CREATE TEMPORARY TABLE和DROP TEMPORARY TABLE只能在非事务性上下文中执行，并且需要AUTOCOMMIT = 1"},
            { 1788, "ER_GTID_MODE_CAN_ONLY_CHANGE_ONE_STEP_AT_A_TIME: @@GLOBAL.GTID_MODE的值只能一次更改一步: OFF <-> UPGRADE_STEP_1 <-> UPGRADE_STEP_2 <-> ON。另请注意，此值必须在所有服务器上同时递增或递减; 有关说明，请参阅手册"},
            { 1789, "ER_MASTER_HAS_PURGED_REQUIRED_GTIDS: 从服务器使用CHANGE MASTER TO MASTER_AUTO_POSITION = 1连接，但主服务器已清除包含从服务器所需GTID的二进制日志"},
            { 1790, "ER_CANT_SET_GTID_NEXT_WHEN_OWNING_GTID: 拥有GTID的客户端无法更改@@SESSION.GTID_NEXT。客户端拥有%s。所有权在COMMIT或ROLLBACK时释放"},
            { 1791, "ER_UNKNOWN_EXPLAIN_FORMAT: 未知的EXPLAIN格式名称: '%s'"},
            { 1792, "ER_CANT_EXECUTE_IN_READ_ONLY_TRANSACTION: 不能在只读事务中执行语句"},
            { 1793, "ER_TOO_LONG_TABLE_PARTITION_COMMENT: 表分区'%-.64s'的注释过长(最大 = %lu)"},
            { 1794, "ER_SLAVE_CONFIGURATION: 从服务器未配置或未能正确初始化。您必须至少设置--server-id以启用主服务器或从服务器。其他错误消息可以在MySQL错误日志中找到"},
            { 1795, "ER_INNODB_FT_LIMIT: InnoDB目前一次支持一个FULLTEXT索引创建"},
            { 1796, "ER_INNODB_NO_FT_TEMP_TABLE: 不能在临时InnoDB表上创建FULLTEXT索引"},
            { 1797, "ER_INNODB_FT_WRONG_DOCID_COLUMN: 列'%-.192s'的类型错误，不适合InnoDB FULLTEXT索引"},
            { 1798, "ER_INNODB_FT_WRONG_DOCID_INDEX: 索引'%-.192s'的类型错误，不适合InnoDB FULLTEXT索引"},
            { 1799, "ER_INNODB_ONLINE_LOG_TOO_BIG: 创建索引'%-.192s'需要超过'innodb_online_alter_log_max_size'字节的修改日志。请重试"},
            { 1800, "ER_UNKNOWN_ALTER_ALGORITHM: 未知的ALGORITHM '%s'"},
            { 1801, "ER_UNKNOWN_ALTER_LOCK: 未知的LOCK类型'%s'"},
            { 1802, "ER_MTS_CHANGE_MASTER_CANT_RUN_WITH_GAPS: 当从服务器在MTS模式下因错误停止或被杀死时，无法执行CHANGE MASTER。请考虑使用RESET SLAVE或START SLAVE UNTIL"},
            { 1803, "ER_MTS_RECOVERY_FAILURE: 在并行执行模式下从服务器出错后无法恢复。其他错误消息可以在MySQL错误日志中找到"},
            { 1804, "ER_MTS_RESET_WORKERS: 无法清理工作线程信息表。其他错误消息可以在MySQL错误日志中找到"},
            { 1805, "ER_COL_COUNT_DOESNT_MATCH_CORRUPTED_V2: %s.%s的列计数错误。预期%d，找到%d。表可能已损坏"},
            { 1806, "ER_SLAVE_SILENT_RETRY_TRANSACTION: 从服务器必须静默重试当前事务"},
            { 1807, "ER_DISCARD_FK_CHECKS_RUNNING: 表'%-.192s'上正在运行外键检查。无法丢弃该表"},
            { 1808, "ER_TABLE_SCHEMA_MISMATCH: 架构不匹配(%s)"},
            { 1809, "ER_TABLE_IN_SYSTEM_TABLESPACE: 表'%-.192s'在系统表空间中"},
            { 1810, "ER_IO_READ_ERROR: IO读取错误: (%lu, %s) %s"},
            { 1811, "ER_IO_WRITE_ERROR: IO写入错误: (%lu, %s) %s"},
            { 1812, "ER_TABLESPACE_MISSING: 表'%-.192s'的表空间缺失"},
            { 1813, "ER_TABLESPACE_EXISTS: 表'%-.192s'的表空间已存在。请在IMPORT之前DISCARD表空间"},
            { 1814, "ER_TABLESPACE_DISCARDED: 表'%-.192s'的表空间已被丢弃"},
            { 1815, "ER_INTERNAL_ERROR: 内部错误: %s"},
            { 1816, "ER_INNODB_IMPORT_ERROR: ALTER TABLE '%-.192s' IMPORT TABLESPACE失败，错误%lu: '%s'"},
            { 1817, "ER_INNODB_INDEX_CORRUPT: 索引损坏: %s"},
            { 1818, "ER_INVALID_YEAR_COLUMN_LENGTH: YEAR(%lu)列类型已弃用。改为创建YEAR(4)列"},
            { 1819, "ER_NOT_VALID_PASSWORD: 您的密码不满足当前策略要求"},
            { 1820, "ER_MUST_CHANGE_PASSWORD: 在执行此语句之前必须设置密码"},
            { 1821, "ER_FK_NO_INDEX_CHILD: 添加外键约束失败。外部表'%s'中约束'%s'缺少索引"},
            { 1822, "ER_FK_NO_INDEX_PARENT: 添加外键约束失败。引用表'%s'中约束'%s'缺少索引"},
            { 1823, "ER_FK_FAIL_ADD_SYSTEM: 将外键约束'%s'添加到系统表失败"},
            { 1824, "ER_FK_CANNOT_OPEN_PARENT: 无法打开引用表'%s'"},
            { 1825, "ER_FK_INCORRECT_OPTION: 在表'%s'上添加外键约束失败。外键约束'%s'中的选项不正确"},
            { 1826, "ER_FK_DUP_NAME: 重复的外键约束名称'%s'"},
            { 1827, "ER_PASSWORD_FORMAT: 密码哈希没有预期的格式。检查是否使用PASSWORD()函数使用了正确的密码算法"},
            { 1828, "ER_FK_COLUMN_CANNOT_DROP: 无法删除列'%-.192s': 外键约束'%-.192s'中需要"},
            { 1829, "ER_FK_COLUMN_CANNOT_DROP_CHILD: 无法删除列'%-.192s': 表'%-.192s'的外键约束'%-.192s'中需要"},
            { 1830, "ER_FK_COLUMN_NOT_NULL: 列'%-.192s'不能为NOT NULL: 外键约束'%-.192s' SET NULL中需要"},
            { 1831, "ER_DUP_INDEX: 在表'%-.64s.%-.64s'上定义了重复的索引'%-.64s'。这已弃用，将在未来版本中不允许"},
            { 1832, "ER_FK_COLUMN_CANNOT_CHANGE: 无法更改列'%-.192s': 在外键约束'%-.192s'中使用"},
            { 1833, "ER_FK_COLUMN_CANNOT_CHANGE_CHILD: 无法更改列'%-.192s': 在表'%-.192s'的外键约束'%-.192s'中使用"},
            { 1834, "ER_FK_CANNOT_DELETE_PARENT: 无法从作为表'%-.192s'外键约束'%-.192s'的父表中删除行"},
            { 1835, "ER_MALFORMED_PACKET: 格式错误的通信数据包"},
            { 1836, "ER_READ_ONLY_MODE: 在只读模式下运行"},
            { 1837, "ER_GTID_NEXT_TYPE_UNDEFINED_GROUP: 当@@SESSION.GTID_NEXT设置为GTID时，必须在COMMIT或ROLLBACK后显式将其设置为不同的值。请检查GTID_NEXT变量手册页面以获取详细说明。当前@@SESSION.GTID_NEXT为'%s'"},
            { 1838, "ER_VARIABLE_NOT_SETTABLE_IN_SP: 系统变量%.200s不能在存储过程中设置"},
            { 1839, "ER_CANT_SET_GTID_PURGED_WHEN_GTID_MODE_IS_OFF: 只有当@@GLOBAL.GTID_MODE = ON时，才能设置@@GLOBAL.GTID_PURGED"},
            { 1840, "ER_CANT_SET_GTID_PURGED_WHEN_GTID_EXECUTED_IS_NOT_EMPTY: 只有当@@GLOBAL.GTID_EXECUTED为空时，才能设置@@GLOBAL.GTID_PURGED"},
            { 1841, "ER_CANT_SET_GTID_PURGED_WHEN_OWNED_GTIDS_IS_NOT_EMPTY: 只有当没有正在进行的事务时(即使在其他客户端中也没有)，才能设置@@GLOBAL.GTID_PURGED"},
            { 1842, "ER_GTID_PURGED_WAS_CHANGED: @@GLOBAL.GTID_PURGED从'%s'更改为'%s'"},
            { 1843, "ER_GTID_EXECUTED_WAS_CHANGED: @@GLOBAL.GTID_EXECUTED从'%s'更改为'%s'"},
            { 1844, "ER_BINLOG_STT_MODE_AND_NO_REPL_TABLES: 无法执行语句: 由于BINLOG_FORMAT = STATEMENT，无法写入二进制日志，并且同时写入复制和非复制表"},
            { 1845, "ER_ALTER_OPERATION_NOT_SUPPORTED: 此操作不支持%s。请尝试%s"},
            { 1846, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON: 不支持%s。原因: %s。请尝试%s"},
            { 1847, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_COPY: COPY算法需要锁"},
            { 1848, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_PARTITION: 分区特定操作尚不支持LOCK/ALGORITHM"},
            { 1849, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FK_RENAME: 参与外键的列被重命名"},
            { 1850, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_COLUMN_TYPE: 无法原地更改列类型"},
            { 1851, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FK_CHECK: 添加外键需要foreign_key_checks=OFF"},
            { 1852, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_IGNORE: 创建唯一索引时使用IGNORE需要COPY算法来移除重复行"},
            { 1853, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_NOPK: 不允许在没有同时添加新主键的情况下删除主键"},
            { 1854, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_AUTOINC: 添加自增列需要锁"},
            { 1855, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_HIDDEN_FTS: 无法用用户可见的FTS_DOC_ID替换隐藏的FTS_DOC_ID"},
            { 1856, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_CHANGE_FTS: 无法删除或重命名FTS_DOC_ID"},
            { 1857, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FTS: 全文索引创建需要锁"},
            { 1858, "ER_SQL_SLAVE_SKIP_COUNTER_NOT_SETTABLE_IN_GTID_MODE: 当服务器运行在@@GLOBAL.GTID_MODE = ON时，不能设置sql_slave_skip_counter。相反，对于每个要跳过的事务，生成一个具有相同GTID的空事务"},
            { 1859, "ER_DUP_UNKNOWN_IN_INDEX: 键'%-.192s'的重复条目"},
            { 1860, "ER_IDENT_CAUSES_TOO_LONG_PATH: 长数据库名称和对象标识符导致路径长度超过%d个字符。路径: '%s'。"},
            { 1861, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_NOT_NULL: 无法静默转换NULL值，如在此SQL_MODE中所要求"},
            { 1862, "ER_MUST_CHANGE_PASSWORD_LOGIN: 您的密码已过期。要登录，您必须使用支持过期密码的客户端更改它。"},
            { 1863, "ER_ROW_IN_WRONG_PARTITION: 在错误的分区%s中找到一行"},
            { 1864, "ER_MTS_EVENT_BIGGER_PENDING_JOBS_SIZE_MAX: 无法将事件%s，中继日志名称%s，位置%s调度到工作线程，因为其大小%lu超过slave_pending_jobs_size_max的%lu。"},
            { 1865, "ER_INNODB_NO_FT_USES_PARSER: 无法在InnoDB表上使用解析器创建全文索引"},
            { 1866, "ER_BINLOG_LOGICAL_CORRUPTION: 二进制日志文件'%s'逻辑损坏: %s"},
            { 1867, "ER_WARN_PURGE_LOG_IN_USE: 文件%s未被清除，因为它被%d个线程读取，仅清除了%d个文件中的%d个。"},
            { 1868, "ER_WARN_PURGE_LOG_IS_ACTIVE: 文件%s未被清除，因为它是活动日志文件。"},
            { 1869, "ER_AUTO_INCREMENT_CONFLICT: UPDATE中的自增值与内部生成的值冲突"},
            { 1870, "WARN_ON_BLOCKHOLE_IN_RBR: 对于在行格式中修改BLACKHOLE表的%s语句，不记录行事件。表: '%-.192s'"},
            { 1871, "ER_SLAVE_MI_INIT_REPOSITORY: 从服务器未能从存储库初始化主信息结构"},
            { 1872, "ER_SLAVE_RLI_INIT_REPOSITORY: 从服务器未能从存储库初始化中继日志信息结构"},
            { 1873, "ER_ACCESS_DENIED_CHANGE_USER_ERROR: 拒绝访问尝试更改用户'%-.48s'@'%-.64s'(使用密码: %s)。断开连接。"},
            { 1874, "ER_INNODB_READ_ONLY: InnoDB处于只读模式。"},
            { 1875, "ER_STOP_SLAVE_SQL_THREAD_TIMEOUT: STOP SLAVE命令执行不完整: 从服务器SQL线程收到停止信号，线程繁忙，SQL线程将在当前任务完成后停止。"},
            { 1876, "ER_STOP_SLAVE_IO_THREAD_TIMEOUT: STOP SLAVE命令执行不完整: 从服务器IO线程收到停止信号，线程繁忙，IO线程将在当前任务完成后停止。"},
            { 1877, "ER_TABLE_CORRUPT: 无法执行操作。表'%-.64s.%-.64s'缺失、损坏或包含错误数据。"},
            { 1878, "ER_TEMP_FILE_WRITE_FAILURE: 临时文件写入失败。"},
            { 1879, "ER_INNODB_FT_AUX_NOT_HEX_ID: 升级索引名称失败，请使用创建索引(alter table)算法copy来重建索引。"},
            { 1880, "ER_OLD_TEMPORALS_UPGRADED: TIME/TIMESTAMP/DATETIME列的旧格式已升级为新格式。"},
            { 1881, "ER_INNODB_FORCED_RECOVERY: 当innodb_forced_recovery > 0时不允许操作。"},
            { 1882, "ER_AES_INVALID_IV: 提供给%s的初始化向量太短。必须至少%d字节长"},
            { 1883, "ER_PLUGIN_CANNOT_BE_UNINSTALLED: 插件'%s'现在无法卸载。%s"},
            { 1884, "ER_GTID_UNSAFE_BINLOG_SPLITTABLE_STATEMENT_AND_GTID_GROUP: 无法执行语句，因为它需要作为多个语句写入二进制日志，而当@@SESSION.GTID_NEXT == 'UUID:NUMBER'时不允许这样做。"},
            { 1885, "ER_SLAVE_HAS_MORE_GTIDS_THAN_MASTER: 从服务器比主服务器有更多的GTID，使用主服务器的SERVER_UUID。这可能表明二进制日志的末尾被截断或最后一个二进制日志文件丢失，例如，当sync_binlog != 1时发生电源或磁盘故障。主服务器可能回滚了已复制到从服务器的事务，也可能没有。建议将主服务器已回滚的任何从事务复制到主服务器，和/或在主服务器上提交空事务以说明已在主服务器上提交但未包含在GTID_EXECUTED中的事务。"},
            { 1886, "ER_QUERY_TIMEOUT: 查询执行被中断，超过max_statement_time"},
            { 1887, "ER_CANT_EXECUTE_WITH_BACKUP_LOCK: 由于您有冲突的备份锁，无法执行查询"}
        };
    }
}