using System.Collections.Generic;

namespace MyTool
{
    public static partial class ConstString
    {
        // MySQL 错误碼 - 繁體中文
        private static readonly Dictionary<long, string> MySqlErrorsMapTraditionalChinese = new()
        {
            { 1, "操作不允許"},
            { 2, "沒有這樣的檔案或目錄"},
            { 3, "沒有這樣的程序"},
            { 4, "系統呼叫被中斷"},
            { 5, "輸入/輸出錯誤"},
            { 6, "沒有這樣的裝置或位址"},
            { 7, "參數列表過長"},
            { 8, "執行格式錯誤"},
            { 9, "錯誤的檔案描述符"},
            { 10, "沒有子程序"},
            { 11, "資源暫時不可用"},
            { 12, "無法分配記憶體"},
            { 13, "權限被拒絕"},
            { 14, "錯誤的位址"},
            { 15, "需要區塊裝置"},
            { 16, "裝置或資源忙"},
            { 17, "檔案已存在"},
            { 18, "無效的跨裝置連結"},
            { 19, "沒有這樣的裝置"},
            { 20, "不是目錄"},
            { 21, "是目錄"},
            { 22, "無效參數"},
            { 23, "系統中開啟檔案過多"},
            { 24, "開啟檔案過多"},
            { 25, "裝置的不適當ioctl操作"},
            { 26, "文字檔案忙"},
            { 27, "檔案過大"},
            { 28, "裝置上沒有剩餘空間"},
            { 29, "非法尋址"},
            { 30, "唯讀檔案系統"},
            { 31, "連結過多"},
            { 32, "管道破裂"},
            { 33, "數值參數超出定義域"},
            { 34, "數值結果超出範圍"},
            { 35, "資源死鎖已避免"},
            { 36, "檔案名稱過長"},
            { 37, "沒有可用的鎖"},
            { 38, "功能未實現"},
            { 39, "目錄非空"},
            { 40, "符號連結層級過多"},
            { 42, "沒有所需類型的訊息"},
            { 43, "識別符已移除"},
            { 44, "通道號超出範圍"},
            { 45, "第2級未同步"},
            { 46, "第3級已停止"},
            { 47, "第3級已重置"},
            { 48, "連結號超出範圍"},
            { 49, "通訊協定驅動程式未附加"},
            { 50, "沒有可用的CSI結構"},
            { 51, "第2級已停止"},
            { 52, "無效交換"},
            { 53, "無效請求描述符"},
            { 54, "交換已滿"},
            { 55, "沒有陽極"},
            { 56, "無效請求代碼"},
            { 57, "無效插槽"},
            { 59, "錯誤的字型檔案格式"},
            { 60, "裝置不是串流"},
            { 61, "沒有可用資料"},
            { 62, "計時器已過期"},
            { 63, "串流資源耗盡"},
            { 64, "機器不在網路上"},
            { 65, "套件未安裝"},
            { 66, "物件是遠端的"},
            { 67, "連結已被切斷"},
            { 68, "廣告錯誤"},
            { 69, "掛載錯誤"},
            { 70, "傳送時通訊錯誤"},
            { 71, "通訊協定錯誤"},
            { 72, "嘗試多跳"},
            { 73, "RFS特定錯誤"},
            { 74, "錯誤訊息"},
            { 75, "值對於定義的資料類型過大"},
            { 76, "網路上名稱不唯一"},
            { 77, "檔案描述符處於錯誤狀態"},
            { 78, "遠端位址已更改"},
            { 79, "無法存取所需的共享庫"},
            { 80, "存取損壞的共享庫"},
            { 81, "a.out中的.lib節損壞"},
            { 82, "嘗試連結過多共享庫"},
            { 83, "無法直接執行共享庫"},
            { 84, "無效或不完整的多位元組或寬字元"},
            { 85, "系統呼叫被中斷應重新啟動"},
            { 86, "串流管道錯誤"},
            { 87, "使用者過多"},
            { 88, "在非通訊端上進行通訊端操作"},
            { 89, "需要目標位址"},
            { 90, "訊息過長"},
            { 91, "通訊端的通訊協定類型錯誤"},
            { 92, "通訊協定不可用"},
            { 93, "通訊協定不受支援"},
            { 94, "通訊端類型不受支援"},
            { 95, "操作不受支援"},
            { 96, "通訊協定族不受支援"},
            { 97, "通訊協定不支援位址族"},
            { 98, "位址已在使用中"},
            { 99, "無法分配請求的位址"},
            { 100, "網路已關閉"},
            { 101, "網路不可達"},
            { 102, "網路在重置時斷開連接"},
            { 103, "軟體導致連接中止"},
            { 104, "對等方重置連接"},
            { 105, "沒有可用的緩衝區空間"},
            { 106, "傳輸端點已連接"},
            { 107, "傳輸端點未連接"},
            { 108, "傳輸端點關閉後無法傳送"},
            { 109, "引用過多：無法拼接"},
            { 110, "連接逾時"},
            { 111, "連接被拒絕"},
            { 112, "主機已關閉"},
            { 113, "沒有到主機的路由"},
            { 114, "操作已在進展中"},
            { 115, "操作現在在進展中"},
            { 116, "過時的檔案句柄"},
            { 117, "結構需要清理"},
            { 118, "不是XENIX命名類型檔案"},
            { 119, "沒有可用的XENIX信號量"},
            { 120, "讀取或更新時未找到鍵"},
            { 121, "寫入或更新時鍵重複"},
            { 122, "處理程式中的內部（未指定）錯誤"},
            { 123, "自讀取以來有人更改了行（當表被鎖定以防止這種情況時）"},
            { 124, "給函數的索引錯誤"},
            { 125, "未定義的處理程式錯誤125"},
            { 126, "索引檔案已損壞"},
            { 127, "記錄檔案已損壞"},
            { 128, "引擎記憶體不足"},
            { 129, "未定義的處理程式錯誤129"},
            { 130, "不正確的檔案格式"},
            { 131, "資料庫不支援的命令"},
            { 132, "舊的資料庫檔案"},
            { 133, "更新前未讀取記錄"},
            { 134, "記錄已被刪除（或記錄檔案已損壞）"},
            { 135, "記錄檔案中沒有更多空間"},
            { 136, "索引檔案中沒有更多空間"},
            { 137, "沒有更多記錄（在檔案末尾後讀取）"},
            { 138, "表使用了不支援的擴充功能"},
            { 139, "行過大"},
            { 140, "錯誤的建立選項"},
            { 141, "寫入或更新時唯一鍵或約束重複"},
            { 142, "表中使用了未知字元集"},
            { 143, "MERGE表的子表中存在衝突的表定義"},
            { 144, "表已損壞且上次修復失敗"},
            { 145, "表被標記為已損壞應進行修復"},
            { 146, "鎖逾時；重試事務"},
            { 147, "鎖表已滿；使用更大的鎖表重新啟動程式"},
            { 148, "唯讀事務下不允許更新"},
            { 149, "鎖死鎖；重試事務"},
            { 150, "外鍵約束格式不正確"},
            { 151, "無法新增子行"},
            { 152, "無法刪除父行"},
            { 153, "沒有該名稱的儲存點"},
            { 154, "非唯一鍵區塊大小"},
            { 155, "引擎中不存在該表"},
            { 156, "儲存引擎中已存在該表"},
            { 157, "無法連線到儲存引擎"},
            { 158, "使用空間索引時發現意外的空指標"},
            { 159, "儲存引擎中的表已更改"},
            { 160, "表中沒有給定值的分割區"},
            { 161, "基於行的二進位記錄失敗"},
            { 162, "外鍵約束中需要索引"},
            { 163, "維護外鍵約束將導致其他表中的重複鍵錯誤"},
            { 164, "表需要升級才能使用"},
            { 165, "表是唯讀的"},
            { 166, "取得下一個自增值失敗"},
            { 167, "設定行自增值失敗"},
            { 168, "引擎的未知（通用）錯誤"},
            { 169, "記錄相同"},
            { 170, "無法記錄此陳述式"},
            { 171, "事件已損壞導致讀取非法資料"},
            { 172, "表是此版本不支援的新格式"},
            { 173, "事件無法處理沒有其他處理程式錯誤發生"},
            { 174, "處理程式初始化期間發生致命錯誤"},
            { 175, "檔案過短；預期檔案中更多資料"},
            { 176, "讀取校驗和錯誤的頁面"},
            { 177, "活動並行事務過多"},
            { 178, "記錄與給定的分割區集不匹配"},
            { 179, "索引列長度超出限制"},
            { 180, "索引已損壞"},
            { 181, "復原記錄過大"},
            { 182, "無效的InnoDB FTS文件ID"},
            { 183, "表正在用於外鍵檢查"},
            { 184, "表空間已存在"},
            { 185, "列過多"},
            { 186, "行在錯誤的分割區中"},
            { 187, "InnoDB處於唯讀模式"},
            { 188, "FTS查詢超出結果快取記憶體限制"},
            { 189, "暫存檔案寫入失敗"},
            { 190, "當innodb_forced_recovery > 0時不允許操作"},
            { 191, "FTS片語或鄰近搜尋中的單字過多"},
            { 1000, "ER_HASHCHK: hashchk"},
            { 1001, "ER_NISAMCHK: isamchk"},
            { 1002, "ER_NO: 否"},
            { 1003, "ER_YES: 是"},
            { 1004, "ER_CANT_CREATE_FILE: 無法建立檔案'%-.200s'(錯誤號: %d - %s)"},
            { 1005, "ER_CANT_CREATE_TABLE: 無法建立表'%-.200s' (錯誤號: %d)"},
            { 1006, "ER_CANT_CREATE_DB: 無法建立資料庫'%-.192s' (錯誤號: %d)"},
            { 1007, "ER_DB_CREATE_EXISTS: 無法建立資料庫'%-.192s'；資料庫已存在"},
            { 1008, "ER_DB_DROP_EXISTS: 無法刪除資料庫'%-.192s'；資料庫不存在"},
            { 1009, "ER_DB_DROP_DELETE: 刪除資料庫錯誤（無法刪除'%-.192s'，錯誤號: %d)"},
            { 1010, "ER_DB_DROP_RMDIR: 刪除資料庫錯誤（無法刪除目錄'%-.192s'，錯誤號: %d)"},
            { 1011, "ER_CANT_DELETE_FILE: 刪除'%-.192s'時出錯（錯誤號: %d - %s)"},
            { 1012, "ER_CANT_FIND_SYSTEM_REC: 無法讀取系統表中的記錄"},
            { 1013, "ER_CANT_GET_STAT: 無法取得'%-.200s'的狀態（錯誤號: %d - %s)"},
            { 1014, "ER_CANT_GET_WD: 無法取得工作目錄（錯誤號: %d - %s)"},
            { 1015, "ER_CANT_LOCK: 無法鎖定檔案（錯誤號: %d - %s)"},
            { 1016, "ER_CANT_OPEN_FILE: 無法開啟檔案: '%-.200s' (錯誤號: %d - %s)"},
            { 1017, "ER_FILE_NOT_FOUND: 找不到檔案: '%-.200s' (錯誤號: %d - %s)"},
            { 1018, "ER_CANT_READ_DIR: 無法讀取'%-.192s'的目錄（錯誤號: %d - %s)"},
            { 1019, "ER_CANT_SET_WD: 無法變更目錄到'%-.192s'（錯誤號: %d - %s)"},
            { 1020, "ER_CHECKREAD: 自上次讀取以來記錄已在表'%-.192s'中更改"},
            { 1021, "ER_DISK_FULL: 磁碟已滿（%s）；等待有人釋放一些空間...（錯誤號: %d - %s)"},
            { 1022, "ER_DUP_KEY: 無法寫入；表'%-.192s'中的鍵重複"},
            { 1023, "ER_ERROR_ON_CLOSE: 關閉'%-.192s'時出錯（錯誤號: %d - %s)"},
            { 1024, "ER_ERROR_ON_READ: 讀取檔案'%-.200s'時出錯（錯誤號: %d - %s)"},
            { 1025, "ER_ERROR_ON_RENAME: 重新命名'%-.210s'為'%-.210s'時出錯（錯誤號: %d - %s)"},
            { 1026, "ER_ERROR_ON_WRITE: 寫入檔案'%-.200s'時出錯（錯誤號: %d - %s)"},
            { 1027, "ER_FILE_USED: '%-.192s'被鎖定以防止更改"},
            { 1028, "ER_FILSORT_ABORT: 排序已中止"},
            { 1029, "ER_FORM_NOT_FOUND: 檢視'%-.192s'不存在於'%-.192s'"},
            { 1030, "ER_GET_ERRNO: 從儲存引擎收到錯誤%d"},
            { 1031, "ER_ILLEGAL_HA: 表'%-.192s'的儲存引擎沒有此選項"},
            { 1032, "ER_KEY_NOT_FOUND: 在'%-.192s'中找不到記錄"},
            { 1033, "ER_NOT_FORM_FILE: 檔案'%-.200s'中的資訊不正確"},
            { 1034, "ER_NOT_KEYFILE: 表'%-.200s'的鍵檔案不正確；嘗試修復它"},
            { 1035, "ER_OLD_KEYFILE: 表'%-.192s'的舊鍵檔案；修復它！"},
            { 1036, "ER_OPEN_AS_READONLY: 表'%-.192s'是唯讀的"},
            { 1037, "ER_OUTOFMEMORY: 記憶體不足；重啟伺服器並重試（需要%d位元組）"},
            { 1038, "ER_OUT_OF_SORTMEMORY: 排序記憶體不足，考慮增加伺服器排序緩衝區大小"},
            { 1039, "ER_UNEXPECTED_EOF: 讀取檔案'%-.192s'時發現意外的EOF（錯誤號: %d - %s)"},
            { 1040, "ER_CON_COUNT_ERROR: 連線過多"},
            { 1041, "ER_OUT_OF_RESOURCES: 記憶體不足；檢查mysqld或其他程序是否使用了所有可用記憶體；如果沒有，您可能需要使用'ulimit'允許mysqld使用更多記憶體或新增更多交換空間"},
            { 1042, "ER_BAD_HOST_ERROR: 無法取得您位址的主機名稱"},
            { 1043, "ER_HANDSHAKE_ERROR: 握手錯誤"},
            { 1044, "ER_DBACCESS_DENIED_ERROR: 使用者'%-.48s'@'%-.64s'對資料庫'%-.192s'的存取被拒絕"},
            { 1045, "ER_ACCESS_DENIED_ERROR: 使用者'%-.48s'@'%-.64s'的存取被拒絕（使用密碼: %s)"},
            { 1046, "ER_NO_DB_ERROR: 未選擇資料庫"},
            { 1047, "ER_UNKNOWN_COM_ERROR: 未知命令"},
            { 1048, "ER_BAD_NULL_ERROR: 列'%-.192s'不能為null"},
            { 1049, "ER_BAD_DB_ERROR: 未知資料庫'%-.192s'"},
            { 1050, "ER_TABLE_EXISTS_ERROR: 表'%-.192s'已存在"},
            { 1051, "ER_BAD_TABLE_ERROR: 未知表'%-.100s'"},
            { 1052, "ER_NON_UNIQ_ERROR: 列'%-.192s'在%-.192s中不明確"},
            { 1053, "ER_SERVER_SHUTDOWN: 伺服器正在關閉"},
            { 1054, "ER_BAD_FIELD_ERROR: 在'%-.192s'中未知列'%-.192s'"},
            { 1055, "ER_WRONG_FIELD_WITH_GROUP: '%-.192s'不在GROUP BY中"},
            { 1056, "ER_WRONG_GROUP_FIELD: 無法在'%-.192s'上分組"},
            { 1057, "ER_WRONG_SUM_SELECT: 陳述式在同一陳述式中有求和函數和列"},
            { 1058, "ER_WRONG_VALUE_COUNT: 列計數與值計數不匹配"},
            { 1059, "ER_TOO_LONG_IDENT: 識別符名稱'%-.100s'過長"},
            { 1060, "ER_DUP_FIELDNAME: 重複的列名'%-.192s'"},
            { 1061, "ER_DUP_KEYNAME: 重複的鍵名'%-.192s'"},
            { 1062, "ER_DUP_ENTRY: 鍵%d的重複條目'%-.192s'"},
            { 1063, "ER_WRONG_FIELD_SPEC: 列'%-.192s'的列說明符不正確"},
            { 1064, "ER_PARSE_ERROR: %s 在'%-.80s'附近，第%d行"},
            { 1065, "ER_EMPTY_QUERY: 查詢為空"},
            { 1066, "ER_NONUNIQ_TABLE: 不唯一的表/別名: '%-.192s'"},
            { 1067, "ER_INVALID_DEFAULT: '%-.192s'的預設值無效"},
            { 1068, "ER_MULTIPLE_PRI_KEY: 定義了多個主鍵"},
            { 1069, "ER_TOO_MANY_KEYS: 指定的鍵過多；最多允許%d個鍵"},
            { 1070, "ER_TOO_MANY_KEY_PARTS: 指定的鍵部分過多；最多允許%d個部分"},
            { 1071, "ER_TOO_LONG_KEY: 指定的鍵過長；最大鍵長度為%d位元組"},
            { 1072, "ER_KEY_COLUMN_DOES_NOT_EXITS: 鍵列'%-.192s'在表中不存在"},
            { 1073, "ER_BLOB_USED_AS_KEY: BLOB列'%-.192s'不能在使用表類型的鍵規範中使用"},
            { 1074, "ER_TOO_BIG_FIELDLENGTH: 列'%-.192s'的列長度過大（最大 = %lu）；請改用BLOB或TEXT"},
            { 1075, "ER_WRONG_AUTO_KEY: 不正確的表定義；只能有一個自動列且必須定義為鍵"},
            { 1076, "ER_READY: %s: 準備連線。版本: '%s'通訊端: '%s'埠: %d"},
            { 1077, "ER_NORMAL_SHUTDOWN: %s: 正常關閉"},
            { 1078, "ER_GOT_SIGNAL: %s: 收到信號%d。正在中止！"},
            { 1079, "ER_SHUTDOWN_COMPLETE: %s: 關閉完成"},
            { 1080, "ER_FORCING_CLOSE: %s: 強制關閉執行緒%ld使用者: '%-.48s'"},
            { 1081, "ER_IPSOCK_ERROR: 無法建立IP通訊端"},
            { 1082, "ER_NO_SUCH_INDEX: 表'%-.192s'沒有像CREATE INDEX中使用的索引；重新建立表"},
            { 1083, "ER_WRONG_FIELD_TERMINATORS: 欄位分隔符參數不是預期的；請檢查手冊"},
            { 1084, "ER_BLOBS_AND_NO_TERMINATED: 不能將固定行長度與BLOB一起使用；請使用'fields terminated by'"},
            { 1085, "ER_TEXTFILE_NOT_READABLE: 檔案'%-.128s'必須在資料庫目錄中或對所有使用者可讀"},
            { 1086, "ER_FILE_EXISTS_ERROR: 檔案'%-.200s'已存在"},
            { 1087, "ER_LOAD_INFO: 記錄: %ld 已刪除: %ld 已跳過: %ld 警告: %ld"},
            { 1088, "ER_ALTER_INFO: 記錄: %ld 重複: %ld"},
            { 1089, "ER_WRONG_SUB_KEY: 不正確的前綴鍵；使用的鍵部分不是字串，使用的長度長於鍵部分，或者儲存引擎不支援唯一前綴鍵"},
            { 1090, "ER_CANT_REMOVE_ALL_FIELDS: 不能使用ALTER TABLE刪除所有列；請改用DROP TABLE"},
            { 1091, "ER_CANT_DROP_FIELD_OR_KEY: 無法DROP'%-.192s'；檢查列/鍵是否存在"},
            { 1092, "ER_INSERT_INFO: 記錄: %ld 重複: %ld 警告: %ld"},
            { 1093, "ER_UPDATE_TABLE_USED: 不能在FROM子句中為更新指定目標表'%-.192s'"},
            { 1094, "ER_NO_SUCH_THREAD: 未知執行緒ID: %lu"},
            { 1095, "ER_KILL_DENIED_ERROR: 您不是執行緒%lu的所有者"},
            { 1096, "ER_NO_TABLES_USED: 未使用表"},
            { 1097, "ER_TOO_BIG_SET: 列%-.192s和SET的字串過多"},
            { 1098, "ER_NO_UNIQUE_LOGFILE: 無法產生唯一的日誌檔名%-.200s.(1-999)"},
            { 1099, "ER_TABLE_NOT_LOCKED_FOR_WRITE: 表'%-.192s'已用READ鎖鎖定，無法更新"},
            { 1100, "ER_TABLE_NOT_LOCKED: 表'%-.192s'未用LOCK TABLES鎖定"},
            { 1101, "ER_BLOB_CANT_HAVE_DEFAULT: BLOB/TEXT列'%-.192s'不能有預設值"},
            { 1102, "ER_WRONG_DB_NAME: 不正確的資料庫名稱'%-.100s'"},
            { 1103, "ER_WRONG_TABLE_NAME: 不正確的表名稱'%-.100s'"},
            { 1104, "ER_TOO_BIG_SELECT: SELECT將檢查超過MAX_JOIN_SIZE的行；檢查您的WHERE並使用SET SQL_BIG_SELECTS=1或SET MAX_JOIN_SIZE=#如果SELECT正常"},
            { 1105, "ER_UNKNOWN_ERROR: 未知錯誤"},
            { 1106, "ER_UNKNOWN_PROCEDURE: 未知程序'%-.192s'"},
            { 1107, "ER_WRONG_PARAMCOUNT_TO_PROCEDURE: 程序'%-.192s'的參數計數不正確"},
            { 1108, "ER_WRONG_PARAMETERS_TO_PROCEDURE: 程序'%-.192s'的參數不正確"},
            { 1109, "ER_UNKNOWN_TABLE: 在%-.32s中未知表'%-.192s'"},
            { 1110, "ER_FIELD_SPECIFIED_TWICE: 列'%-.192s'被指定了兩次"},
            { 1111, "ER_INVALID_GROUP_FUNC_USE: 分組函數的無效使用"},
                        { 1112, "ER_UNSUPPORTED_EXTENSION: 表'%-.192s'使用了此MySQL版本中不存在的擴充功能"},
            { 1113, "ER_TABLE_MUST_HAVE_COLUMNS: 表必須至少有一列"},
            { 1114, "ER_RECORD_FILE_FULL: 表'%-.192s'已滿"},
            { 1115, "ER_UNKNOWN_CHARACTER_SET: 未知字元集: '%-.64s'"},
            { 1116, "ER_TOO_MANY_TABLES: 表過多; MySQL只能在一個查詢中使用%d個表"},
            { 1117, "ER_TOO_MANY_FIELDS: 列過多"},
            { 1118, "ER_TOO_BIG_ROWSIZE: 行大小過大。表'%-.192s'的最大行大小(不包括BLOB)是%lu。您必須將某些列更改為TEXT或BLOB"},
            { 1119, "ER_STACK_OVERRUN: 執行緒堆疊溢位: 已使用: %ld堆疊的%d。如果需要，請使用'mysqld --thread_stack=#'指定更大的堆疊"},
            { 1120, "ER_WRONG_OUTER_JOIN: 在OUTER JOIN中發現交叉依賴; 檢查您的ON條件"},
            { 1121, "ER_NULL_COLUMN_IN_INDEX: 表'%-.192s'的列'%-.192s'用於鍵規範而沒有NOT NULL標誌"},
            { 1122, "ER_CANT_FIND_UDF: 無法載入函數'%-.192s'"},
            { 1123, "ER_CANT_INITIALIZE_UDF: 無法初始化函數'%-.192s'; %s"},
            { 1124, "ER_UDF_NO_PATHS: 不允許UDF的路徑"},
            { 1125, "ER_UDF_EXISTS: 函數'%-.192s'已存在"},
            { 1126, "ER_CANT_OPEN_LIBRARY: 無法開啟共享庫'%-.192s' (錯誤號: %d %s)"},
            { 1127, "ER_CANT_FIND_DL_ENTRY: 無法在庫中找到符號'%-.192s'"},
            { 1128, "ER_FUNCTION_NOT_DEFINED: 函數'%-.192s'未定義"},
            { 1129, "ER_HOST_IS_BLOCKED: 主機'%-.64s'被阻止，因為有太多連接錯誤; 使用'mysqladmin flush-hosts'解除阻止"},
            { 1130, "ER_HOST_NOT_PRIVILEGED: 主機'%-.64s'未被允許連線到此MySQL伺服器"},
            { 1131, "ER_PASSWORD_ANONYMOUS_USER: 您正在使用MySQL作為匿名使用者，不允許匿名使用者更改密碼"},
            { 1132, "ER_PASSWORD_NOT_ALLOWED: 您必須有更新mysql資料庫中表的權限才能更改密碼"},
            { 1133, "ER_PASSWORD_NO_MATCH: 無法在任何使用者表中找到匹配的行來重設密碼"},
            { 1134, "ER_UPDATE_INFO: 記錄: %ld 重複: %ld 警告: %ld"},
            { 1135, "ER_CANT_CREATE_THREAD: 無法建立新執行緒 (錯誤號 %d); 如果您沒有可用記憶體，可以檢查mysqld或作業系統文件"},
            { 1136, "ER_WRONG_VALUE_COUNT_ON_ROW: 列計數與第%ld行的值計數不匹配"},
            { 1137, "ER_CANT_REOPEN_TABLE: 無法重新開啟表'%-.192s'"},
            { 1138, "ER_INVALID_USE_OF_NULL: NULL值使用無效"},
            { 1139, "ER_REGEXP_ERROR: 從正規表示式得到錯誤"},
            { 1140, "ER_MIX_OF_GROUP_FUNC_AND_FIELDS: 在沒有GROUP BY的列中混合了分組函數和列"},
            { 1141, "ER_NONEXISTING_GRANT: 使用者'%-.48s'@'%-.64s'沒有指定操作的特權"},
            { 1142, "ER_TABLEACCESS_DENIED_ERROR: 使用者'%-.48s'@'%-.64s'對表'%-.192s'的%-.16s被拒絕"},
            { 1143, "ER_COLUMNACCESS_DENIED_ERROR: 使用者'%-.48s'@'%-.64s'對表'%-.192s'的列'%-.192s'的%-.16s被拒絕"},
            { 1144, "ER_ILLEGAL_GRANT_FOR_TABLE: 此GRANT或REVOKE語句中指定的GRANT特權非法"},
            { 1145, "ER_GRANT_WRONG_HOST_OR_USER: GRANT的主機或用戶部分非法"},
            { 1146, "ER_NO_SUCH_TABLE: 表'%-.192s.%-.192s'不存在"},
            { 1147, "ER_NONEXISTING_TABLE_GRANT: 使用者'%-.48s'@'%-.64s'沒有表'%-.192s'的GRANT特權"},
            { 1148, "ER_NOT_ALLOWED_COMMAND: 此MySQL版本不允許使用的命令"},
            { 1149, "ER_SYNTAX_ERROR: 您有SQL語法錯誤; 檢查與您的MySQL伺服器版本對應的手冊，以了解在第%d行'%-.80s'附近使用的正確語法"},
            { 1150, "ER_DELAYED_CANT_CHANGE_LOCK: 對於延遲插入，無法更改鎖定類型"},
            { 1151, "ER_TOO_MANY_DELAYED_THREADS: 使用的延遲執行緒過多"},
            { 1152, "ER_ABORTING_CONNECTION: 中止連接%ld到資料庫: '%-.192s'使用者: '%-.48s' (%s)"},
            { 1153, "ER_NET_PACKET_TOO_LARGE: 從%s收到的包大於'max_allowed_packet'位元組"},
            { 1154, "ER_NET_READ_ERROR_FROM_PIPE: 從管道讀取時出錯"},
            { 1155, "ER_NET_FCNTL_ERROR: 在%s上獲取fcntl時出錯"},
            { 1156, "ER_NET_PACKETS_OUT_OF_ORDER: 從%s收到的包無序"},
            { 1157, "ER_NET_UNCOMPRESS_ERROR: 從%s解壓縮通訊時出錯"},
            { 1158, "ER_NET_READ_ERROR: 從%s讀取時出錯"},
            { 1159, "ER_NET_READ_INTERRUPTED: 從%s讀取時被中斷"},
            { 1160, "ER_NET_ERROR_ON_WRITE: 寫入%s時出錯"},
            { 1161, "ER_NET_WRITE_INTERRUPTED: 寫入%s時被中斷"},
            { 1162, "ER_TOO_LONG_STRING: 結果字串長於'max_allowed_packet'位元組"},
            { 1163, "ER_TABLE_CANT_HANDLE_BLOB: 使用的表類型不支援BLOB/TEXT列"},
            { 1164, "ER_TABLE_CANT_HANDLE_AUTO_INCREMENT: 使用的表類型不支援AUTO_INCREMENT列"},
            { 1165, "ER_DELAYED_INSERT_TABLE_LOCKED: 由於表被鎖定，INSERT DELAYED無法使用"},
            { 1166, "ER_WRONG_COLUMN_NAME: 不正確的列名'%-.100s'"},
            { 1167, "ER_WRONG_KEY_COLUMN: 使用的儲存引擎無法索引列'%-.192s'"},
            { 1168, "ER_WRONG_MRG_TABLE: 無法開啟表; MERGE表中的所有表必須具有相同的結構"},
            { 1169, "ER_DUP_UNIQUE: 由於唯一約束，無法寫入表'%-.192s'"},
            { 1170, "ER_BLOB_KEY_WITHOUT_LENGTH: 在沒有鍵長度的鍵規範中使用了BLOB/TEXT列'%-.192s'"},
            { 1171, "ER_PRIMARY_CANT_HAVE_NULL: 主鍵的所有部分必須是NOT NULL; 如果需要NULL鍵，請使用UNIQUE索引"},
            { 1172, "ER_TOO_MANY_ROWS: 結果包含多於一行"},
            { 1173, "ER_REQUIRES_PRIMARY_KEY: 此表類型需要主鍵"},
            { 1174, "ER_NO_RAID_COMPILED: 此MySQL版本未使用RAID支援編譯"},
            { 1175, "ER_UPDATE_WITHOUT_KEY_IN_SAFE_MODE: 您正在使用安全更新模式，並且嘗試更新沒有使用KEY列的WHERE的表"},
            { 1176, "ER_KEY_DOES_NOT_EXITS: 鍵'%-.192s'不存在於表'%-.192s'中"},
            { 1177, "ER_CHECK_NO_SUCH_TABLE: 無法開啟表"},
            { 1178, "ER_CHECK_NOT_IMPLEMENTED: 表的引擎不支援%s"},
            { 1179, "ER_CANT_DO_THIS_DURING_AN_TRANSACTION: 您無法在事務中執行此操作"},
            { 1180, "ER_ERROR_DURING_COMMIT: 在提交期間出錯%d"},
            { 1181, "ER_ERROR_DURING_ROLLBACK: 在回滾期間出錯%d"},
            { 1182, "ER_ERROR_DURING_FLUSH_LOGS: 在刷新日誌期間出錯%d"},
            { 1183, "ER_ERROR_DURING_CHECKPOINT: 在檢查點期間出錯%d"},
            { 1184, "ER_NEW_ABORTING_CONNECTION: 中止連接%ld到資料庫: '%-.192s'使用者: '%-.48s'主機: '%-.64s' (%s)"},
            { 1185, "ER_DUMP_NOT_IMPLEMENTED: 表的儲存引擎不支援二進位表轉儲"},
            { 1186, "ER_FLUSH_MASTER_BINLOG_CLOSED: 由於主二進位日誌關閉，Binlog已關閉"},
            { 1187, "ER_INDEX_REBUILD: 失敗重建表'%-.192s'的索引"},
            { 1188, "ER_MASTER: 來自主機'%-.64s'的錯誤"},
            { 1189, "ER_MASTER_NET_READ: 從主機讀取時網路錯誤"},
            { 1190, "ER_MASTER_NET_WRITE: 寫入主機時網路錯誤"},
            { 1191, "ER_FT_MATCHING_KEY_NOT_FOUND: 無法找到與列列表匹配的全文索引"},
            { 1192, "ER_LOCK_OR_ACTIVE_TRANSACTION: 無法執行給定的命令，因為您有活動的鎖定表或活動的事務"},
            { 1193, "ER_UNKNOWN_SYSTEM_VARIABLE: 未知系統變數'%-.64s'"},
            { 1194, "ER_CRASHED_ON_USAGE: 表'%-.192s'被標記為已損壞，應修復"},
            { 1195, "ER_CRASHED_ON_REPAIR: 表'%-.192s'被標記為已損壞，上次修復失敗"},
            { 1196, "ER_WARNING_NOT_COMPLETE_ROLLBACK: 某些非事務性更改的事務回滾未回滾"},
            { 1197, "ER_TRANS_CACHE_FULL: 多語句事務需要更多的'max_binlog_cache_size'位元組儲存; 增加mysqld變數並重新啟動事務"},
            { 1198, "ER_SLAVE_MUST_STOP: 此操作無法在運行時執行; 先運行SLAVE STOP"},
            { 1199, "ER_SLAVE_NOT_RUNNING: 此操作需要運行的從伺服器; 配置從伺服器並使用SLAVE START啟動它"},
            { 1200, "ER_BAD_SLAVE: 伺服器未配置為從伺服器; 在配置文件中或使用CHANGE MASTER TO修復"},
            { 1201, "ER_MASTER_INFO: 無法初始化主資訊結構; 更多錯誤訊息可以在MySQL錯誤日誌中找到"},
            { 1202, "ER_SLAVE_THREAD: 無法建立從執行緒; 檢查系統資源"},
            { 1203, "ER_TOO_MANY_USER_CONNECTIONS: 使用者%s已超過'max_user_connections'資源"},
            { 1204, "ER_SET_CONSTANTS_ONLY: 您只能將常量表達式與SET一起使用"},
            { 1205, "ER_LOCK_WAIT_TIMEOUT: 鎖等待逾時; 嘗試重新啟動事務"},
            { 1206, "ER_LOCK_TABLE_FULL: 鎖表已滿"},
            { 1207, "ER_READ_ONLY_TRANSACTION: 更新期間的讀取鎖定; 嘗試重新啟動事務"},
            { 1208, "ER_DROP_DB_WITH_READ_LOCK: 當全域讀取鎖定處於活動狀態時，不允許DROP DATABASE"},
            { 1209, "ER_CREATE_DB_WITH_READ_LOCK: 當全域讀取鎖定處於活動狀態時，不允許CREATE DATABASE"},
            { 1210, "ER_WRONG_ARGUMENTS: 對%s的參數不正確"},
            { 1211, "ER_NO_PERMISSION_TO_CREATE_USER: 不允許建立使用者'%-.48s'@'%-.64s'"},
            { 1212, "ER_UNION_TABLES_IN_DIFFERENT_DIR: 不正確的表格定義; 所有合併表必須位於同一資料庫中"},
            { 1213, "ER_LOCK_DEADLOCK: 死鎖發現時嘗試獲取鎖; 嘗試重新啟動事務"},
            { 1214, "ER_TABLE_CANT_HANDLE_FT: 使用的表類型不支援全文索引"},
            { 1215, "ER_CANNOT_ADD_FOREIGN: 無法新增外鍵約束"},
            { 1216, "ER_NO_REFERENCED_ROW: 無法新增或更新子行: 外鍵約束失敗"},
            { 1217, "ER_ROW_IS_REFERENCED: 無法刪除或更新父行: 外鍵約束失敗"},
            { 1218, "ER_CONNECT_TO_MASTER: 連線到主機時出錯: %s"},
            { 1219, "ER_QUERY_ON_MASTER: 在主機上執行查詢時出錯: %s"},
            { 1220, "ER_ERROR_WHEN_EXECUTING_COMMAND: 執行命令%s時出錯: %s"},
            { 1221, "ER_WRONG_USAGE: %s和%s的用法不正確"},
            { 1222, "ER_WRONG_NUMBER_OF_COLUMNS_IN_SELECT: 使用的SELECT語句具有不同的列數"},
            { 1223, "ER_CANT_UPDATE_WITH_READLOCK: 無法執行查詢，因為您有活動的讀取鎖定"},
            { 1224, "ER_MIXING_NOT_ALLOWED: 不允許混合事務性和非事務性表"},
            { 1225, "ER_DUP_ARGUMENT: 選項'%s'在指令行中使用多次"},
            { 1226, "ER_USER_LIMIT_REACHED: 使用者'%s'已超過'%s'資源（當前值: %ld）"},
            { 1227, "ER_SPECIFIC_ACCESS_DENIED_ERROR: 存取被拒絕; 您需要（至少一個）%s特權才能執行此操作"},
            { 1228, "ER_LOCAL_VARIABLE: 會話變數'%s'是只讀的"},
            { 1229, "ER_GLOBAL_VARIABLE: 全域變數'%s'是只讀的"},
            { 1230, "ER_NO_DEFAULT: 變數'%s'沒有預設值"},
            { 1231, "ER_WRONG_VALUE_FOR_VAR: 變數'%s'不能設置為值'%s'"},
            { 1232, "ER_WRONG_TYPE_FOR_VAR: 變數'%s'的參數類型不正確"},
            { 1233, "ER_VAR_CANT_BE_READ: 變數'%s'只能設置，不能讀取"},
            { 1234, "ER_CANT_USE_OPTION_HERE: 不正確使用%s"},
            { 1235, "ER_NOT_SUPPORTED_YET: 此MySQL版本尚不支援'%s'"},
            { 1236, "ER_MASTER_FATAL_ERROR_READING_BINLOG: 從二進位日誌讀取資料時，主伺服器發生致命錯誤: %s"},
            { 1237, "ER_SLAVE_IGNORED_TABLE: 從伺服器SQL執行緒忽略查詢，因為複製已在此表上定義: %s"},
            { 1238, "ER_INCORRECT_GLOBAL_LOCAL_VAR: 變數'%s'是%s變數"},
            { 1239, "ER_WRONG_FK_DEF: 外鍵定義不正確: %s"},
            { 1240, "ER_KEY_REF_DO_NOT_MATCH_TABLE_REF: 鍵引用和表引用不匹配"},
            { 1241, "ER_OPERAND_COLUMNS: 運算元應包含%d列"},
            { 1242, "ER_SUBQUERY_NO_1_ROW: 子查詢返回多於一行"},
            { 1243, "ER_UNKNOWN_STMT_HANDLER: 未知的預處理語句處理程式（%lu）"},
            { 1244, "ER_CORRUPT_HELP_DB: 幫助資料庫已損壞或不存在"},
            { 1245, "ER_CYCLIC_REFERENCE: 循環引用"},
            { 1246, "ER_AUTO_CONVERT: 將列'%s'從%s轉換為%s"},
            { 1247, "ER_ILLEGAL_REFERENCE: 引用'%s'不支持"},
            { 1248, "ER_DERIVED_MUST_HAVE_ALIAS: 每個派生表必須有自己的別名"},
            { 1249, "ER_SELECT_REDUCED: 選擇%d被優化掉在優化期間"},
            { 1250, "ER_TABLENAME_NOT_ALLOWED_HERE: 表'%s'不允許來自%s中的SELECT中的'%s'"},
            { 1251, "ER_NOT_SUPPORTED_AUTH_MODE: 客戶端不支援伺服器請求的驗證協議; 考慮升級MySQL客戶端"},
            { 1252, "ER_SPATIAL_CANT_HAVE_NULL: 所有空間索引的列必須是NOT NULL"},
            { 1253, "ER_COLLATION_CHARSET_MISMATCH: 無效的%s字符集: '%s'"},
            { 1254, "ER_SLAVE_WAS_RUNNING: 從伺服器正在運行，因此無法執行此操作"},
            { 1255, "ER_SLAVE_WAS_NOT_RUNNING: 從伺服器未運行，因此無法執行此操作"},
            { 1256, "ER_TOO_BIG_FOR_UNCOMPRESS: 未壓縮的資料太大; 最大大小為%d（可能，未壓縮的長度已損壞）"},
            { 1257, "ER_ZLIB_Z_MEM_ERROR: ZLIB: 記憶體不足"},
            { 1258, "ER_ZLIB_Z_BUF_ERROR: ZLIB: 輸出緩衝區不足（可能，未壓縮的長度已損壞）"},
            { 1259, "ER_ZLIB_Z_DATA_ERROR: ZLIB: 輸入資料已損壞"},
            { 1260, "ER_CUT_VALUE_GROUP_CONCAT: 行%ld被GROUP_CONCAT()截斷"},
            { 1261, "ER_WARN_TOO_FEW_RECORDS: 行%ld不包含所有列的資料"},
            { 1262, "ER_WARN_TOO_MANY_RECORDS: 行%ld被截斷; 它包含的資料多於輸入列"},
            { 1263, "ER_WARN_NULL_TO_NOTNULL: 列被設置為預設值; 在行%ld為NOT NULL列提供NULL"},
            { 1264, "ER_WARN_DATA_OUT_OF_RANGE: 行%ld中列'%s'的值超出範圍"},
            { 1265, "ER_WARN_DATA_TRUNCATED: 行%ld中列'%s'的資料被截斷"},
            { 1266, "ER_WARN_USING_OTHER_HANDLER: 使用儲存引擎%s作為表'%s'"},
            { 1267, "ER_CANT_AGGREGATE_2COLLATIONS: 操作'%s'的非法混合排序(%s,%s)和(%s,%s)"},
            { 1268, "ER_DROP_USER: 無法刪除一個或多個請求的使用者"},
            { 1269, "ER_REVOKE_GRANTS: 無法撤銷一個或多個請求使用者的所有特權"},
            { 1270, "ER_CANT_AGGREGATE_3COLLATIONS: 操作'%s'的非法混合排序(%s,%s)、(%s,%s)和(%s,%s)"},
            { 1271, "ER_CANT_AGGREGATE_NCOLLATIONS: 操作'%s'的非法混合排序"},
            { 1272, "ER_VARIABLE_IS_NOT_STRUCT: 變數'%s'不是變數組件（不能用作XXXX.variable_name）"},
            { 1273, "ER_UNKNOWN_COLLATION: 未知排序規則: '%s'"},
            { 1274, "ER_SLAVE_IGNORED_SSL_PARAMS: SSL參數在CHANGE MASTER中被忽略，因為此MySQL版本未使用SSL支援編譯"},
            { 1275, "ER_SERVER_IS_IN_SECURE_AUTH_MODE: 伺服器正在執行--secure-auth模式，但'%s'@'%s'有舊密碼; 請更改密碼以使用更安全的驗證方法"},
            { 1276, "ER_WARN_FIELD_RESOLVED: 字段或參考'%s%s%s%s%s'在SELECT %d中解析"},
            { 1277, "ER_BAD_SLAVE_UNTIL_COND: 不正確的參數或直到條件組合"},
            { 1278, "ER_MISSING_SKIP_SLAVE: 執行START SLAVE UNTIL時，建議也使用--skip-slave-start，否則如果發生意外重新啟動，可能會出現問題"},
            { 1279, "ER_UNTIL_COND_IGNORED: SQL執行緒完全啟動，直到條件被忽略"},
            { 1280, "ER_WRONG_NAME_FOR_INDEX: 索引名稱'%s'不正確"},
            { 1281, "ER_WRONG_NAME_FOR_CATALOG: 目錄名稱'%s'不正確"},
            { 1282, "ER_WARN_QC_RESIZE: 查詢緩存未能設置大小%lu; 新的查詢緩存大小是%lu"},
            { 1283, "ER_BAD_FT_COLUMN: 列'%s'不能用於全文索引"},
            { 1284, "ER_UNKNOWN_KEY_CACHE: 未知的鍵緩存'%s'"},
            { 1285, "ER_WARN_HOSTNAME_WONT_WORK: MySQL已使用'--skip-name-resolve'啟動; 您必須在授權表中使用IP而不是名稱重新建立它們"},
            { 1286, "ER_UNKNOWN_STORAGE_ENGINE: 未知的儲存引擎'%s'"},
            { 1287, "ER_WARN_DEPRECATED_SYNTAX: '%s'已棄用; 請使用%s代替"},
            { 1288, "ER_NON_UPDATABLE_TABLE: 目標表%s的%s不可更新"},
            { 1289, "ER_FEATURE_DISABLED: '%s'功能已禁用; 您需要MySQL內建%s支援"},
            { 1290, "ER_OPTION_PREVENTS_STATEMENT: MySQL伺服器正在使用%s選項運行，因此無法執行此語句"},
            { 1291, "ER_DUPLICATED_VALUE_IN_TYPE: 列'%s'在%s中有重複值'%s'"},
            { 1292, "ER_TRUNCATED_WRONG_VALUE: 截斷不正確的%s值: '%s'"},
            { 1293, "ER_TOO_MUCH_AUTO_TIMESTAMP_COLS: 不正確的表定義; 只能有一個TIMESTAMP列使用CURRENT_TIMESTAMP作為DEFAULT或ON UPDATE"},
            { 1294, "ER_INVALID_ON_UPDATE: 列'%s'的ON UPDATE子句無效"},
            { 1295, "ER_UNSUPPORTED_PS: 此命令在此MySQL版本中尚不支援預處理語句"},
            { 1296, "ER_GET_ERRMSG: 從%s得到錯誤%d '%s'"},
            { 1297, "ER_GET_TEMPORARY_ERRMSG: 從%s得到臨時錯誤%d '%s'"},
            { 1298, "ER_UNKNOWN_TIME_ZONE: 未知或不正確的時區: '%s'"},
            { 1299, "ER_WARN_INVALID_TIMESTAMP: 在行%ld中為列'%s'指定了無效的TIMESTAMP值"},
            { 1300, "ER_INVALID_CHARACTER_STRING: 無效的%s字符串: '%s'"},
            { 1301, "ER_WARN_ALLOWED_PACKET_OVERFLOWED: 結果大於max_allowed_packet位元組 - %ld"},
            { 1302, "ER_CONFLICTING_DECLARATIONS: 衝突的聲明: '%s%s'和'%s%s'"},
            { 1303, "ER_SP_NO_RECURSIVE_CREATE: 無法從另一個儲存程序建立%s"},
            { 1304, "ER_SP_ALREADY_EXISTS: %s %s已存在"},
            { 1305, "ER_SP_DOES_NOT_EXIST: %s %s不存在"},
            { 1306, "ER_SP_DROP_FAILED: 刪除%s %s失敗"},
            { 1307, "ER_SP_STORE_FAILED: 建立%s %s失敗"},
            { 1308, "ER_SP_LILABEL_MISMATCH: %s: 無匹配標籤: %s"},
            { 1309, "ER_SP_LABEL_REDEFINE: %s: 重新定義標籤%s"},
            { 1310, "ER_SP_LABEL_MISMATCH: %s: 結束標籤%s無匹配的開始標籤"},
            { 1311, "ER_SP_UNINIT_VAR: 在存儲程序中引用未初始化的變數%s"},
            { 1312, "ER_SP_BADSELECT: 過程%s返回結果集但沒有OUT參數中的游標"},
            { 1313, "ER_SP_BADRETURN: 在函數中不允許RETURN"},
            { 1314, "ER_SP_BADSTATEMENT: 在存儲程序中不允許%s"},
            { 1315, "ER_UPDATE_LOG_DEPRECATED_IGNORED: 更新日誌已棄用，並被二進位日誌取代; 設置sql_log_update被忽略"},
            { 1316, "ER_UPDATE_LOG_DEPRECATED_TRANSLATED: 更新日誌已棄用，並被二進位日誌取代; 使用二進位日誌記錄更新"},
            { 1317, "ER_QUERY_INTERRUPTED: 查詢執行被中斷"},
            { 1318, "ER_SP_WRONG_NO_OF_ARGS: 不正確的參數計數給%s %s; 預期%d，得到%d"},
            { 1319, "ER_SP_COND_MISMATCH: 未定義條件%s"},
            { 1320, "ER_SP_NORETURN: 在函數%s中未找到RETURN"},
            { 1321, "ER_SP_NORETURNEND: 函數%s結束時沒有RETURN"},
            { 1322, "ER_SP_BAD_CURSOR_QUERY: 游標語句必須是SELECT"},
            { 1323, "ER_SP_BAD_CURSOR_SELECT: 游標SELECT不得有INTO"},
            { 1324, "ER_SP_CURSOR_MISMATCH: 未定義游標%s"},
            { 1325, "ER_SP_CURSOR_ALREADY_OPEN: 游標%s已打開"},
            { 1326, "ER_SP_CURSOR_NOT_OPEN: 游標%s未打開"},
            { 1327, "ER_SP_UNDECLARED_VAR: 未聲明的變數%s"},
            { 1328, "ER_SP_WRONG_NO_OF_FETCH_ARGS: 不正確的提取計數"},
            { 1329, "ER_SP_FETCH_NO_DATA: 無資料 - 提取、選擇或處理零行"},
            { 1330, "ER_SP_DUP_PARAM: 重複參數: %s"},
            { 1331, "ER_SP_DUP_VAR: 重複變數: %s"},
            { 1332, "ER_SP_DUP_COND: 重複條件: %s"},
            { 1333, "ER_SP_DUP_CURSOR: 重複游標: %s"},
            { 1334, "ER_SP_CANT_ALTER: 無法更改%s %s"},
            { 1335, "ER_SP_SUBSELECT_NYI: 子選擇尚不支援在存儲程序中"},
            { 1336, "ER_STMT_NOT_ALLOWED_IN_SF_OR_TRG: %s不允許在存儲函數或觸發器中"},
            { 1337, "ER_SP_VARCOND_AFTER_CURSHNDLR: 變數或條件聲明在游標或處理程式聲明之後"},
            { 1338, "ER_SP_CURSOR_AFTER_HANDLER: 游標聲明在處理程式聲明之後"},
            { 1339, "ER_SP_CASE_NOT_FOUND: 未找到CASE語句的案例"},
            { 1340, "ER_SP_CASE_NOT_FOUND_WARNING: 未找到CASE語句的案例"},
            { 1341, "ER_FPARSER_TOO_BIG_FILE: 配置文件'%s'太大"},
            { 1342, "ER_FPARSER_BAD_HEADER: 配置文件'%s'的標頭不正確"},
            { 1343, "ER_FPARSER_EOF_IN_COMMENT: 配置文件'%s'中註解中意外的文件結束"},
            { 1344, "ER_FPARSER_ERROR_IN_PARAMETER: 配置文件'%s'中參數錯誤"},
            { 1345, "ER_FPARSER_EOF_IN_UNKNOWN_PARAMETER: 配置文件'%s'中未知參數中意外的文件結束"},
            { 1346, "ER_VIEW_NO_EXPLAIN: 無法在SELECT中顯示EXPLAIN"},
            { 1347, "ER_WRONG_OBJECT: '%s.%s'不是%s"},
            { 1348, "ER_NONUPDATEABLE_COLUMN: 列'%s'不可更新"},
            { 1349, "ER_VIEW_SELECT_DERIVED: 視圖的SELECT包含子查詢中的子句"},
            { 1350, "ER_VIEW_SELECT_CLAUSE: 視圖的SELECT包含'%s'子句"},
            { 1351, "ER_VIEW_SELECT_VARIABLE: 視圖的SELECT包含變數或參數"},
            { 1352, "ER_VIEW_SELECT_TMPTABLE: 視圖的SELECT包含臨時表'%s'"},
            { 1353, "ER_VIEW_WRONG_LIST: 視圖SELECT和VIEW的列列表具有不同的列計數"},
            { 1354, "ER_WARN_VIEW_MERGE: 視圖合併算法無法在此處使用（假定未定義算法）"},
            { 1355, "ER_WARN_VIEW_WITHOUT_KEY: 視圖沒有基礎表的完整鍵"},
            { 1356, "ER_VIEW_INVALID: 視圖'%s.%s'引用無效表或列或其他定義"},
            { 1357, "ER_SP_NO_DROP_SP: 無法從另一個%s刪除或更改%s"},
            { 1358, "ER_TRG_ALREADY_EXISTS: 觸發器已存在"},
            { 1359, "ER_TRG_DOES_NOT_EXIST: 觸發器%s不存在"},
            { 1360, "ER_TRG_ON_VIEW_OR_TEMP_TABLE: 觸發器的'%s'是視圖或臨時表"},
            { 1361, "ER_TRG_CANT_CHANGE_ROW: 不允許更新%s中的OLD行"},
            { 1362, "ER_TRG_NO_SUCH_ROW_IN_TRG: 在%s中沒有%s行"},
            { 1363, "ER_NO_DEFAULT_FOR_FIELD: 列'%s'沒有預設值"},
            { 1364, "ER_DIVISION_BY_ZERO: 除以零"},
            { 1365, "ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: 不正確的%s值: '%s'對於列'%s'在行%ld"},
            { 1366, "ER_ILLEGAL_VALUE_FOR_TYPE: 不正確的%s值對於函數%s: '%s'"},
            { 1367, "ER_VIEW_NONUPD_CHECK: 檢查選項違反非更新視圖'%s.%s'"},
            { 1368, "ER_VIEW_CHECK_FAILED: CHECK OPTION失敗'%s.%s'"},
            { 1369, "ER_PROCACCESS_DENIED_ERROR: 使用者%s沒有%s程序%s的EXECUTE特權"},
            { 1370, "ER_RELAY_LOG_FAIL: 失敗%s中繼日誌%s"},
            { 1371, "ER_PASSWD_LENGTH: 密碼雜湊應為%d十六進位數字長"},
            { 1372, "ER_UNKNOWN_TARGET_BINLOG: 目標日誌未在二進位日誌索引中找到"},
            { 1373, "ER_IO_ERR_LOG_INDEX_READ: 讀取日誌索引檔案時I/O錯誤"},
            { 1374, "ER_BINLOG_PURGE_PROHIBITED: 伺服器配置不允許binlog清除"},
            { 1375, "ER_FSEEK_FAIL: 在日誌索引檔案上fseek()失敗"},
            { 1376, "ER_BINLOG_PURGE_FATAL_ERR: 在binlog清除期間發生致命錯誤"},
            { 1377, "ER_LOG_IN_USE: 可清除的日誌正在使用中，將不清除"},
            { 1378, "ER_LOG_PURGE_UNKNOWN_ERR: 在日誌清除期間發生未知錯誤"},
            { 1379, "ER_RELAY_LOG_INIT: 無法初始化中繼日誌結構; 更多錯誤訊息可以在MySQL錯誤日誌中找到"},
            { 1380, "ER_NO_BINARY_LOGGING: 您沒有使用二進位日誌記錄"},
            { 1381, "ER_RESERVED_SYNTAX: '%s'語法已保留用於MySQL伺服器內部使用"},
            { 1382, "ER_WSAS_FAILED: WSAStartup失敗"},
            { 1383, "ER_DIFF_GROUPS_PROC: 無法使用不同的群組處理程序處理程序"},
            { 1384, "ER_NO_GROUP_FOR_PROC: 對於該程序沒有群組處理程序"},
            { 1385, "ER_ORDER_WITH_PROC: 無法與ORDER一起使用程序"},
            { 1386, "ER_LOGGING_PROHIBIT_CHANGING_OF: 記錄禁止更改%s"},
            { 1387, "ER_NO_FILE_MAPPING: 無法映射檔案: %s, errno: %d"},
            { 1388, "ER_WRONG_MAGIC: %s中的錯誤魔法"},
            { 1389, "ER_PS_MANY_PARAM: 準備語句包含太多佔位符"},
            { 1390, "ER_KEY_PART_0: 鍵部分'%-.192s'的長度不能為0"},
            { 1391, "ER_VIEW_CHECKSUM: 視圖文字校驗和不匹配"},
            { 1392, "ER_VIEW_MULTIUPDATE: 無法透過連接視圖'%-.192s'.'%-.192s'修改多個基表"},
            { 1393, "ER_VIEW_NO_INSERT_FIELD_LIST: 無法插入到沒有完整欄位列表的連接視圖'%-.192s'.'%-.192s'中"},
            { 1394, "ER_VIEW_DELETE_MERGE_VIEW: 無法從連接視圖'%-.192s'.'%-.192s'中刪除"},
            { 1395, "ER_CANNOT_USER: 操作%s對%s失敗"},
            { 1396, "ER_XAER_NOTA: XAER_NOTA: 未知XID"},
            { 1397, "ER_XAER_INVAL: XAER_INVAL: 無效參數(或不支援的命令)"},
            { 1398, "ER_XAER_RMFAIL: XAER_RMFAIL: 資源管理器出錯時命令失敗"},
            { 1399, "ER_XAER_OUTSIDE: XAER_OUTSIDE: 某些工作是在全域事務之外完成的"},
            { 1400, "ER_XAER_RMERR: XAER_RMERR: 事務分支中出現資源管理器錯誤"},
            { 1401, "ER_XA_RBROLLBACK: XA_RBROLLBACK: 事務分支已回滾"},
            { 1402, "ER_NONEXISTING_PROC_GRANT: 沒有為使用者'%-.48s'在主機'%-.64s'上的例程'%-.192s'定義此類授權"},
            { 1403, "ER_PROC_AUTO_GRANT_FAIL: 無法授予EXECUTE和ALTER ROUTINE權限"},
            { 1404, "ER_PROC_AUTO_REVOKE_FAIL: 無法撤銷EXECUTE和ALTER ROUTINE權限"},
            { 1405, "ER_DATA_TOO_LONG: 第%ld行列'%s'的資料過長"},
            { 1406, "ER_SP_BAD_SQLSTATE: 錯誤的SQLSTATE: '%s'"},
            { 1407, "ER_STARTUP: %s: 準備連接失敗。%s"},
            { 1408, "ER_LOAD_FROM_FIXED_SIZE_ROWS_TO_VAR: 無法從具有固定大小行的檔案載入到具有可變大小行的表中"},
            { 1409, "ER_CANT_CREATE_USER_WITH_GRANT: 您不允許使用GRANT建立使用者"},
            { 1410, "ER_WRONG_VALUE_FOR_TYPE: 不正確的%s值: '%-.128s'用於函數%s"},
            { 1411, "ER_TABLE_DEF_CHANGED: 表定義已更改，請重試事務"},
            { 1412, "ER_SP_DUP_HANDLER: 重複的處理程序在相同區塊中宣告"},
            { 1413, "ER_SP_NOT_VAR_ARG: 不允許OUT或INOUT參數用於%s %s"},
            { 1414, "ER_SP_NO_RETSET: 不允許從%s傳回結果集"},
            { 1415, "ER_CANT_CREATE_GEOMETRY_OBJECT: 無法從傳送給GEOMETRY欄位的資料中取得幾何物件"},
            { 1416, "ER_FAILED_ROUTINE_BREAK_BINLOG: 例程失敗，並且二進位日誌記錄已啟用; 如果儲存的函數/觸發器使用非確定性操作，則可能不安全"},
            { 1417, "ER_BINLOG_UNSAFE_ROUTINE: 此函數在其主體中沒有DETERMINISTIC、NO SQL或READS SQL DATA，並且二進位日誌記錄已啟用(您*可能*希望使用較不安全的log_bin_trust_function_creators變數)"},
            { 1418, "ER_BINLOG_CREATE_ROUTINE_NEED_SUPER: 您沒有SUPER權限，並且二進位日誌記錄已啟用(您*可能*希望使用較不安全的log_bin_trust_function_creators變數)"},
            { 1419, "ER_EXEC_STMT_WITH_OPEN_CURSOR: 您無法在準備好的語句中執行此命令，該語句具有與之關聯的開啟游標。請先關閉游標，然後再執行該語句。"},
            { 1420, "ER_STMT_HAS_NO_OPEN_CURSOR: 該語句沒有開啟的游標。"},
            { 1421, "ER_COMMIT_NOT_ALLOWED_IN_SF_OR_TRG: 在儲存函數或觸發器中不允許顯式或隱式提交。"},
            { 1422, "ER_NO_DEFAULT_FOR_VIEW_FIELD: 視圖'%-.192s'.'%-.192s'的基礎表沒有預設值"},
            { 1423, "ER_SP_NO_RECURSION: 不允許遞迴儲存函數。"},
            { 1424, "ER_TOO_BIG_SCALE: 為欄'%-.192s'指定了太大的比例%d。最大為%d。"},
            { 1425, "ER_TOO_BIG_PRECISION: 為欄'%-.192s'指定了太大的精度%d。最大為%d。"},
            { 1426, "ER_M_BIGGER_THAN_D: 對於float(M,D)、double(M,D)或decimal(M,D)，M必須>= D(欄'%-.192s')。"},
            { 1427, "ER_WRONG_LOCK_OF_SYSTEM_TABLE: 您無法將系統表'%-.192s'.'%-.192s'與%s鎖定"},
            { 1428, "ER_CONNECT_TO_FOREIGN_DATA_SOURCE: 無法連線到外部資料來源: %-.64s"},
            { 1429, "ER_QUERY_ON_FOREIGN_DATA_SOURCE: 對外部資料來源的處理失敗。資料來源錯誤: %-.64s"},
            { 1430, "ER_FOREIGN_DATA_SOURCE_DOESNT_EXIST: 您嘗試參考的外部資料來源不存在。資料來源名稱: %-.64s"},
            { 1431, "ER_FOREIGN_DATA_STRING_INVALID_CANT_CREATE: 無法建立聯合表。資料來源連接字串'%-.100s'格式不正確。"},
            { 1432, "ER_FOREIGN_DATA_STRING_INVALID: 資料來源連接字串'%-.100s'格式不正確。"},
            { 1433, "ER_CANT_CREATE_FEDERATED_TABLE: 無法建立聯合表。外部資料來源錯誤: %-.64s"},
            { 1434, "ER_TRG_IN_WRONG_SCHEMA: 觸發器在錯誤的架構中"},
            { 1435, "ER_STACK_OVERRUN_NEED_MORE: 執行緒堆疊溢位: %ld位元組的堆疊使用，%ld位元組需要。使用'mysqld --thread_stack=#'指定更大的堆疊。"},
            { 1436, "ER_TOO_LONG_BODY: 例程體對於'%-.192s'過長"},
            { 1437, "ER_WARN_CANT_DROP_DEFAULT_KEYCACHE: 無法刪除預設鍵快取"},
            { 1438, "ER_TOO_BIG_DISPLAYWIDTH: 顯示寬度超出範圍對於欄'%-.192s'(最大值=%lu)"},
            { 1439, "ER_XAER_DUPID: XAER_DUPID: XID已存在"},
            { 1440, "ER_DATETIME_FUNCTION_OVERFLOW: 日期時間函數: %s欄位溢位"},
            { 1441, "ER_CANT_UPDATE_USED_TABLE_IN_SF_OR_TRG: 無法更新儲存函數/觸發器中的表'%-.192s'，因為它已被呼叫此儲存函數/觸發器的語句使用。"},
            { 1442, "ER_VIEW_PREVENT_UPDATE: 表'%-.192s'的定義不允許在表'%-.192s'上操作。"},
            { 1443, "ER_PS_NO_RECURSION: 準備好的語句包含對相同語句的參考。"},
            { 1444, "ER_SP_CANT_SET_AUTOCOMMIT: 不允許在儲存函數或觸發器中設定自動提交。"},
            { 1445, "ER_MALFORMED_DEFINER: 視圖'%-.192s'.'%-.192s'的定義者格式不正確。"},
            { 1446, "ER_VIEW_FRM_NO_USER: 視圖'%-.192s'.'%-.192s'的.frm檔案中沒有定義者資訊。"},
            { 1447, "ER_VIEW_OTHER_USER: 您需要定義者/呼叫者權限才能使用視圖'%-.192s'.'%-.192s'。"},
            { 1448, "ER_NO_SUCH_USER: 指定為定義者的使用者'%-.48s'@'%-.64s'不存在。"},
            { 1449, "ER_FORBID_SCHEMA_CHANGE: 不允許將架構從'%-.64s'更改為'%-.64s'。"},
            { 1450, "ER_ROW_IS_REFERENCED_2: 無法刪除或更新父行: 外鍵約束失敗(%s)"},
            { 1451, "ER_NO_REFERENCED_ROW_2: 無法新增或更新子行: 外鍵約束失敗(%s)"},
            { 1452, "ER_SP_BAD_VAR_SHADOW: 變數'%-.64s'必須用...宣告或必須在...之前宣告"},
            { 1453, "ER_TRG_NO_DEFINER: 觸發器'%-.192s'.'%-.192s'沒有定義者資訊。"},
            { 1454, "ER_OLD_FILE_FORMAT: '%-.192s'具有舊格式，您應該重新建立此視圖或取得更新的.frm檔案"},
            { 1455, "ER_SP_RECURSION_LIMIT: 遞迴限制%d(如max_sp_recursion_depth變數所設定)已用完"},
            { 1456, "ER_SP_PROC_TABLE_CORRUPT: 無法從mysql.proc表載入例程%s。該表可能已損壞"},
            { 1457, "ER_SP_WRONG_NAME: 不正確的例程名稱'%-.192s'"},
            { 1458, "ER_TABLE_NEEDS_UPGRADE: 表'%-.192s'.'%-.192s'需要升級。"},
            { 1459, "ER_SP_NO_AGGREGATE: 不允許聚合函數在%s"},
            { 1460, "ER_MAX_PREPARED_STMT_COUNT_REACHED: 無法建立超過max_prepared_stmt_count個預處理語句(目前值: %lu)"},
            { 1461, "ER_VIEW_RECURSIVE: 視圖'%-.64s'.'%-.64s'的SELECT包含對自身的子查詢參考"},
            { 1462, "ER_NON_GROUPING_FIELD_USED: 非分組欄'%-.192s'在HAVING子句中使用"},
            { 1463, "ER_TABLE_CANT_HANDLE_SPKEYS: 使用的表類型不支援SPATIAL索引"},
            { 1464, "ER_NO_TRIGGERS_ON_SYSTEM_SCHEMA: 不允許在系統表上建立觸發器"},
            { 1465, "ER_REMOVED_SPACES: 前導空格從名稱'%-.192s'中刪除"},
            { 1466, "ER_AUTOINC_READ_FAILED: 無法從儲存引擎讀取自增值"},
            { 1467, "ER_USERNAME: 使用者名稱"},
            { 1468, "ER_HOSTNAME: 主機名稱"},
            { 1469, "ER_WRONG_STRING_LENGTH: 字串'%-.70s'對於%s太長(應為%d, 最大%d)"},
            { 1470, "ER_NON_INSERTABLE_TABLE: 表'%-.192s'.'%-.192s'的目標不可插入"},
            { 1471, "ER_ADMIN_WRONG_MRG_TABLE: 表'%-.192s'.'%-.192s'定義為MERGE表，但沒有UNION=(表列表); 您必須修復此表"},
            { 1472, "ER_TOO_HIGH_LEVEL_OF_NESTING_FOR_SELECT: 對於SELECT的巢狀層級太高"},
            { 1473, "ER_NAME_BECOMES_EMPTY: 名稱'%-.192s'變為空"},
            { 1474, "ER_AMBIGUOUS_FIELD_TERM: 第一個欄位終止符與行終止符匹配，並且行終止符不是空的; 如果這不是您想要的，請檢查您的資料"},
            { 1475, "ER_FOREIGN_SERVER_EXISTS: 外部伺服器'%s'已存在"},
            { 1476, "ER_FOREIGN_SERVER_DOESNT_EXIST: 外部伺服器'%s'不存在"},
            { 1477, "ER_ILLEGAL_HA_CREATE_OPTION: 表儲存引擎'%s'不支援建立選項'%s'"},
            { 1478, "ER_PARTITION_REQUIRES_VALUES_ERROR: 語法錯誤: %s PARTITIONING需要VALUES %s的定義"},
            { 1479, "ER_PARTITION_WRONG_VALUES_ERROR: 只有%s PARTITIONING可以使用VALUES %s"},
            { 1480, "ER_PARTITION_MAXVALUE_ERROR: MAXVALUE只能在最後一個分割區定義中使用"},
            { 1481, "ER_PARTITION_SUBPARTITION_ERROR: 子分割區只能用於RANGE/LIST分割區"},
            { 1482, "ER_PARTITION_SUBPART_MIX_ERROR: 必須在每個分割區中定義相同數量的子分割區"},
            { 1483, "ER_PARTITION_WRONG_NO_PART_ERROR: 錯誤的分割區數，沒有分割區"},
            { 1484, "ER_PARTITION_WRONG_NO_SUBPART_ERROR: 錯誤的子分割區數，沒有子分割區"},
            { 1485, "ER_WRONG_EXPR_IN_PARTITION_FUNC_ERROR: 分割區函數中不允許常量、隨機或時區相關表達式"},
            { 1486, "ER_NO_CONST_EXPR_IN_RANGE_OR_LIST_ERROR: 在RANGE/LIST VALUES中只允許常量表達式"},
            { 1487, "ER_FIELD_NOT_FOUND_PART_ERROR: 在分割區函數中找不到欄位"},
            { 1488, "ER_LIST_OF_FIELDS_ONLY_IN_HASH_ERROR: 欄位列表僅在KEY分割區中允許"},
            { 1489, "ER_INCONSISTENT_PARTITION_INFO_ERROR: 分割區資訊不一致"},
            { 1490, "ER_PARTITION_FUNC_NOT_ALLOWED_ERROR: 此分割區函數不允許"},
            { 1491, "ER_PARTITIONS_MUST_BE_DEFINED_ERROR: 對於%s分割區，必須定義分割區"},
            { 1492, "ER_RANGE_NOT_INCREASING_ERROR: VALUES LESS THAN值必須嚴格遞增"},
            { 1493, "ER_INCONSISTENT_TYPE_OF_FUNCTIONS_ERROR: VALUES值必須與分割區函數具有相同類型"},
            { 1494, "ER_MULTIPLE_DEF_CONST_IN_LIST_PART_ERROR: LIST分割區中不允許重複的條目"},
            { 1495, "ER_PARTITION_ENTRY_ERROR: 分割區定義中的錯誤"},
            { 1496, "ER_MIX_HANDLER_ERROR: 此版本的MySQL尚不支援此表中的處理程序混合"},
            { 1497, "ER_PARTITION_NOT_DEFINED_ERROR: 對於表'%-.192s'.'%-.192s'，分割區'%-.64s'未定義"},
            { 1498, "ER_TOO_MANY_PARTITIONS_ERROR: 分割區太多，最大為%d"},
            { 1499, "ER_SUBPARTITION_ERROR: 子分割區錯誤，無法分配子分割區"},
            { 1500, "ER_CANT_CREATE_HANDLER_FILE: 無法建立特定的處理程序檔案"},
            { 1501, "ER_BLOB_FIELD_IN_PART_FUNC_ERROR: BLOB欄位在分割區函數中不允許"},
            { 1502, "ER_UNIQUE_KEY_NEED_ALL_FIELDS_IN_PF: %-.192s必須包括表分割區函數中的所有列"},
            { 1503, "ER_NO_PARTS_ERROR: 表'%-.192s'.'%-.192s'的分割區數=0"},
            { 1504, "ER_PARTITION_MGMT_ON_NONPARTITIONED: 對非分割區表的分割區管理"},
            { 1505, "ER_FOREIGN_KEY_ON_PARTITIONED: 不支援分割區表上的外鍵"},
            { 1506, "ER_DROP_PARTITION_NON_EXISTENT: 刪除不存在的分割區錯誤"},
            { 1507, "ER_DROP_LAST_PARTITION: 無法刪除所有分割區，請改用DROP TABLE"},
            { 1508, "ER_COALESCE_ONLY_ON_HASH_PARTITION: COALESCE PARTITION只能用於HASH/KEY分割區"},
            { 1509, "ER_REORG_HASH_ONLY_ON_SAME_NO: REORGANIZE PARTITION只能用於重新組織分割區而不更改其數量"},
            { 1510, "ER_REORG_NO_PARAM_ERROR: REORGANIZE PARTITION沒有參數"},
            { 1511, "ER_ONLY_ON_RANGE_LIST_PARTITION: %s PARTITION只能用於RANGE/LIST分割區"},
            { 1512, "ER_ADD_PARTITION_SUBPART_ERROR: 嘗試新增具有錯誤數量的子分割區的分割區"},
            { 1513, "ER_ADD_PARTITION_NO_NEW_PARTITION_ERROR: 必須至少新增一個分割區"},
            { 1514, "ER_COALESCE_PARTITION_NO_PARTITION_ERROR: 必須至少合併一個分割區"},
            { 1515, "ER_REORG_PARTITION_NOT_EXIST_ERROR: 重新組織不存在的分割區"},
            { 1516, "ER_SAME_NAME_PARTITION: 重複的分割區名稱'%-.64s'"},
            { 1517, "ER_NO_BINLOG_ERROR: 二進位日誌記錄已關閉; 可能需要重新啟動伺服器以啟用它"},
            { 1518, "ER_CONSECUTIVE_REORG_PARTITIONS: 重新組織一組連續的分割區時，它們必須按順序排列"},
            { 1519, "ER_REORG_OUTSIDE_RANGE: 重新組織分割區範圍超出範圍"},
            { 1520, "ER_PARTITION_FUNCTION_FAILURE: 分割區功能故障"},
            { 1521, "ER_PART_STATE_ERROR: 分割區狀態錯誤"},
            { 1522, "ER_LIMITED_PART_RANGE: 此版本的MySQL尚不支援此分割區範圍"},
            { 1523, "ER_PLUGIN_IS_NOT_LOADED: 插件'%s'未載入"},
            { 1524, "ER_WRONG_VALUE: 不正確的%s值: '%-.64s'"},
            { 1525, "ER_NO_PARTITION_FOR_GIVEN_VALUE: 表沒有分割區用於值'%-.64s'"},
            { 1526, "ER_FILEGROUP_OPTION_ONLY_ONCE: 每個表只能使用一次FILEGROUP選項"},
            { 1527, "ER_CREATE_FILEGROUP_FAILED: 建立檔案群組失敗"},
            { 1528, "ER_DROP_FILEGROUP_FAILED: 刪除檔案群組失敗"},
            { 1529, "ER_TABLESPACE_AUTO_EXTEND_ERROR: 表空間自動擴充錯誤"},
            { 1530, "ER_WRONG_SIZE_NUMBER: 大小數字語法錯誤"},
            { 1531, "ER_SIZE_OVERFLOW_ERROR: 大小溢位錯誤"},
            { 1532, "ER_ALTER_FILEGROUP_FAILED: 更改檔案群組失敗"},
            { 1533, "ER_BINLOG_ROW_LOGGING_FAILED: 二進位日誌行記錄失敗: %s"},
            { 1534, "ER_BINLOG_ROW_WRONG_TABLE_DEF: 表定義在主從伺服器上不匹配: %s"},
            { 1535, "ER_BINLOG_ROW_RBR_TO_SBR: 無法使用語句格式在從伺服器上執行行事件"},
            { 1536, "ER_EVENT_ALREADY_EXISTS: 事件'%-.192s'已存在"},
            { 1537, "ER_EVENT_STORE_FAILED: 建立/更改事件'%-.192s'失敗"},
            { 1538, "ER_EVENT_DOES_NOT_EXIST: 未知事件'%-.192s'"},
            { 1539, "ER_EVENT_CANT_ALTER: 無法更改事件'%-.192s'"},
            { 1540, "ER_EVENT_DROP_FAILED: 刪除事件'%-.192s'失敗"},
            { 1541, "ER_EVENT_INTERVAL_NOT_POSITIVE_OR_TOO_BIG: 事件間隔既不是正數也不是太大"},
            { 1542, "ER_EVENT_ENDS_BEFORE_STARTS: 事件結束在開始之前"},
            { 1543, "ER_EVENT_EXEC_TIME_IN_THE_PAST: 事件執行時間在過去，ON COMPLETION NOT PRESERVE設定。事件在建立後立即被刪除。"},
            { 1544, "ER_EVENT_OPEN_TABLE_FAILED: 無法開啟mysql.event表"},
            { 1545, "ER_EVENT_NEITHER_M_EXPR_NOR_M_AT: 事件'%-.192s'既沒有表達式也沒有AT子句"},
            { 1546, "ER_COL_COUNT_DOESNT_MATCH_CORRUPTED: 列計數錯誤。預期%d，找到%d。表可能已損壞"},
            { 1547, "ER_CANNOT_LOAD_FROM_TABLE: 無法從mysql.%s載入。該表可能已損壞"},
            { 1548, "ER_EVENT_CANNOT_DELETE: 無法從mysql.event刪除事件"},
            { 1549, "ER_EVENT_COMPILE_ERROR: 事件體編譯期間出錯"},
            { 1550, "ER_EVENT_SAME_NAME: 相同的新舊事件名稱"},
            { 1551, "ER_EVENT_DATA_TOO_LONG: 欄'%s'的資料過長"},
            { 1552, "ER_DROP_INDEX_FK: 無法刪除索引'%-.192s': 外鍵約束中需要"},
            { 1553, "ER_WARN_DEPRECATED_SYNTAX_WITH_VER: 語法'%s'已棄用，將在MySQL %s中刪除。請改用%s"},
            { 1554, "ER_CANT_WRITE_LOCK_LOG_TABLE: 您無法寫鎖定日誌表。只允許讀取存取"},
            { 1555, "ER_CANT_LOCK_LOG_TABLE: 您無法對日誌表使用鎖。"},
            { 1556, "ER_FOREIGN_DUPLICATE_KEY: 維護表'%.192s'的外鍵約束，條目'%-.192s'，鍵%d將導致重複條目"},
            { 1557, "ER_COL_COUNT_DOESNT_MATCH_PLEASE_UPDATE: mysql.%s的列計數錯誤。預期%d，找到%d。使用MySQL %d建立，現在執行%d。請使用mysql_upgrade修復此錯誤。"},
            { 1558, "ER_TEMP_TABLE_PREVENTS_SWITCH_OUT_OF_RBR: 當會話有開啟的臨時表時，無法從基於行的二進位日誌格式切換"},
            { 1559, "ER_STORED_FUNCTION_PREVENTS_SWITCH_BINLOG_FORMAT: 無法在儲存函數或觸發器內部更改二進位日誌格式"},
            { 1560, "ER_NDB_CANT_SWITCH_BINLOG_FORMAT: NDB叢集引擎尚不支援動態更改binlog格式"},
            { 1561, "ER_PARTITION_NO_TEMPORARY: 無法建立具有分割區的臨時表"},
            { 1562, "ER_PARTITION_CONST_DOMAIN_ERROR: 分割區常量超出分割區函數域"},
            { 1563, "ER_PARTITION_FUNCTION_IS_NOT_ALLOWED: 不允許此分割區函數"},
            { 1564, "ER_DDL_LOG_ERROR: DDL日誌中的錯誤"},
            { 1565, "ER_NULL_IN_VALUES_LESS_THAN: 在VALUES LESS THAN中不允許使用NULL值"},
            { 1566, "ER_WRONG_PARTITION_NAME: 不正確的分割區名稱"},
            { 1567, "ER_CANT_CHANGE_TX_CHARACTERISTICS: 事務正在進行時無法更改事務特徵"},
            { 1568, "ER_DUP_ENTRY_AUTOINCREMENT_CASE: ALTER TABLE導致自動遞增重新排序，導致鍵'%-.192s'的重複條目'%-.192s'"},
            { 1569, "ER_EVENT_MODIFY_QUEUE_ERROR: 內部排程程序錯誤%d"},
            { 1570, "ER_EVENT_SET_VAR_ERROR: 排程程序啟動/停止期間出錯。錯誤代碼%u"},
            { 1571, "ER_PARTITION_MERGE_ERROR: 引擎不能在分割區表中使用"},
            { 1572, "ER_CANT_ACTIVATE_LOG: 無法啟動'%-.64s'日誌"},
            { 1573, "ER_RBR_NOT_AVAILABLE: 伺服器未使用基於行的複製建置"},
            { 1574, "ER_BASE64_DECODE_ERROR: base64字串解碼失敗"},
            { 1575, "ER_EVENT_RECURSION_FORBIDDEN: 當存在主體時，禁止事件DDL語句的遞迴"},
            { 1576, "ER_EVENTS_DB_ERROR: 無法繼續，因為在伺服器啟動時發現事件排程程序使用的系統表已損壞"},
            { 1577, "ER_ONLY_INTEGERS_ALLOWED: 此處只允許整數作為數字"},
            { 1578, "ER_UNSUPORTED_LOG_ENGINE: 此儲存引擎不能用於日誌表"},
            { 1579, "ER_BAD_LOG_STATEMENT: 如果啟用了日誌記錄，則無法對日誌表執行'%s'"},
            { 1580, "ER_CANT_RENAME_LOG_TABLE: 無法重新命名'%s'。啟用日誌記錄時，重新命名到/從日誌表必須重新命名兩個表: 日誌表到歸檔表，另一個表回到'%s'"},
            { 1581, "ER_WRONG_PARAMCOUNT_TO_NATIVE_FCT: 呼叫本機函數'%-.192s'的參數計數不正確"},
            { 1582, "ER_WRONG_PARAMETERS_TO_NATIVE_FCT: 呼叫本機函數'%-.192s'的參數不正確"},
            { 1583, "ER_WRONG_PARAMETERS_TO_STORED_FCT: 呼叫儲存函數'%-.192s'的參數不正確"},
            { 1584, "ER_NATIVE_FCT_NAME_COLLISION: 此函數'%-.192s'與本機函數同名"},
            { 1585, "ER_DUP_ENTRY_WITH_KEY_NAME: 鍵'%-.192s'的重複條目'%-.64s'"},
            { 1586, "ER_BINLOG_PURGE_EMFILE: 開啟的檔案太多，請再次執行命令"},
            { 1587, "ER_EVENT_CANNOT_CREATE_IN_THE_PAST: 事件執行時間在過去，ON COMPLETION NOT PRESERVE設定。事件在建立後立即被刪除。"},
            { 1588, "ER_EVENT_CANNOT_ALTER_IN_THE_PAST: 事件執行時間在過去，ON COMPLETION NOT PRESERVE設定。事件未更改。請指定未來的時間。"},
            { 1589, "ER_SLAVE_INCIDENT: 主伺服器上發生事件%s。訊息: %-.64s"},
            { 1590, "ER_NO_PARTITION_FOR_GIVEN_VALUE_SILENT: 表沒有某些現有值的分割區"},
            { 1591, "ER_BINLOG_UNSAFE_STATEMENT: 由於BINLOG_FORMAT = STATEMENT，不安全的語句寫入二進位日誌。%s"},
            { 1592, "ER_SLAVE_FATAL_ERROR: 致命錯誤: %s"},
            { 1593, "ER_SLAVE_RELAY_LOG_READ_FAILURE: 中繼日誌讀取失敗: %s"},
            { 1594, "ER_SLAVE_RELAY_LOG_WRITE_FAILURE: 中繼日誌寫入失敗: %s"},
            { 1595, "ER_SLAVE_CREATE_EVENT_FAILURE: 建立%s失敗"},
            { 1596, "ER_SLAVE_MASTER_COM_FAILURE: 主命令%s失敗: %s"},
            { 1597, "ER_BINLOG_LOGGING_IMPOSSIBLE: 無法進行二進位日誌記錄。訊息: %s"},
            { 1598, "ER_VIEW_NO_CREATION_CTX: 視圖`%-.64s`.`%-.64s`沒有建立上下文"},
            { 1599, "ER_VIEW_INVALID_CREATION_CTX: 視圖`%-.64s`.`%-.64s`的建立上下文無效"},
            { 1600, "ER_SR_INVALID_CREATION_CTX: 儲存例程`%-.64s`.`%-.64s`的建立上下文無效"},
            { 1601, "ER_TRG_CORRUPTED_FILE: 表`%-.64s`.`%-.64s`的TRG檔案已損壞"},
            { 1602, "ER_TRG_NO_CREATION_CTX: 表`%-.64s`.`%-.64s`的觸發器沒有建立上下文"},
            { 1603, "ER_TRG_INVALID_CREATION_CTX: 表`%-.64s`.`%-.64s`的觸發器建立上下文無效"},
            { 1604, "ER_EVENT_INVALID_CREATION_CTX: 事件`%-.64s`.`%-.64s`的建立上下文無效"},
            { 1605, "ER_TRG_CANT_OPEN_TABLE: 無法為觸發器`%-.64s`.`%-.64s`開啟表"},
            { 1606, "ER_CANT_CREATE_SROUTINE: 無法建立儲存例程`%-.64s`。檢查警告"},
            { 1607, "ER_NEVER_USED: 模糊的從伺服器模式組合。%s"},
            { 1608, "ER_NO_FORMAT_DESCRIPTION_EVENT_BEFORE_BINLOG_STATEMENT: 類型為`%s`的BINLOG語句前面沒有格式描述BINLOG語句。"},
            { 1609, "ER_SLAVE_CORRUPT_EVENT: 偵測到損壞的複製事件"},
            { 1610, "ER_LOAD_DATA_INVALID_COLUMN: LOAD DATA中的無效列參考(%-.64s)"},
            { 1611, "ER_LOG_PURGE_NO_FILE: 未找到正在清除的日誌%s"},
            { 1612, "ER_XA_RBTIMEOUT: XA_RBTIMEOUT: 事務分支已回滾: 耗時過長"},
            { 1613, "ER_XA_RBDEADLOCK: XA_RBDEADLOCK: 事務分支已回滾: 偵測到死鎖"},
            { 1614, "ER_CANNOT_ADD_FOREIGN: 無法新增外鍵約束"},
            { 1615, "ER_BAD_COLUMN_ERROR: 未知列'%-.192s'在'%s'中"},
            { 1616, "ER_BAD_FIELD_ERROR: 未知列'%-.192s'在'%s'中"},
            { 1617, "ER_BAD_TABLE_ERROR: 未知表'%s'"},
            { 1618, "ER_BAD_DB_ERROR: 未知資料庫'%s'"},
            { 1619, "ER_DB_CREATE_EXISTS: 無法建立資料庫'%s'; 資料庫已存在"},
            { 1620, "ER_DB_DROP_EXISTS: 無法刪除資料庫'%s'; 資料庫不存在"},
            { 1621, "ER_DB_DROP_DELETE: 無法刪除資料庫'%s'; %s"},
            { 1622, "ER_DB_DROP_RMDIR: 無法刪除資料庫'%s'; %s"},
            { 1623, "ER_CANT_DELETE_FILE: 無法刪除'%s' (錯誤代碼: %d - %s)"},
            { 1624, "ER_CANT_FIND_SYSTEM_REC: 無法在%s中找到系統記錄"},
            { 1625, "ER_CANT_GET_STAT: 無法取得'%s'的狀態 (錯誤代碼: %d - %s)"},
            { 1626, "ER_CANT_GET_WD: 無法取得工作目錄 (錯誤代碼: %d - %s)"},
            { 1627, "ER_CANT_LOCK: 無法鎖定檔案 (錯誤代碼: %d - %s)"},
            { 1628, "ER_CANT_OPEN_FILE: 無法開啟'%s' (錯誤代碼: %d - %s)"},
            { 1629, "ER_FILE_NOT_FOUND: 找不到檔案'%s' (錯誤代碼: %d - %s)"},
            { 1630, "ER_CANT_READ_DIR: 無法讀取'%s'的目錄 (錯誤代碼: %d - %s)"},
            { 1631, "ER_CANT_SET_WD: 無法設定工作目錄為'%s' (錯誤代碼: %d - %s)"},
            { 1632, "ER_CHECKREAD: 表'%s'的記錄已損壞"},
            { 1633, "ER_DISK_FULL: 磁碟已滿 (%s); 等待某人釋放一些空間..."},
            { 1634, "ER_DUP_KEY: 無法寫入; 表'%s'的重複鍵"},
            { 1635, "ER_ERROR_ON_CLOSE: 關閉'%s'時出錯 (錯誤代碼: %d - %s)"},
            { 1636, "ER_ERROR_ON_READ: 讀取'%s'時出錯 (錯誤代碼: %d - %s)"},
            { 1637, "ER_ERROR_ON_RENAME: 重新命名'%s'到'%s'時出錯 (錯誤代碼: %d - %s)"},
            { 1638, "ER_ERROR_ON_WRITE: 寫入'%s'時出錯 (錯誤代碼: %d - %s)"},
            { 1639, "ER_FILE_USED: '%s'被鎖定以防止更改"},
            { 1640, "ER_FILSORT_ABORT: 排序中止"},
            { 1641, "ER_FORM_NOT_FOUND: 視圖'%s'的.frm檔案不存在"},
            { 1642, "ER_GET_ERRNO: 從儲存引擎取得錯誤%d"},
            { 1643, "ER_ILLEGAL_HA: 表'%s'的儲存引擎不存在"},
            { 1644, "ER_KEY_NOT_FOUND: 在表'%s'中找不到記錄"},
            { 1645, "ER_NOT_FORM_FILE: '%s'的檔案內容不符合預期"},
            { 1646, "ER_NOT_KEYFILE: 表'%s'的索引檔案不正確"},
            { 1647, "ER_OLD_KEYFILE: 表'%s'的索引檔案太舊，請修復它"},
            { 1648, "ER_OPEN_AS_READONLY: 表'%s'以唯讀方式開啟"},
            { 1649, "ER_OUTOFMEMORY: 記憶體不足，檢查mysqld或其他程序是否佔用所有可用記憶體; 如果沒有，您可能需要使用'ulimit'允許mysqld使用更多記憶體，或增加交換空間"},
            { 1650, "ER_OUT_OF_SORTMEMORY: 排序記憶體不足，增加伺服器的排序緩衝區大小"},
            { 1651, "ER_UNEXPECTED_EOF: 讀取檔案'%s'時遇到意外EOF (錯誤代碼: %d - %s)"},
            { 1652, "ER_CON_COUNT_ERROR: 連接太多"},
            { 1653, "ER_OUT_OF_RESOURCES: 資源不足; 檢查是否有其他mysqld程序在執行"},
            { 1654, "ER_BAD_HOST_ERROR: 無法取得%s的主機名稱"},
            { 1655, "ER_HANDSHAKE_ERROR: 握手錯誤"},
            { 1656, "ER_DBACCESS_DENIED_ERROR: 使用者'%-.48s'@'%-.64s'拒絕存取資料庫'%s'"},
            { 1657, "ER_ACCESS_DENIED_ERROR: 使用者'%-.48s'@'%-.64s'拒絕存取(使用密碼: %s)"},
            { 1658, "ER_NO_DB_ERROR: 未選擇資料庫"},
            { 1659, "ER_UNKNOWN_COM_ERROR: 未知命令"},
            { 1660, "ER_BAD_NULL_ERROR: 列'%s'不能為空"},
            { 1661, "ER_BAD_DB_ERROR: 未知資料庫'%s'"},
            { 1662, "ER_TABLE_EXISTS_ERROR: 表'%s'已存在"},
            { 1663, "ER_BAD_TABLE_ERROR: 未知表'%s'"},
            { 1664, "ER_NON_UNIQ_ERROR: 列'%s'在%s中不明確"},
            { 1665, "ER_SERVER_SHUTDOWN: 伺服器關閉中"},
            { 1666, "ER_BAD_FIELD_ERROR: 未知列'%s'在'%s'中"},
            { 1667, "ER_WRONG_FIELD_WITH_GROUP: '%s'不在GROUP BY中"},
            { 1668, "ER_WRONG_GROUP_FIELD: 無法在'%s'上分組"},
            { 1669, "ER_WRONG_SUM_SELECT: 在包含組函數的語句中，%s的SELECT列表中有非組函數的列'%s'"},
            { 1670, "ER_WRONG_VALUE_COUNT: 列計數與值計數不匹配"},
            { 1671, "ER_TOO_LONG_IDENT: 標識符'%s'太長"},
            { 1672, "ER_DUP_FIELDNAME: 重複的列名稱'%s'"},
            { 1673, "ER_DUP_KEYNAME: 重複的鍵名稱'%s'"},
            { 1674, "ER_DUP_ENTRY: 鍵'%s'的重複條目'%-.64s'"},
            { 1675, "ER_WRONG_FIELD_SPEC: 列'%s'的規格不正確"},
            { 1676, "ER_PARSE_ERROR: %s接近'%-.80s'在第%d行"},
            { 1677, "ER_EMPTY_QUERY: 查詢為空"},
            { 1678, "ER_NONUNIQ_TABLE: 表'%s'不明確"},
            { 1679, "ER_INVALID_DEFAULT: 列'%s'的無效預設值"},
            { 1680, "ER_MULTIPLE_PRI_KEY: 定義了多個主鍵"},
            { 1681, "ER_TOO_MANY_KEYS: 指定了太多鍵; 最大允許%d個鍵"},
            { 1682, "ER_TOO_MANY_KEY_PARTS: 指定了太多鍵部分; 最大允許%d個部分"},
            { 1683, "ER_TOO_LONG_KEY: 指定的鍵太長; 最大鍵長度為%d位元組"},
            { 1684, "ER_KEY_COLUMN_DOES_NOT_EXITS: 鍵列'%s'在表中不存在"},
            { 1685, "ER_BLOB_USED_AS_KEY: 使用的BLOB/TEXT列'%s'用作鍵規範而沒有鍵長度"},
            { 1686, "ER_TOO_BIG_FIELDLENGTH: 列'%s'的長度太大(最大值=%lu); 改用BLOB或TEXT"},
            { 1687, "ER_WRONG_AUTO_KEY: 表定義中的不正確自動增量規格"},
            { 1688, "ER_READY: %s: 準備好連接。版本: '%s' 通訊端: '%s' 連接埠: %d"},
            { 1689, "ER_NORMAL_SHUTDOWN: %s: 正常關閉"},
            { 1690, "ER_GOT_SIGNAL: %s: 收到信號%d。正在中止!"},
            { 1691, "ER_SHUTDOWN_COMPLETE: %s: 關閉完成"},
            { 1692, "ER_FORCING_CLOSE: %s: 強制關閉執行緒%ld 使用者: '%-.48s'"},
            { 1693, "ER_IPSOCK_ERROR: 無法建立IP通訊端"},
            { 1694, "ER_NO_TABLES_USED: 沒有使用表"},
            { 1695, "ER_TOO_BIG_SET: 列%s和SET的字串過多"},
            { 1696, "ER_NO_UNIQUE_LOGFILE: 無法產生唯一日誌檔名%s.(1-999)"},
            { 1697, "ER_TABLE_NOT_LOCKED_FOR_WRITE: 表'%-.192s'未使用WRITE鎖定"},
            { 1698, "ER_TABLE_NOT_LOCKED: 表'%-.192s'未鎖定"},
            { 1699, "ER_BLOB_CANT_HAVE_DEFAULT: BLOB/TEXT列'%-.192s'不能有預設值"},
            { 1700, "ER_WRONG_DB_NAME: 不正確的資料庫名稱'%-.100s'"},
            { 1701, "ER_WRONG_TABLE_NAME: 不正確的表名'%-.100s'"},
            { 1702, "ER_TOO_BIG_SELECT: 選擇的列過多"},
            { 1703, "ER_UNKNOWN_ERROR: 未知錯誤"},
            { 1704, "ER_UNKNOWN_PROCEDURE: 未知程序'%-.192s'"},
            { 1705, "ER_WRONG_PARAMCOUNT_TO_PROCEDURE: 程序'%-.192s'的參數計數不正確"},
            { 1706, "ER_WRONG_PARAMETERS_TO_PROCEDURE: 程序'%-.192s'的參數不正確"},
            { 1707, "ER_UNKNOWN_TABLE: 表'%-.192s'中的未知列'%-.192s'"},
            { 1708, "ER_FIELD_SPECIFIED_TWICE: 列'%-.192s'被指定了兩次"},
            { 1709, "ER_INVALID_GROUP_FUNC_USE: 組函數的無效使用"},
            { 1710, "ER_UNSUPPORTED_EXTENSION: 表'%-.192s'使用該延伸中不支援的延伸"},
            { 1711, "ER_TABLE_MUST_HAVE_COLUMNS: 表必須至少有1列"},
            { 1712, "ER_RECORD_FILE_FULL: 表'%-.192s'已滿"},
            { 1713, "ER_UNKNOWN_CHARACTER_SET: 未知字元集: '%-.64s'"},
            { 1714, "ER_BINLOG_UNSAFE_INSERT_IGNORE_SELECT: INSERT IGNORE... SELECT不安全，因為SELECT檢索行的順序決定了哪些(如果有)行被忽略。此順序無法預測，並且可能在主伺服器和從伺服器上不同"},
            { 1715, "ER_BINLOG_UNSAFE_INSERT_SELECT_UPDATE: INSERT... SELECT... ON DUPLICATE KEY UPDATE不安全，因為SELECT檢索行的順序決定了哪些行被更新。此順序無法預測，並且可能在主伺服器和從伺服器上不同"},
            { 1716, "ER_BINLOG_UNSAFE_REPLACE_SELECT: REPLACE... SELECT不安全，因為SELECT檢索行的順序決定了哪些行被替換。此順序無法預測，並且可能在主伺服器和從伺服器上不同"},
            { 1717, "ER_BINLOG_UNSAFE_CREATE_IGNORE_SELECT: CREATE... IGNORE... SELECT不安全，因為SELECT檢索行的順序決定了哪些行被忽略。此順序無法預測，並且可能在主伺服器和從伺服器上不同"},
            { 1718, "ER_BINLOG_UNSAFE_CREATE_REPLACE_SELECT: CREATE... REPLACE... SELECT不安全，因為SELECT檢索行的順序決定了哪些行被替換。此順序無法預測，並且可能在主伺服器和從伺服器上不同"},
            { 1719, "ER_BINLOG_UNSAFE_UPDATE_IGNORE: UPDATE IGNORE不安全，因為行的更新順序決定了哪些行被忽略。此順序無法預測，並且可能在主伺服器和從伺服器上不同"},
            { 1720, "ER_PLUGIN_NO_UNINSTALL: 插件'%s'已標記為不可解除安裝。您需要先停止伺服器才能解除安裝它"},
            { 1721, "ER_PLUGIN_NO_INSTALL: 插件'%s'已標記為不可安裝。您需要先停止伺服器才能安裝它"},
            { 1722, "ER_BINLOG_UNSAFE_WRITE_AUTOINC_SELECT: 對具有自增列的表執行INSERT... SELECT語句不安全，因為SELECT檢索行的順序決定了哪些行被分配了哪些自增值。此順序無法預測，並且可能在主伺服器和從伺服器上不同"},
            { 1723, "ER_BINLOG_UNSAFE_CREATE_SELECT_AUTOINC: 對具有自增列的表執行CREATE... SELECT語句不安全，因為SELECT檢索行的順序決定了哪些行被分配了哪些自增值。此順序無法預測，並且可能在主伺服器和從伺服器上不同"},
            { 1724, "ER_BINLOG_UNSAFE_INSERT_TWO_KEYS: INSERT INTO... ON DUPLICATE KEY UPDATE在不安全的語句二進位日誌記錄模式下不安全，因為受影響的行數無法預測"},
            { 1725, "ER_TABLE_IN_FK_CHECK: 無法在表'%-.192s'上執行操作，因為外鍵檢查正在執行"},
            { 1726, "ER_UNSUPPORTED_ENGINE: 儲存引擎'%s'不支援%s"},
            { 1727, "ER_BINLOG_UNSAFE_AUTOINC_NOT_FIRST: 自增列不是表中的第一列時不安全"},
            { 1728, "ER_CANNOT_LOAD_FROM_TABLE_V2: 無法從%s.%s載入。該表可能已損壞"},
            { 1729, "ER_MASTER_DELAY_VALUE_OUT_OF_RANGE: 請求的主伺服器延遲值'%ld'超出範圍。必須介於0和%ld之間"},
            { 1730, "ER_ONLY_FD_AND_RBR_EVENTS_ALLOWED_IN_BINLOG_STATEMENT: 只有格式描述和行事件允許在BINLOG語句中"},
            { 1731, "ER_PARTITION_EXCHANGE_DIFFERENT_OPTION: 非分割區表'%-.64s'和分割區表'%-.64s'在分割區交換中不共用相同的%s選項"},
            { 1732, "ER_PARTITION_EXCHANGE_PART_TABLE: 表'%-.64s'是分割區表。只能與非分割區表交換分割區"},
            { 1733, "ER_PARTITION_EXCHANGE_TEMP_TABLE: 表'%-.64s'是臨時表。不能與分割區交換"},
            { 1734, "ER_PARTITION_INSTEAD_OF_SUBPARTITION: 子分割區表只能與子分割區交換，不能與分割區交換"},
            { 1735, "ER_UNKNOWN_PARTITION: 表'%-.192s'中的未知分割區'%-.64s'"},
            { 1736, "ER_TABLES_DIFFERENT_METADATA: 表具有不同的定義"},
            { 1737, "ER_ROW_DOES_NOT_MATCH_PARTITION: 找到一行不匹配給定分割區"},
            { 1738, "ER_BINLOG_CACHE_SIZE_GREATER_THAN_MAX: 選項binlog_cache_size(%lu)大於max_binlog_cache_size(%lu); 將binlog_cache_size設定為等於max_binlog_cache_size"},
            { 1739, "ER_WARN_INDEX_NOT_APPLICABLE: 由於類型或排序規則轉換，無法使用索引%s進行%s存取"},
            { 1740, "ER_PARTITION_EXCHANGE_FOREIGN_KEY: 分割區交換不能在外鍵約束中執行; 表'%-.192s'，約束'%-.64s'"},
            { 1741, "ER_NO_SUCH_KEY_VALUE: 鍵值'%-.192s'在表'%-.192s'中未找到"},
            { 1742, "ER_RPL_INFO_DATA_TOO_LONG: 資料對於列'%-.192s'過長"},
            { 1743, "ER_NETWORK_READ_EVENT_CHECKSUM_FAILURE: 從網路讀取時複製事件校驗和失敗"},
            { 1744, "ER_BINLOG_READ_EVENT_CHECKSUM_FAILURE: 從二進位日誌讀取時複製事件校驗和失敗"},
            { 1745, "ER_BINLOG_STMT_CACHE_SIZE_GREATER_THAN_MAX: 選項binlog_stmt_cache_size(%lu)大於max_binlog_stmt_cache_size(%lu); 將binlog_stmt_cache_size設定為等於max_binlog_stmt_cache_size"},
            { 1746, "ER_CANT_UPDATE_TABLE_IN_CREATE_TABLE_SELECT: 不能在子查詢中更新表'%-.192s'，該表也用於CREATE/ALTER TABLE語句的外部查詢"},
            { 1747, "ER_PARTITION_CLAUSE_ON_NONPARTITIONED: 非分割區表'%-.192s'上的PARTITION子句"},
            { 1748, "ER_ROW_DOES_NOT_MATCH_GIVEN_PARTITION_SET: 行不匹配給定的分割區集"},
            { 1749, "ER_NO_SUCH_PARTITION: 表'%-.192s'中的分割區'%-.64s'不存在"},
            { 1750, "ER_CHANGE_RPL_INFO_REPOSITORY_FAILURE: 更改複製儲存庫類型時失敗: %s"},
            { 1751, "ER_WARNING_NOT_COMPLETE_ROLLBACK_WITH_CREATED_TEMP_TABLE: 某些臨時表的建立無法回滾"},
            { 1752, "ER_WARNING_NOT_COMPLETE_ROLLBACK_WITH_DROPPED_TEMP_TABLE: 某些臨時表被刪除，但這些操作無法回滾"},
            { 1753, "ER_MTS_FEATURE_IS_NOT_SUPPORTED: %s在多執行緒從伺服器模式下不支援。%s"},
            { 1754, "ER_MTS_UPDATED_DBS_GREATER_MAX: 修改的資料庫數量超過最大值%d; 資料庫名稱將不包含在複製事件元資料中"},
            { 1755, "ER_MTS_CANT_PARALLEL: 無法在平行模式下執行目前事件群組。遇到事件%s，中繼日誌名稱%s，位置%s，這阻止了在平行模式下執行此事件群組。原因: %s"},
            { 1756, "ER_MTS_INCONSISTENT_DATA: %s"},
            { 1757, "ER_FULLTEXT_NOT_SUPPORTED_WITH_PARTITIONING: 分割區表不支援FULLTEXT索引"},
            { 1758, "ER_DA_INVALID_CONDITION_NUMBER: 無效的條件編號"},
            { 1759, "ER_INSECURE_PLAIN_TEXT: 在不使用SSL/TLS的情況下以明文傳送密碼極不安全"},
            { 1760, "ER_INSECURE_CHANGE_MASTER: 在主資訊儲存庫中儲存MySQL使用者名稱或密碼資訊不安全，因此不推薦。請考慮使用START SLAVE的USER和PASSWORD連線選項; 有關更多資訊，請參閱MySQL手冊中的'START SLAVE語法'"},
            { 1761, "ER_FOREIGN_DUPLICATE_KEY_WITH_CHILD_INFO: 表'%.192s'的外鍵約束，記錄'%-.192s'將導致表'%.192s'中的重複條目，鍵'%.192s'"},
            { 1762, "ER_FOREIGN_DUPLICATE_KEY_WITHOUT_CHILD_INFO: 表'%.192s'的外鍵約束，記錄'%-.192s'將導致子表中的重複條目"},
            { 1763, "ER_SQLTHREAD_WITH_SECURE_SLAVE: 當僅啟動從伺服器SQL執行緒時，無法設定身份驗證選項"},
            { 1764, "ER_TABLE_HAS_NO_FT: 表沒有FULLTEXT索引來支援此查詢"},
            { 1765, "ER_VARIABLE_NOT_SETTABLE_IN_SF_OR_TRIGGER: 系統變數%.200s不能在儲存函數或觸發器中設定"},
            { 1766, "ER_VARIABLE_NOT_SETTABLE_IN_TRANSACTION: 當有正在進行的事務時，不能設定系統變數%.200s"},
            { 1767, "ER_GTID_NEXT_IS_NOT_IN_GTID_NEXT_LIST: 系統變數@@SESSION.GTID_NEXT的值為%.200s，未在@@SESSION.GTID_NEXT_LIST中列出"},
            { 1768, "ER_CANT_CHANGE_GTID_NEXT_IN_TRANSACTION_WHEN_GTID_NEXT_LIST_IS_NULL: 系統變數@@SESSION.GTID_NEXT不能在事務內部更改"},
            { 1769, "ER_SET_STATEMENT_CANNOT_INVOKE_FUNCTION: 語句'SET %.200s'不能呼叫儲存函數"},
            { 1770, "ER_GTID_NEXT_CANT_BE_AUTOMATIC_IF_GTID_NEXT_LIST_IS_NON_NULL: 當@@SESSION.GTID_NEXT_LIST為非NULL時，系統變數@@SESSION.GTID_NEXT不能為'AUTOMATIC'"},
            { 1771, "ER_SKIPPING_LOGGED_TRANSACTION: 跳過事務%.200s，因為它已被執行並記錄"},
            { 1772, "ER_MALFORMED_GTID_SET_SPECIFICATION: 格式錯誤的GTID集規範'%.200s'"},
            { 1773, "ER_MALFORMED_GTID_SET_ENCODING: 格式錯誤的GTID集編碼"},
            { 1774, "ER_MALFORMED_GTID_SPECIFICATION: 格式錯誤的GTID規範'%.200s'"},
            { 1775, "ER_GNO_EXHAUSTED: 無法產生全域事務識別碼: 整數元件達到最大值。使用新的server_uuid重新啟動伺服器"},
            { 1776, "ER_BAD_SLAVE_AUTO_POSITION: 當MASTER_AUTO_POSITION處於活動狀態時，不能設定參數MASTER_LOG_FILE、MASTER_LOG_POS、RELAY_LOG_FILE和RELAY_LOG_POS"},
            { 1777, "ER_AUTO_POSITION_REQUIRES_GTID_MODE_ON: 只有當@@GLOBAL.GTID_MODE = ON時，才能執行CHANGE MASTER TO MASTER_AUTO_POSITION = 1"},
            { 1778, "ER_CANNOT_DO_IMPLICIT_COMMIT_IN_TRX_WHEN_GTID_NEXT_IS_SET: 當@@SESSION.GTID_NEXT != AUTOMATIC時，不能在事務內部執行具有隱式提交的語句"},
            { 1779, "ER_GTID_MODE_2_OR_3_REQUIRES_ENFORCE_GTID_CONSISTENCY_ON: @@GLOBAL.GTID_MODE = ON或UPGRADE_STEP_2需要@@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1"},
            { 1780, "ER_GTID_MODE_REQUIRES_BINLOG: @@GLOBAL.GTID_MODE = ON或UPGRADE_STEP_1或UPGRADE_STEP_2需要--log-bin和--log-slave-updates"},
            { 1781, "ER_CANT_SET_GTID_NEXT_TO_GTID_WHEN_GTID_MODE_IS_OFF: 當@@GLOBAL.GTID_MODE = OFF時，@@SESSION.GTID_NEXT不能設定為UUID:NUMBER"},
            { 1782, "ER_CANT_SET_GTID_NEXT_TO_ANONYMOUS_WHEN_GTID_MODE_IS_ON: 當@@GLOBAL.GTID_MODE = ON時，@@SESSION.GTID_NEXT不能設定為ANONYMOUS"},
            { 1783, "ER_CANT_SET_GTID_NEXT_LIST_TO_NON_NULL_WHEN_GTID_MODE_IS_OFF: 當@@GLOBAL.GTID_MODE = OFF時，@@SESSION.GTID_NEXT_LIST不能設定為非NULL值"},
            { 1784, "ER_FOUND_GTID_EVENT_WHEN_GTID_MODE_IS_OFF: 當@@GLOBAL.GTID_MODE = OFF時，找到Gtid_log_event或Previous_gtids_log_event"},
            { 1785, "ER_GTID_UNSAFE_NON_TRANSACTIONAL_TABLE: 當@@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1時，對非事務性表的更新只能在自動提交語句或單語句事務中完成，並且永遠不能與對事務性表的更新在同一語句中"},
            { 1786, "ER_GTID_UNSAFE_CREATE_SELECT: 當@@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1時，禁止CREATE TABLE ... SELECT"},
            { 1787, "ER_GTID_UNSAFE_CREATE_DROP_TEMPORARY_TABLE_IN_TRANSACTION: 當@@GLOBAL.ENFORCE_GTID_CONSISTENCY = 1時，語句CREATE TEMPORARY TABLE和DROP TEMPORARY TABLE只能在非事務性上下文中執行，並且需要AUTOCOMMIT = 1"},
            { 1788, "ER_GTID_MODE_CAN_ONLY_CHANGE_ONE_STEP_AT_A_TIME: @@GLOBAL.GTID_MODE的值只能一次更改一步: OFF <-> UPGRADE_STEP_1 <-> UPGRADE_STEP_2 <-> ON。另請注意，此值必須在所有伺服器上同時遞增或遞減; 有關說明，請參閱手冊"},
            { 1789, "ER_MASTER_HAS_PURGED_REQUIRED_GTIDS: 從伺服器使用CHANGE MASTER TO MASTER_AUTO_POSITION = 1連接，但主伺服器已清除包含從伺服器所需GTID的二進位日誌"},
            { 1790, "ER_CANT_SET_GTID_NEXT_WHEN_OWNING_GTID: 擁有GTID的客戶端無法更改@@SESSION.GTID_NEXT。客戶端擁有%s。所有權在COMMIT或ROLLBACK時釋放"},
            { 1791, "ER_UNKNOWN_EXPLAIN_FORMAT: 未知的EXPLAIN格式名稱: '%s'"},
            { 1792, "ER_CANT_EXECUTE_IN_READ_ONLY_TRANSACTION: 不能在唯讀事務中執行語句"},
            { 1793, "ER_TOO_LONG_TABLE_PARTITION_COMMENT: 表分割區'%-.64s'的註解過長(最大 = %lu)"},
            { 1794, "ER_SLAVE_CONFIGURATION: 從伺服器未配置或未能正確初始化。您必須至少設定--server-id以啟用主伺服器或從伺服器。其他錯誤訊息可以在MySQL錯誤日誌中找到"},
            { 1795, "ER_INNODB_FT_LIMIT: InnoDB目前一次支援一個FULLTEXT索引建立"},
            { 1796, "ER_INNODB_NO_FT_TEMP_TABLE: 不能在臨時InnoDB表上建立FULLTEXT索引"},
            { 1797, "ER_INNODB_FT_WRONG_DOCID_COLUMN: 列'%-.192s'的類型錯誤，不適合InnoDB FULLTEXT索引"},
            { 1798, "ER_INNODB_FT_WRONG_DOCID_INDEX: 索引'%-.192s'的類型錯誤，不適合InnoDB FULLTEXT索引"},
            { 1799, "ER_INNODB_ONLINE_LOG_TOO_BIG: 建立索引'%-.192s'需要超過'innodb_online_alter_log_max_size'位元組的修改日誌。請重試"},
            { 1800, "ER_UNKNOWN_ALTER_ALGORITHM: 未知的ALGORITHM '%s'"},
            { 1801, "ER_UNKNOWN_ALTER_LOCK: 未知的LOCK類型'%s'"},
            { 1802, "ER_MTS_CHANGE_MASTER_CANT_RUN_WITH_GAPS: 當從伺服器在MTS模式下因錯誤停止或被殺死時，無法執行CHANGE MASTER。請考慮使用RESET SLAVE或START SLAVE UNTIL"},
            { 1803, "ER_MTS_RECOVERY_FAILURE: 在平行執行模式下從伺服器出錯後無法恢復。其他錯誤訊息可以在MySQL錯誤日誌中找到"},
            { 1804, "ER_MTS_RESET_WORKERS: 無法清理工作執行緒資訊表。其他錯誤訊息可以在MySQL錯誤日誌中找到"},
            { 1805, "ER_COL_COUNT_DOESNT_MATCH_CORRUPTED_V2: %s.%s的列計數錯誤。預期%d，找到%d。表可能已損壞"},
            { 1806, "ER_SLAVE_SILENT_RETRY_TRANSACTION: 從伺服器必須靜默重試目前事務"},
            { 1807, "ER_DISCARD_FK_CHECKS_RUNNING: 表'%-.192s'上正在執行外鍵檢查。無法丟棄該表"},
            { 1808, "ER_TABLE_SCHEMA_MISMATCH: 架構不匹配(%s)"},
            { 1809, "ER_TABLE_IN_SYSTEM_TABLESPACE: 表'%-.192s'在系統表空間中"},
            { 1810, "ER_IO_READ_ERROR: IO讀取錯誤: (%lu, %s) %s"},
            { 1811, "ER_IO_WRITE_ERROR: IO寫入錯誤: (%lu, %s) %s"},
            { 1812, "ER_TABLESPACE_MISSING: 表'%-.192s'的表空間缺失"},
            { 1813, "ER_TABLESPACE_EXISTS: 表'%-.192s'的表空間已存在。請在IMPORT之前DISCARD表空間"},
            { 1814, "ER_TABLESPACE_DISCARDED: 表'%-.192s'的表空間已被丟棄"},
            { 1815, "ER_INTERNAL_ERROR: 內部錯誤: %s"},
            { 1816, "ER_INNODB_IMPORT_ERROR: ALTER TABLE '%-.192s' IMPORT TABLESPACE失敗，錯誤%lu: '%s'"},
            { 1817, "ER_INNODB_INDEX_CORRUPT: 索引損壞: %s"},
            { 1818, "ER_INVALID_YEAR_COLUMN_LENGTH: YEAR(%lu)列類型已棄用。改為建立YEAR(4)列"},
            { 1819, "ER_NOT_VALID_PASSWORD: 您的密碼不滿足目前策略要求"},
            { 1820, "ER_MUST_CHANGE_PASSWORD: 在執行此語句之前必須設定密碼"},
            { 1821, "ER_FK_NO_INDEX_CHILD: 新增外鍵約束失敗。外部表'%s'中約束'%s'缺少索引"},
            { 1822, "ER_FK_NO_INDEX_PARENT: 新增外鍵約束失敗。參考表'%s'中約束'%s'缺少索引"},
            { 1823, "ER_FK_FAIL_ADD_SYSTEM: 將外鍵約束'%s'新增到系統表失敗"},
            { 1824, "ER_FK_CANNOT_OPEN_PARENT: 無法開啟參考表'%s'"},
            { 1825, "ER_FK_INCORRECT_OPTION: 在表'%s'上新增外鍵約束失敗。外鍵約束'%s'中的選項不正確"},
            { 1826, "ER_FK_DUP_NAME: 重複的外鍵約束名稱'%s'"},
            { 1827, "ER_PASSWORD_FORMAT: 密碼雜湊沒有預期的格式。檢查是否使用PASSWORD()函數使用了正確的密碼演算法"},
            { 1828, "ER_FK_COLUMN_CANNOT_DROP: 無法刪除列'%-.192s': 外鍵約束'%-.192s'中需要"},
            { 1829, "ER_FK_COLUMN_CANNOT_DROP_CHILD: 無法刪除列'%-.192s': 表'%-.192s'的外鍵約束'%-.192s'中需要"},
            { 1830, "ER_FK_COLUMN_NOT_NULL: 列'%-.192s'不能為NOT NULL: 外鍵約束'%-.192s' SET NULL中需要"},
            { 1831, "ER_DUP_INDEX: 在表'%-.64s.%-.64s'上定義了重複的索引'%-.64s'。這已棄用，將在未來版本中不允許"},
            { 1832, "ER_FK_COLUMN_CANNOT_CHANGE: 無法更改列'%-.192s': 在外鍵約束'%-.192s'中使用"},
            { 1833, "ER_FK_COLUMN_CANNOT_CHANGE_CHILD: 無法更改列'%-.192s': 在表'%-.192s'的外鍵約束'%-.192s'中使用"},
            { 1834, "ER_FK_CANNOT_DELETE_PARENT: 無法從作為表'%-.192s'外鍵約束'%-.192s'的父表中刪除行"},
            { 1835, "ER_MALFORMED_PACKET: 格式錯誤的通訊資料包"},
            { 1836, "ER_READ_ONLY_MODE: 在唯讀模式下執行"},
            { 1837, "ER_GTID_NEXT_TYPE_UNDEFINED_GROUP: 當@@SESSION.GTID_NEXT設定為GTID時，必須在COMMIT或ROLLBACK後顯式將其設定為不同的值。請檢查GTID_NEXT變數手冊頁面以獲取詳細說明。目前@@SESSION.GTID_NEXT為'%s'"},
            { 1838, "ER_VARIABLE_NOT_SETTABLE_IN_SP: 系統變數%.200s不能在儲存程序中設定"},
            { 1839, "ER_CANT_SET_GTID_PURGED_WHEN_GTID_MODE_IS_OFF: 只有當@@GLOBAL.GTID_MODE = ON時，才能設定@@GLOBAL.GTID_PURGED"},
            { 1840, "ER_CANT_SET_GTID_PURGED_WHEN_GTID_EXECUTED_IS_NOT_EMPTY: 只有當@@GLOBAL.GTID_EXECUTED為空時，才能設定@@GLOBAL.GTID_PURGED"},
            { 1841, "ER_CANT_SET_GTID_PURGED_WHEN_OWNED_GTIDS_IS_NOT_EMPTY: 只有當沒有正在進行的事務時(即使在其他客戶端中也沒有)，才能設定@@GLOBAL.GTID_PURGED"},
            { 1842, "ER_GTID_PURGED_WAS_CHANGED: @@GLOBAL.GTID_PURGED從'%s'更改為'%s'"},
            { 1843, "ER_GTID_EXECUTED_WAS_CHANGED: @@GLOBAL.GTID_EXECUTED從'%s'更改為'%s'"},
            { 1844, "ER_BINLOG_STMT_MODE_AND_NO_REPL_TABLES: 無法執行語句: 由於BINLOG_FORMAT = STATEMENT，無法寫入二進位日誌，並且同時寫入複製和非複製表"},
            { 1845, "ER_ALTER_OPERATION_NOT_SUPPORTED: 此操作不支援%s。請嘗試%s"},
            { 1846, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON: 不支援%s。原因: %s。請嘗試%s"},
            { 1847, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_COPY: COPY演算法需要鎖"},
            { 1848, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_PARTITION: 分割區特定操作尚不支援LOCK/ALGORITHM"},
            { 1849, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FK_RENAME: 參與外鍵的列被重新命名"},
            { 1850, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_COLUMN_TYPE: 無法原地更改列類型"},
            { 1851, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FK_CHECK: 新增外鍵需要foreign_key_checks=OFF"},
            { 1852, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_IGNORE: 建立唯一索引時使用IGNORE需要COPY演算法來移除重複行"},
            { 1853, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_NOPK: 不允許在沒有同時新增新主鍵的情況下刪除主鍵"},
            { 1854, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_AUTOINC: 新增自增列需要鎖"},
            { 1855, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_HIDDEN_FTS: 無法用使用者可見的FTS_DOC_ID替換隱藏的FTS_DOC_ID"},
            { 1856, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_CHANGE_FTS: 無法刪除或重新命名FTS_DOC_ID"},
            { 1857, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_FTS: 全文索引建立需要鎖"},
            { 1858, "ER_SQL_SLAVE_SKIP_COUNTER_NOT_SETTABLE_IN_GTID_MODE: 當伺服器執行在@@GLOBAL.GTID_MODE = ON時，不能設定sql_slave_skip_counter。相反，對於每個要跳過的事務，產生一個具有相同GTID的空事務"},
            { 1859, "ER_DUP_UNKNOWN_IN_INDEX: 鍵'%-.192s'的重複條目"},
            { 1860, "ER_IDENT_CAUSES_TOO_LONG_PATH: 長資料庫名稱和物件識別碼導致路徑長度超過%d個字元。路徑: '%s'。"},
            { 1861, "ER_ALTER_OPERATION_NOT_SUPPORTED_REASON_NOT_NULL: 無法靜默轉換NULL值，如在此SQL_MODE中所要求"},
            { 1862, "ER_MUST_CHANGE_PASSWORD_LOGIN: 您的密碼已過期。要登入，您必須使用支援過期密碼的客戶端更改它。"},
            { 1863, "ER_ROW_IN_WRONG_PARTITION: 在錯誤的分割區%s中找到一行"},
            { 1864, "ER_MTS_EVENT_BIGGER_PENDING_JOBS_SIZE_MAX: 無法將事件%s，中繼日誌名稱%s，位置%s排程到工作執行緒，因為其大小%lu超過slave_pending_jobs_size_max的%lu。"},
            { 1865, "ER_INNODB_NO_FT_USES_PARSER: 無法在InnoDB表上使用解析器建立全文索引"},
            { 1866, "ER_BINLOG_LOGICAL_CORRUPTION: 二進位日誌檔案'%s'邏輯損壞: %s"},
            { 1867, "ER_WARN_PURGE_LOG_IN_USE: 檔案%s未被清除，因為它被%d個執行緒讀取，僅清除了%d個檔案中的%d個。"},
            { 1868, "ER_WARN_PURGE_LOG_IS_ACTIVE: 檔案%s未被清除，因為它是活動日誌檔案。"},
            { 1869, "ER_AUTO_INCREMENT_CONFLICT: UPDATE中的自增值與內部產生的值衝突"},
            { 1870, "WARN_ON_BLOCKHOLE_IN_RBR: 對於在行格式中修改BLACKHOLE表的%s語句，不記錄行事件。表: '%-.192s'"},
            { 1871, "ER_SLAVE_MI_INIT_REPOSITORY: 從伺服器未能從儲存庫初始化主資訊結構"},
            { 1872, "ER_SLAVE_RLI_INIT_REPOSITORY: 從伺服器未能從儲存庫初始化中繼日誌資訊結構"},
            { 1873, "ER_ACCESS_DENIED_CHANGE_USER_ERROR: 拒絕存取嘗試更改使用者'%-.48s'@'%-.64s'(使用密碼: %s)。斷開連接。"},
            { 1874, "ER_INNODB_READ_ONLY: InnoDB處於唯讀模式。"},
            { 1875, "ER_STOP_SLAVE_SQL_THREAD_TIMEOUT: STOP SLAVE命令執行不完整: 從伺服器SQL執行緒收到停止信號，執行緒繁忙，SQL執行緒將在目前任務完成後停止。"},
            { 1876, "ER_STOP_SLAVE_IO_THREAD_TIMEOUT: STOP SLAVE命令執行不完整: 從伺服器IO執行緒收到停止信號，執行緒繁忙，IO執行緒將在目前任務完成後停止。"},
            { 1877, "ER_TABLE_CORRUPT: 無法執行操作。表'%-.64s.%-.64s'缺失、損壞或包含錯誤資料。"},
            { 1878, "ER_TEMP_FILE_WRITE_FAILURE: 臨時檔案寫入失敗。"},
            { 1879, "ER_INNODB_FT_AUX_NOT_HEX_ID: 升級索引名稱失敗，請使用建立索引(alter table)演算法copy來重建索引。"},
            { 1880, "ER_OLD_TEMPORALS_UPGRADED: TIME/TIMESTAMP/DATETIME列的舊格式已升級為新格式。"},
            { 1881, "ER_INNODB_FORCED_RECOVERY: 當innodb_forced_recovery > 0時不允許操作。"},
            { 1882, "ER_AES_INVALID_IV: 提供給%s的初始化向量太短。必須至少%d位元組長"},
            { 1883, "ER_PLUGIN_CANNOT_BE_UNINSTALLED: 插件'%s'現在無法解除安裝。%s"},
            { 1884, "ER_GTID_UNSAFE_BINLOG_SPLITTABLE_STATEMENT_AND_GTID_GROUP: 無法執行語句，因為它需要作為多個語句寫入二進位日誌，而當@@SESSION.GTID_NEXT == 'UUID:NUMBER'時不允許這樣做。"},
            { 1885, "ER_SLAVE_HAS_MORE_GTIDS_THAN_MASTER: 從伺服器比主伺服器有更多的GTID，使用主伺服器的SERVER_UUID。這可能表明二進位日誌的末尾被截斷或最後一個二進位日誌檔案丟失，例如，當sync_binlog != 1時發生電源或磁碟故障。主伺服器可能回滾了已複製到從伺服器的事務，也可能沒有。建議將主伺服器已回滾的任何從事務複製到主伺服器，和/或在主伺服器上提交空事務以說明已在主伺服器上提交但未包含在GTID_EXECUTED中的事務。"},
            { 1886, "ER_QUERY_TIMEOUT: 查詢執行被中斷，超過max_statement_time"},
            { 1887, "ER_CANT_EXECUTE_WITH_BACKUP_LOCK: 由於您有衝突的備份鎖，無法執行查詢"}
        };
    }
}