using MyTool.Enums;

namespace MyTool
{
    public static partial class ConstString
    {
        // 英文 HTTP 状态码描述
        private static readonly Dictionary<long, string> HttpStatusMapEnglish = new()
        {
            { 100, "Continue" },
            { 101, "Switching Protocols" },
            { 102, "Processing" },
            { 103, "Early Hints" },
            { 200, "OK" },
            { 201, "Created" },
            { 202, "Accepted" },
            { 203, "Non-Authoritative Information" },
            { 204, "No Content" },
            { 205, "Reset Content" },
            { 206, "Partial Content" },
            { 207, "Multi-Status" },
            { 208, "Already Reported" },
            { 226, "IM Used" },
            { 300, "Multiple Choices" },
            { 301, "Moved Permanently" },
            { 302, "Found" },
            { 303, "See Other" },
            { 304, "Not Modified" },
            { 305, "Use Proxy" },
            { 306, "Switch Proxy" },
            { 307, "Temporary Redirect" },
            { 308, "Permanent Redirect" },
            { 400, "Bad Request" },
            { 401, "Unauthorized" },
            { 402, "Payment Required" },
            { 403, "Forbidden" },
            { 404, "Not Found" },
            { 405, "Method Not Allowed" },
            { 406, "Not Acceptable" },
            { 407, "Proxy Authentication Required" },
            { 408, "Request Timeout" },
            { 409, "Conflict" },
            { 410, "Gone" },
            { 411, "Length Required" },
            { 412, "Precondition Failed" },
            { 413, "Payload Too Large" },
            { 414, "URI Too Long" },
            { 415, "Unsupported Media Type" },
            { 416, "Range Not Satisfiable" },
            { 417, "Expectation Failed" },
            { 418, "I'm a teapot" },
            { 421, "Misdirected Request" },
            { 422, "Unprocessable Entity" },
            { 423, "Locked" },
            { 424, "Failed Dependency" },
            { 425, "Too Early" },
            { 426, "Upgrade Required" },
            { 428, "Precondition Required" },
            { 429, "Too Many Requests" },
            { 431, "Request Header Fields Too Large" },
            { 451, "Unavailable For Legal Reasons" },
            { 500, "Internal Server Error" },
            { 501, "Not Implemented" },
            { 502, "Bad Gateway" },
            { 503, "Service Unavailable" },
            { 504, "Gateway Timeout" },
            { 505, "HTTP Version Not Supported" },
            { 506, "Variant Also Negotiates" },
            { 507, "Insufficient Storage" },
            { 508, "Loop Detected" },
            { 510, "Not Extended" },
            { 511, "Network Authentication Required" },
            { 599, "Network Connect Timeout Error" }
        };

        // 简体中文 HTTP 状态码描述
        private static readonly Dictionary<long, string> HttpStatusMapSimplifiedChinese = new()
        {
            { 100, "继续" },
            { 101, "切换协议" },
            { 102, "处理中" },
            { 103, "早期提示" },
            { 200, "成功" },
            { 201, "已创建" },
            { 202, "已接受" },
            { 203, "非授权信息" },
            { 204, "无内容" },
            { 205, "重置内容" },
            { 206, "部分内容" },
            { 207, "多状态" },
            { 208, "已报告" },
            { 226, "IM 已使用" },
            { 300, "多种选择" },
            { 301, "永久移动" },
            { 302, "临时移动" },
            { 303, "查看其他位置" },
            { 304, "未修改" },
            { 305, "使用代理" },
            { 306, "切换代理" },
            { 307, "临时重定向" },
            { 308, "永久重定向" },
            { 400, "错误请求" },
            { 401, "未授权" },
            { 402, "需要付款" },
            { 403, "禁止访问" },
            { 404, "未找到" },
            { 405, "方法不允许" },
            { 406, "不接受" },
            { 407, "需要代理授权" },
            { 408, "请求超时" },
            { 409, "冲突" },
            { 410, "已失效" },
            { 411, "需要有效长度" },
            { 412, "前置条件失败" },
            { 413, "请求实体过大" },
            { 414, "请求 URI 过长" },
            { 415, "不支持的媒体类型" },
            { 416, "请求范围不符合要求" },
            { 417, "期望失败" },
            { 418, "我是一个茶壶" },
            { 421, "误导请求" },
            { 422, "不可处理的实体" },
            { 423, "已锁定" },
            { 424, "依赖失败" },
            { 425, "过早" },
            { 426, "需要升级" },
            { 428, "需要前置条件" },
            { 429, "请求过多" },
            { 431, "请求头字段过大" },
            { 451, "因法律原因不可用" },
            { 500, "内部服务器错误" },
            { 501, "尚未实施" },
            { 502, "错误网关" },
            { 503, "服务不可用" },
            { 504, "网关超时" },
            { 505, "HTTP 版本不受支持" },
            { 506, "变体也协商" },
            { 507, "存储空间不足" },
            { 508, "检测到循环" },
            { 510, "不扩展" },
            { 511, "需要网络认证" },
            { 599, "网络连接超时错误" }
        };

        // 繁体中文 HTTP 状态码描述
        private static readonly Dictionary<long, string> HttpStatusMapTraditionalChinese = new()
        {
            { 100, "繼續" },
            { 101, "切換協議" },
            { 102, "處理中" },
            { 103, "早期提示" },
            { 200, "成功" },
            { 201, "已創建" },
            { 202, "已接受" },
            { 203, "非授權信息" },
            { 204, "無內容" },
            { 205, "重置內容" },
            { 206, "部分內容" },
            { 207, "多狀態" },
            { 208, "已報告" },
            { 226, "IM 已使用" },
            { 300, "多種選擇" },
            { 301, "永久移動" },
            { 302, "臨時移動" },
            { 303, "查看其他位置" },
            { 304, "未修改" },
            { 305, "使用代理" },
            { 306, "切換代理" },
            { 307, "臨時重定向" },
            { 308, "永久重定向" },
            { 400, "錯誤請求" },
            { 401, "未授權" },
            { 402, "需要付款" },
            { 403, "禁止訪問" },
            { 404, "未找到" },
            { 405, "方法不允許" },
            { 406, "不接受" },
            { 407, "需要代理授權" },
            { 408, "請求超時" },
            { 409, "衝突" },
            { 410, "已失效" },
            { 411, "需要有效長度" },
            { 412, "前置條件失敗" },
            { 413, "請求實體過大" },
            { 414, "請求 URI 過長" },
            { 415, "不支持的媒體類型" },
            { 416, "請求範圍不符合要求" },
            { 417, "期望失敗" },
            { 418, "我是個茶壺" },
            { 421, "誤導請求" },
            { 422, "不可處理的實體" },
            { 423, "已鎖定" },
            { 424, "依賴失敗" },
            { 425, "過早" },
            { 426, "需要升級" },
            { 428, "需要前置條件" },
            { 429, "請求過多" },
            { 431, "請求頭字段過大" },
            { 451, "因法律原因不可用" },
            { 500, "內部服務器錯誤" },
            { 501, "尚未實施" },
            { 502, "錯誤網關" },
            { 503, "服務不可用" },
            { 504, "網關超時" },
            { 505, "HTTP 版本不受支持" },
            { 506, "變體也協商" },
            { 507, "存儲空間不足" },
            { 508, "檢測到循環" },
            { 510, "不擴展" },
            { 511, "需要網絡認證" },
            { 599, "網絡連接超時錯誤" }
        };

        // HTTP 状态码
        public static Dictionary<long, string> HttpStatusMap
        {
            get
            {
                return GlobalState.CurrentLanguageType switch
                {
                    LanguageType.SimplifiedChinese => HttpStatusMapSimplifiedChinese,
                    LanguageType.TraditionalChinese => HttpStatusMapTraditionalChinese,
                    _ => HttpStatusMapEnglish
                };
            }
        }
    }
}