using System.Collections.Generic;

namespace MyTool
{
    public static partial class ConstString
    {
        // Linux errno 错误码
        public static readonly Dictionary<long, string> LinuxErrnoMap = new()
        {
            { 0, "Success" },
            { 1, "Operation not permitted" },
            { 2, "No such file or directory" },
            { 3, "No such process" },
            { 4, "Interrupted system call" },
            { 5, "Input/output error" },
            { 6, "No such device or address" },
            { 7, "Argument list too long" },
            { 8, "Exec format error" },
            { 9, "Bad file descriptor" },
            { 10, "No child processes" },
            { 11, "Resource temporarily unavailable" },
            { 12, "Cannot allocate memory" },
            { 13, "Permission denied" },
            { 14, "Bad address" },
            { 15, "Block device required" },
            { 16, "Device or resource busy" },
            { 17, "File exists" },
            { 18, "Invalid cross-device link" },
            { 19, "No such device" },
            { 20, "Not a directory" },
            { 21, "Is a directory" },
            { 22, "Invalid argument" },
            { 23, "Too many open files in system" },
            { 24, "Too many open files" },
            { 25, "Inappropriate ioctl for device" },
            { 26, "Text file busy" },
            { 27, "File too large" },
            { 28, "No space left on device" },
            { 29, "Illegal seek" },
            { 30, "Read-only file system" },
            { 31, "Too many links" },
            { 32, "Broken pipe" },
            { 33, "Numerical argument out of domain" },
            { 34, "Numerical result out of range" },
            { 35, "Resource deadlock avoided" },
            { 36, "File name too long" },
            { 37, "No locks available" },
            { 38, "Function not implemented" },
            { 39, "Directory not empty" },
            { 40, "Too many symbolic links encountered" },
            { 42, "No message of desired type" },
            { 43, "Identifier removed" },
            { 50, "No message available" },
            { 51, "Identifier removed" },
            { 52, "Channel number out of range" },
            { 53, "Level 2 not synchronized" },
            { 54, "Level 3 halted" },
            { 55, "Level 3 reset" },
            { 56, "Link number out of range" },
            { 57, "Protocol driver not attached" },
            { 58, "No CSI structure available" },
            { 59, "Level 2 halted" },
            { 60, "Timer expired" },
            { 61, "Connection refused" },
            { 62, "Connection aborted" },
            { 63, "Protocol error" },
            { 64, "Multihop attempted" },
            { 65, "RFS specific error" },
            { 66, "Invalid message" },
            { 67, "Value too large for defined data type" },
            { 68, "Name not unique on network" },
            { 69, "File descriptor in bad state" },
            { 70, "Remote address changed" },
            { 71, "Can not access a needed shared library" },
            { 72, "Accessing a corrupted shared library" },
            { 73, ".lib section in a.out corrupted" },
            { 74, "Attempting to link in too many shared libraries" },
            { 75, "Cannot exec a shared library directly" },
            { 76, "Illegal byte sequence" },
            { 77, "Interrupted system call should be restarted" },
            { 78, "Streams pipe error" },
            { 79, "Too many users" },
            { 80, "Socket operation on non-socket" },
            { 81, "Destination address required" },
            { 82, "Message too long" },
            { 83, "Protocol wrong type for socket" },
            { 84, "Protocol not available" },
            { 85, "Protocol not supported" },
            { 86, "Socket type not supported" },
            { 87, "Operation not supported on transport endpoint" },
            { 88, "Protocol family not supported" },
            { 89, "Address family not supported by protocol" },
            { 90, "Address already in use" },
            { 91, "Cannot assign requested address" },
            { 92, "Network is down" },
            { 93, "Network is unreachable" },
            { 94, "Network dropped connection because of reset" },
            { 95, "Software caused connection abort" },
            { 96, "Connection reset by peer" },
            { 97, "No buffer space available" },
            { 98, "Transport endpoint is already connected" },
            { 99, "Transport endpoint is not connected" },
            { 100, "Cannot send after transport endpoint shutdown" },
            { 101, "Too many references: cannot splice" },
            { 102, "Connection timed out" },
            { 103, "Connection refused" },
            { 104, "Host is down" },
            { 105, "No route to host" },
            { 106, "Operation already in progress" },
            { 107, "Operation now in progress" },
            { 108, "Stale NFS file handle" },
            { 109, "Structure needs cleaning" },
            { 110, "Not a XENIX named type file" },
            { 111, "No XENIX semaphores available" },
            { 112, "Is a named type file" },
            { 113, "Remote I/O error" },
            { 114, "Quota exceeded" },
            { 115, "No medium found" },
            { 116, "Wrong medium type" },
            { 117, "Operation Canceled" },
            { 118, "Required key not available" },
            { 119, "Key has expired" },
            { 120, "Key has been revoked" },
            { 121, "Key was rejected by service" },
            { 122, "Owner died" },
            { 123, "State not recoverable" },
            { 124, "Operation not possible due to RF-kill" },
            { 125, "Memory page has hardware error" }
        };
    }
}