using PersonalTools.Utils;
using PersonalTools.Enums;

namespace PersonalTools.ConstString
{
    internal static partial class SqlServerErrors
    {
        // SQL Server 错误码 - 英文
        private static readonly Dictionary<long, string> SqlServerErrorsMapEnglish = new()
        {
            { 100, "Return warning information" },
            { 150, "Both terms of an outer join must contain columns" },
            { 170, "Incorrect syntax near (parser syntax error)" },
            { 201, "Procedure or function requires parameter" },
            { 207, "Invalid column name" },
            { 208, "Invalid object name" },
            { 245, "Conversion failed when converting the varchar value to data type int" },
            { 266, "Transaction count after EXECUTE indicates mismatched BEGIN and COMMIT statements" },
            { 297, "User account lacks sufficient permissions" },
            { 310, "The value specified for the MAXRECURSION option exceeds the allowed maximum of 32767" },
            { 403, "Invalid operator for data type" },
            { 421, "The data type cannot be selected as DISTINCT because it is not comparable" },
            { 512, "Subquery returned more than one value" },
            { 515, "Cannot insert the value NULL into column" },
            { 517, "Adding a value to a datetime column caused an overflow" },
            { 547, "Statement conflicts with column reference constraint" },
            { 550, "The insert or update failed because the target view specifies WITH CHECK OPTION and a resulting row did not qualify under the CHECK OPTION constraint" },
            { 615, "Could not find database ID; the database may be offline" },
            { 911, "Invalid database" },
            { 948, "Database version incompatible" },
            { 1007, "The number is out of the range for numeric representation (maximum precision 38)" },
            { 1205, "Deadlock" },
            { 1511, "Sort cannot be reconciled with transaction log" },
            { 1563, "Cannot create constraint" },
            { 1742, "Cannot create index on a view that contains a self join" },
            { 1750, "Cannot create constraint" },
            { 1801, "Database already exists" },
            { 1807, "Timeout acquiring database lock" },
            { 1834, "Device is being used by an existing resource" },
            { 18456, "Login failed" },
            { 2601, "Duplicate key" },
            { 2627, "Violation of unique constraint condition" },
            { 2714, "Object name already exists" },
            { 3701, "Object does not exist" },
            { 3902, "The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION" },
            { 3903, "The ROLLBACK TRANSACTION request has no corresponding BEGIN TRANSACTION" },
            { 4060, "Cannot open database" },
            { 5028, "The system could not activate enough of the database to rebuild the log" },
            { 5123, "CREATE FILE encountered operating system error" },
            { 5172, "File header incorrect" },
            { 7915, "Repair: IAM chain for the object has been truncated and will be rebuilt" },
            { 8623, "Internal query processor limit" },
            { 8642, "Internal query processor error" },
            { 8651, "Out of memory" },
            { 9001, "The log for the database is not available; resolve errors and restart the database" },
            { 9002, "Transaction log full" },
            { 10053, "Network connection interrupted" },
            { 10054, "Existing connection forcibly closed by remote host" },
            { 10060, "Connection timeout" },
            { 10061, "Target computer actively refused connection" },
            { 11001, "Hostname not found" },
            { 11011, "Replication table has no primary key" },
            { 14001, "DLL required by application is missing" },
            { 15601, "Full-Text Search is not enabled for the current database" },
            { 17187, "SQL Server is not ready to accept new client connections; wait a few minutes and try again" },
            { 18452, "Cannot use Windows authentication" },
            { 23294, "Object is being used by another process" },
            { 26024, "Failed to start service" },
            { 99999, "SQL Server error - unknown error" }
        };

        // SQL Server 错误码 - 简体中文
        private static readonly Dictionary<long, string> SqlServerErrorsMapSimplifiedChinese = new()
        {
            { 100, "返回警告信息" },
            { 150, "外连接的两个词条都必须包含列" },
            { 170, "语法错误(near 附近有不正确的语法)" },
            { 201, "过程或函数需要参数" },
            { 207, "列名无效" },
            { 208, "对象名无效" },
            { 245, "将 varchar 值转换为数据类型 int 时出错" },
            { 266, "EXECUTE 后的事务计数表明 BEGIN 和 COMMIT 语句数不匹配" },
            { 297, "用户帐户权限不足" },
            { 310, "为 MAXRECURSION 选项指定的值超过允许的最大值 32767" },
            { 403, "该数据类型的运算符无效" },
            { 421, "该数据类型不可比较，不能作为 DISTINCT 选择" },
            { 512, "子查询返回的值多于一个" },
            { 515, "不能将值 NULL 插入列" },
            { 517, "向 datetime 列添加值导致溢出" },
            { 547, "语句与列引用约束冲突" },
            { 550, "插入或更新失败：目标视图指定了 WITH CHECK OPTION，且结果行不满足该 CHECK OPTION 约束" },
            { 615, "找不到数据库 ID，数据库可能已离线" },
            { 911, "数据库无效" },
            { 948, "数据库版本不兼容" },
            { 1007, "值超出数值表示范围（最大精度 38）" },
            { 1205, "死锁" },
            { 1511, "排序无法与事务日志协调" },
            { 1563, "无法创建约束" },
            { 1742, "无法在包含自连接的视图上创建索引" },
            { 1750, "无法创建约束" },
            { 1801, "数据库已存在" },
            { 1807, "获取数据库锁时超时" },
            { 1834, "设备正由某个现有资源使用" },
            { 18456, "登录失败" },
            { 2601, "重复键" },
            { 2627, "违反唯一约束条件" },
            { 2714, "对象名已存在" },
            { 3701, "对象不存在" },
            { 3902, "COMMIT TRANSACTION 请求没有对应的 BEGIN TRANSACTION" },
            { 3903, "ROLLBACK TRANSACTION 请求没有对应的 BEGIN TRANSACTION" },
            { 4060, "无法打开数据库" },
            { 5028, "系统无法激活足够的数据库来重建日志" },
            { 5123, "CREATE FILE遇到操作系统错误" },
            { 5172, "文件头不正确" },
            { 7915, "修复: 对象的 IAM 链已被截断，将被重建" },
            { 8623, "内部查询处理器限制" },
            { 8642, "内部查询处理器错误" },
            { 8651, "内存不足" },
            { 9001, "数据库的日志不可用；请解决错误后重启数据库" },
            { 9002, "事务日志已满" },
            { 10053, "网络连接中断" },
            { 10054, "现有连接被远程主机强制关闭" },
            { 10060, "连接超时" },
            { 10061, "目标计算机积极拒绝连接" },
            { 11001, "找不到主机名" },
            { 11011, "复制表没有主键" },
            { 14001, "应用程序依赖的DLL缺失" },
            { 15601, "当前数据库未启用全文搜索" },
            { 17187, "SQL Server 尚未就绪接受新客户端连接；请稍候几分钟后重试" },
            { 18452, "无法使用 Windows 身份验证" },
            { 23294, "对象正被另一进程使用" },
            { 26024, "启动服务失败" },
            { 99999, "SQL Server 错误 - 未知错误" }
        };

        // SQL Server 错误码 - 繁体中文
        private static readonly Dictionary<long, string> SqlServerErrorsMapTraditionalChinese = new()
        {
            { 100, "返回警告資訊" },
            { 150, "外連接的兩個詞條都必須包含列" },
            { 170, "語法錯誤(near 附近有不正確的語法)" },
            { 201, "過程或函數需要參數" },
            { 207, "列名無效" },
            { 208, "物件名無效" },
            { 245, "將 varchar 值轉換為資料類型 int 時出錯" },
            { 266, "EXECUTE 後的事務計數表明 BEGIN 和 COMMIT 語句數不匹配" },
            { 297, "用戶帳戶權限不足" },
            { 310, "為 MAXRECURSION 選項指定的值超過允許的最大值 32767" },
            { 403, "該資料類型的運算子無效" },
            { 421, "該資料類型不可比較，不能作為 DISTINCT 選擇" },
            { 512, "子查詢返回的值多於一個" },
            { 515, "不能將值 NULL 插入列" },
            { 517, "向 datetime 列添加值導致溢位" },
            { 547, "語句與列引用約束衝突" },
            { 550, "插入或更新失敗：目標視圖指定了 WITH CHECK OPTION，且結果行不滿足該 CHECK OPTION 約束" },
            { 615, "找不到資料庫 ID，資料庫可能已離線" },
            { 911, "資料庫無效" },
            { 948, "資料庫版本不相容" },
            { 1007, "值超出數值表示範圍（最大精度 38）" },
            { 1205, "死鎖" },
            { 1511, "排序無法與事務日誌協調" },
            { 1563, "無法建立約束" },
            { 1742, "無法在包含自連接的視圖上建立索引" },
            { 1750, "無法建立約束" },
            { 1801, "資料庫已存在" },
            { 1807, "獲取資料庫鎖時逾時" },
            { 1834, "設備正由某個現有資源使用" },
            { 18456, "登入失敗" },
            { 2601, "重複鍵" },
            { 2627, "違反唯一約束條件" },
            { 2714, "物件名已存在" },
            { 3701, "物件不存在" },
            { 3902, "COMMIT TRANSACTION 要求沒有對應的 BEGIN TRANSACTION" },
            { 3903, "ROLLBACK TRANSACTION 要求沒有對應的 BEGIN TRANSACTION" },
            { 4060, "無法打開資料庫" },
            { 5028, "系統無法啟動足夠的資料庫來重建日誌" },
            { 5123, "CREATE FILE遇到作業系統錯誤" },
            { 5172, "檔頭不正確" },
            { 7915, "修復: 物件的 IAM 鏈已被截斷，將被重建" },
            { 8623, "內部查詢處理器限制" },
            { 8642, "內部查詢處理器錯誤" },
            { 8651, "記憶體不足" },
            { 9001, "資料庫的日誌不可用；請解決錯誤後重新啟動資料庫" },
            { 9002, "事務日誌已滿" },
            { 10053, "網路連線中斷" },
            { 10054, "現有連線被遠程主機強制關閉" },
            { 10060, "連線逾時" },
            { 10061, "目標計算機積極拒絕連線" },
            { 11001, "找不到主機名" },
            { 11011, "複製表沒有主鍵" },
            { 14001, "應用程式依賴的DLL缺失" },
            { 15601, "目前資料庫未啟用全文搜尋" },
            { 17187, "SQL Server 尚未就緒接受新用戶端連線；請稍候幾分鐘後重試" },
            { 18452, "無法使用 Windows 身份驗證" },
            { 23294, "物件正被另一進程使用" },
            { 26024, "啟動服務失敗" },
            { 99999, "SQL Server 錯誤 - 未知錯誤" }
        };

        internal static Dictionary<long, string> SqlServerErrorsMap => GlobalState.CurrentLanguageType switch
        {
            LanguageType.SimplifiedChinese => SqlServerErrorsMapSimplifiedChinese,
            LanguageType.TraditionalChinese => SqlServerErrorsMapTraditionalChinese,
            _ => SqlServerErrorsMapEnglish
        };
    }
}